 # Generate src/mbio/mb_config.h 
message("Now in buildConfigHeader")

function(buildConfigHeader buildGSF buildTRN buildMbTNav
                           buildGUIs buildTest
                           mbVersion mbVersionDate)

   
   set(outfile ${CMAKE_SOURCE_DIR}/src/mbio/mb_config.h)
   
   file(WRITE ${outfile}
        "// This file automatically generated by build-tools/buildConfigHeader.cmake\n\n")
        
   # Header guard
   file(APPEND ${outfile} "#ifndef __MB_CONFIG_H_\n")
   file(APPEND ${outfile} "#define __MB_CONFIG_H_\n\n")

   include(TestBigEndian)
   test_big_endian(bigEndian)
   file(APPEND ${outfile} "// Bytes are swapped (little-endian)?\n")
   if (bigEndian)
     file(APPEND ${outfile} "#undef BYTESWAPPED\n\n")
   else()
     file(APPEND ${outfile} "#define BYTESWAPPED\n\n")
   endif()
   
   file(APPEND ${outfile} "// Build with GSF?\n")
   if (${buildGSF})
      file(APPEND ${outfile} "#define ENABLE_GSF\n\n")
   else()
      file(APPEND ${outfile} "#undef ENABLE_GSF\n\n")
   endif()
   
   file(APPEND ${outfile} "// Machine is bigendian, (Byteswapping off)?\n")
   file(APPEND ${outfile} "#define ENDIAN_BIG ${bigEndian}\n\n")
#[[ Not referenced
   file(APPEND ${outfile} "// Compiler supports basic C++11 syntax?\n")
   if (${CMAKE_CXX_STANDARD} EQUAL 11)
     file(APPEND ${outfile} "#define HAVE_CXX11\n\n")
   else()
     file(APPEND ${outfile} "#undef HAVE_CXX11\n\n")
   endif()
 ]]

#[[ Not referenced
   file(APPEND ${outfile} "// Have <dlfcn.h>?\n")
   find_file(fn1 "dlfcn.h" NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn1} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#define HAVE_DLFCN_H\n\n")
   else()
     file(APPEND ${outfile} "#undef HAVE_DLFCN_H\n\n")   
   endif()
]]

#[[     
/*
/* Have `gsincos' function. */
/* #undef HAVE_GSINCOS */
]]

#[[ Not referenced
  file(APPEND ${outfile} "// Have <inttypes.h>?\n")
   message("CMAKE_SYSTEM_PREFIX_PATH: ${CMAKE_SYSTEM_PREFIX_PATH}")
   find_file(fn2 "inttypes.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   message("AFTER - fn2: ${fn2}")
   if (${fn2} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_INTTYPES_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_INTTYPES_H\n\n")   
   endif()
]]

#[[ Not referenced
   file(APPEND ${outfile} "// Have `m' (math) library\n")
   message("CMAKE_SYSTEM_LIBRARY_PATH: ${CMAKE_SYSTEM_LIBRARY_PATH}")
   find_library(lib1 "m" NO_CACHE)
   message("lib1: ${lib1}")
   if (${lib1} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_LIBM\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_LIBM\n\n")   
   endif()
]]

#[[ Not referenced
   file(APPEND ${outfile} "// Have `pthread' library?\n")
   find_library(lib2 "pthread" NO_CACHE)
   message("lib2: ${lib2}")
   if (${lib2} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_LIBPTHREAD\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_LIBPTHREAD\n\n")   
   endif()
]]

   file(APPEND ${outfile} "// Have <malloc.h>?\n")
   find_file(fn3 "malloc.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn3} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_MALLOC_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_MALLOC_H\n\n") 
   endif()

   file(APPEND ${outfile} "// Have <rpc/rpc.h>?\n")
   find_file(fn4 "rpc/rpc.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn4} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_RPC_RPC_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_RPC_RPC_H\n\n")
   endif()
   
#[[

#define HAVE_RPC_RPC_H 1
/* Have `sincos' function. */
/* #undef HAVE_SINCOS */
]]

   file(APPEND ${outfile} "// Have <stdint.h>?\n")
   find_file(fn5 "stdint.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn5} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_STDINT_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_STDINT_H\n\n")
   endif()

#[[ Not referenced
   file(APPEND ${outfile} "// Have <stdio.h>?\n")
   find_file(fn6 "stdio.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn6} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_STDIO_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_STDIO_H\n\n")
   endif()
]]

#[[ Not referenced
   file(APPEND ${outfile} "// Have <stdlib.h>?\n")
   find_file(fn7 "stdlib.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn7} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_STDLIB_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_STDLIB_H\n\n")
   endif()
]]

#[[ Not referenced
   file(APPEND ${outfile} "// Have <strings.h>?\n")
   find_file(fn8 "strings.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn8} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_STRINGS_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_STRINGS_H\n\n")
   endif()

   file(APPEND ${outfile} "// Have <string.h>?\n")
   find_file(fn9 "string.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn9} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_STRING_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_STRING_H\n\n")
   endif()

   file(APPEND ${outfile} "// Have <stat.h>?\n")
   find_file(fn10 "sys/stat.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH} ${CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES})
   if (${fn10} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_SYS_STAT_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_SYS_STAT_H\n\n")
   endif()

   file(APPEND ${outfile} "// Have <sys/types.h>?\n")
   find_file(fn11 "sys/types.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn11} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_SYS_TYPES_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_SYS_TYPES_H\n\n")
   endif()

   file(APPEND ${outfile} "// Have <unistd.h>?\n")
   find_file(fn12 "unistd.h" 
             NO_CACHE PATHS ${CMAKE_SYSTEM_PREFIX_PATH})
   if (${fn12} MATCHES "-NOTFOUND")
     file(APPEND ${outfile} "#undef HAVE_UNISTD_H\n\n")
   else()
     file(APPEND ${outfile} "#define HAVE_UNISTD_H\n\n")
   endif()
]]

   file(APPEND ${outfile} "#define MBSYSTEM_CONFIG_DEFINED\n\n")

   file(APPEND ${outfile} "// Installation prefix\n")
   file(APPEND ${outfile} "#define MBSYSTEM_INSTALL_PREFIX \"${CMAKE_INSTALL_PREFIX}\"\n\n")   

   file(APPEND ${outfile} "// Package version\n")
   file(APPEND ${outfile} "#define PACKAGE_VERSION \"${mbVersion}\"\n\n")
   file(APPEND ${outfile} "// Redundant to PACKAGE_VERSION?\n")
   file(APPEND ${outfile} "#define VERSION \"${mbVersion}\"\n\n")

   # Get date that version was committed
   file(APPEND ${outfile} "// Package version date\n")
   file(APPEND ${outfile} "#define VERSION_DATE \"${mbVersionDate}\"\n\n")

   set(packageName "mbsystem")
   
   file(APPEND ${outfile} "// Define full package name \n")
   file(APPEND ${outfile} "#define PACKAGE \"${packageName}\"\n\n")

   file(APPEND ${outfile} "// Define full package name and version\n")
   file(APPEND ${outfile} "#define PACKAGE_STRING ${packageName} \"${gitVersion}\"\n\n")
   

   file(APPEND ${outfile} "// Define package short name\n")
   file(APPEND ${outfile} "#define PACKAGE_TARNAME \"mbsystem\"\n\n")

#[[ Not referenced
   file(APPEND ${outfile} "// Build tools using OpenCV?\n")
   file(APPEND ${outfile} "#define OPENCVTOOLS_ENABLED ${openCVEnabled}\n\n")
]]

   file(APPEND ${outfile} "// Address where bug reports for this package should be sent.\n")
   file(APPEND ${outfile}
               "#define PACKAGE_BUGREPORT \"http://listserver.mbari.org/sympa/arc/mbsystem\"\n\n")

   file(APPEND ${outfile} "// Package homepage\n")
   file(APPEND ${outfile} "#define PACKAGE_URL \"http://www.mbari.org/data/mbsystem/\"\n\n")


#[[ Not referenced
   file(APPEND ${outfile} "// Build libmbtnav and embed TRN instance in mbtrnpp?\n")
   if (${buildTNav})
      file(APPEND ${outfile} "#define MBTNAV_ENABLED\n\n")
   else()
      file(APPEND ${outfile} "#undef MBTNAV_ENABLED 0\n\n")
   endif()

]]

   file(APPEND ${outfile} "// Build libmbtrn and mbtrnpp?\n")
   if (${buildTRN})
      file(APPEND ${outfile} "#define MBTRN_ENABLED\n\n")
   else()
      file(APPEND ${outfile} "#undef MBTRN_ENABLED\n\n")
   endif()

#[[ Not referenced
   file(APPEND ${outfile} "// Build graphical tools?\n")
   if (${buildGUIs})
      file(APPEND ${outfile} "#define MB_GRAPHICAL_ENABLED\n\n")
   else()
      file(APPEND ${outfile} "#undef MB_GRAPHICAL_ENABLED\n\n")   
   endif()

   file(APPEND ${outfile} "//Build unit tests?\n")
   if (${buildTest})
      file(APPEND ${outfile} "#define TEST_ENABLED\n\n")
   else()
      file(APPEND ${outfile} "#undefine TEST_ENABLED\n\n")   
   endif()
]]


#[[

/* Build tools using PCL */
/* #undef PCLTOOLS_ENABLED */
/* Build tools using Qt5 */
/* #undef QTTOOLS_ENABLED */
/* Define to 1 if all of the C90 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */


/* Version number of package */
/*
#define VERSION "5.7.9beta26"


/* Define WORDS_BIGENDIAN to 1 if your processor stores words with the most
   significant byte first (like Motorola and SPARC, unlike Intel). */
#if defined AC_APPLE_UNIVERSAL_BUILD
# if defined __BIG_ENDIAN__
#  define WORDS_BIGENDIAN 1
# endif
#else
# ifndef WORDS_BIGENDIAN
/* #  undef WORDS_BIGENDIAN */
# endif
#endif

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to the type of a signed integer type of width exactly 8 bits if such
   a type exists and the standard includes do not define it. */
/* #undef int8_t */
]]

# End header guard
file(APPEND ${outfile} "#endif    // MB_CONFIG_H_\n")

endfunction()
