#pragma once

#include "./geometry.h"

#include <cstddef>
#include <string>

/*
 * A position on the Earth's surface defined by latitude, longitude, and
 * elevation. Longitude and latitude are angular values in decimal degrees;
 * elevation is linear meters and follows the project convention of negative
 * values downward.
 */
struct GeodeticPosition {
	double longitude = 0.0;
	double latitude = 0.0;
	double elevation = 0.0;
};

struct CoordinateFrame {
	GeodeticPosition origin;
	double meters_per_degree_lon = 0.0;
	double meters_per_degree_lat = 0.0;
};

struct GeographicBounds {
	double degrees_N = 90.0;
	double degrees_S = -90.0;
	double degrees_E = 180.0;
	double degrees_W = -180.0;

	[[nodiscard]] bool contains(double lon, double lat) const;
};

/*
 * A sounding is the specific, calculated depth point generated by a single
 * valid beam. Invalid and null beams should be filtered out when extracting
 * soundings from a ping. The original flag is retained for diagnostics only.
 */
struct Sounding {
	GeodeticPosition position;
	std::size_t beam_index = 0;
	char beam_flag = 0;
};

struct Beam {
	Sounding sounding;
};

/*
 * Metadata for a single sonar ping fired by the multi-beam sonar sensor.
 * Consists of multiple narrow, directional beams arranged in a wide,
 * fan-shaped pattern covering a "swath" of the seafloor.
 */
struct Ping {
	double timestamp = 0.0;
	GeodeticPosition sensor_position;
};

/*
 * Metadata for one swath-sonar file. Contains multiple pings collected by the
 * sensor at different times and positions. Pings should be processed
 * incrementally rather than being retained in memory.
 */
struct SwathFile {
	std::string path;
	int format = 0;
};
