#!/bin/csh
$CMPGCTP/testproj < parm6 > testfile
$CMPGCTP/testproj < parm6a >> testfile
$CMPGCTP/testproj < parm6b >> testfile
$CMPGCTP/testproj < parm6c >> testfile
$CMPGCTP/testproj < parm6d >> testfile
$CMPGCTP/testproj < parm6e >> testfile
