import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

// Grid Parameters panel — place inside any parent Item.
//
// Inbound properties (set from C++ or parent QML):
//   swathNames    – list<string>  display names for swath files
//   gridInfo      – string        formatted read-only grid summary
//   cellSize      – real          current cell size in metres (0.01–3.00)
//   algorithm     – int           0 = Simple Mean, 1 = Footprint, 2 = Shoal Bias
//   interpScale   – int           interpolation radius in grid cells (≥1)
//
// Outbound signals (connect to C++ slots):
//   selectionChanged(var indices)   – explicit signal; list of selected file indices (0-based)
//   cellSizeChanged()               – auto-generated by property cellSize
//   algorithmChanged()              – auto-generated by property algorithm
//   interpScaleChanged()            – auto-generated by property interpScale

Item {
    id: root

    // ── Inbound ──────────────────────────────────────────────────────────────
    property var    swathNames:   []
    property string gridInfo:     ""
    property real   cellSize:     0.50
    property int    algorithm:    0
    property int    interpScale:  1

    // Upper bound of the interpolation-scale slider; adjust as needed.
    property int interpScaleMax: 20

    // ── Outbound ─────────────────────────────────────────────────────────────
    // cellSize, algorithm, and interpScale use their auto-generated property
    // change signals (cellSizeChanged, algorithmChanged, interpScaleChanged).
    // Explicitly redeclaring them would collide — don't.
    signal selectionChanged(var indices)
    signal accepted()   ///< User clicked OK
    signal rejected()   ///< User clicked Cancel

    // ── Internal ─────────────────────────────────────────────────────────────
    // Tracks which swath indices the user has checked.
    property var _selected: []

    function _toggleIndex(idx, on) {
        var s = _selected.slice()
        var pos = s.indexOf(idx)
        if (on  && pos < 0) s.push(idx)
        if (!on && pos >= 0) s.splice(pos, 1)
        _selected = s
        selectionChanged(s)
    }

    // Propagate the layout's natural size upward so a parent Window can
    // bind its width/height to gridParameters.implicitWidth/Height.
    // The +16 accounts for the 8 px margin on each side.
    implicitWidth:  mainLayout.implicitWidth  + 16
    implicitHeight: mainLayout.implicitHeight + 16

    // ── Layout ───────────────────────────────────────────────────────────────
    ColumnLayout {
        id: mainLayout
        anchors.fill: parent
        anchors.margins: 8
        spacing: 12

        // ── Swath file list (multi-select via checkboxes) ─────────────────
        Label {
            text: qsTr("Swath Files")
            font.bold: true
        }

        Rectangle {
            Layout.fillWidth: true
            Layout.preferredHeight: 180
            border.color: palette.mid
            border.width: 1
            radius: 3
            clip: true
            color: palette.base

            ListView {
                id: fileList
                anchors.fill: parent
                anchors.margins: 2
                model: root.swathNames
                clip: true

                ScrollBar.vertical: ScrollBar { policy: ScrollBar.AsNeeded }

                delegate: ItemDelegate {
                    width: fileList.width
                    padding: 2
                    highlighted: root._selected.indexOf(index) >= 0

                    contentItem: RowLayout {
                        spacing: 4

                        CheckBox {
                            checked: root._selected.indexOf(index) >= 0
                            onToggled: root._toggleIndex(index, checked)
                        }

                        Label {
                            text: modelData
                            elide: Text.ElideLeft
                            Layout.fillWidth: true
                        }
                    }
                }
            }
        }

        // ── Grid parameters (read-only) ───────────────────────────────────
        Label {
            text: qsTr("Current Grid Parameters")
            font.bold: true
        }

        Rectangle {
            Layout.fillWidth: true
            implicitHeight: gridInfoLabel.implicitHeight + 16
            border.color: palette.mid
            border.width: 1
            radius: 3
            color: palette.window

            Label {
                id: gridInfoLabel
                anchors { left: parent.left; right: parent.right; top: parent.top; margins: 8 }
                text: root.gridInfo.length > 0 ? root.gridInfo : qsTr("—")
                wrapMode: Text.WordWrap
                font.family: "Monospace"
                font.pixelSize: 12
                color: palette.windowText
            }
        }

        // ── Cell size slider + text field ─────────────────────────────────
        Label {
            text: qsTr("Grid Cell Size")
            font.bold: true
        }

        RowLayout {
            Layout.fillWidth: true
            spacing: 6

            Slider {
                id: cellSizeSlider
                Layout.fillWidth: true
                from: 0.01
                to: 3.00
                stepSize: 0.01
                value: root.cellSize

                onMoved: {
                    var v = Math.round(value * 100) / 100   // snap to 0.01
                    root.cellSize = v
                    cellSizeField.text = v.toFixed(2)
                    // cellSizeChanged fires automatically via property binding
                }
            }

            TextField {
                id: cellSizeField
                Layout.preferredWidth: 64
                horizontalAlignment: Text.AlignRight
                text: root.cellSize.toFixed(2)
                inputMethodHints: Qt.ImhFormattedNumbersOnly
                validator: DoubleValidator {
                    bottom: 0.01
                    top: 3.00
                    decimals: 2
                    notation: DoubleValidator.StandardNotation
                }
                onEditingFinished: {
                    var v = parseFloat(text)
                    if (isNaN(v)) { text = root.cellSize.toFixed(2); return }
                    v = Math.max(0.01, Math.min(3.00, Math.round(v * 100) / 100))
                    root.cellSize = v
                    cellSizeSlider.value = v
                    text = v.toFixed(2)
                    // cellSizeChanged fires automatically via property binding
                }
            }

            Label { text: qsTr("m") }
        }

        // ── Gridding algorithm (radio buttons) ────────────────────────────
        Label {
            text: qsTr("Gridding Algorithm")
            font.bold: true
        }

        // ButtonGroup makes the three RadioButtons mutually exclusive even
        // though they are created by a Repeater.
        ButtonGroup { id: algGroup }

        ColumnLayout {
            spacing: 0

            Repeater {
                model: [qsTr("Simple Mean"), qsTr("Footprint"), qsTr("Shoal Bias")]

                RadioButton {
                    text: modelData
                    checked: root.algorithm === index
                    ButtonGroup.group: algGroup
                    onClicked: {
                        root.algorithm = index
                        // algorithmChanged fires automatically via property binding
                    }
                }
            }
        }

        // ── Interpolation scale slider ────────────────────────────────────
        Label {
            text: qsTr("Interpolation Scale")
            font.bold: true
        }

        RowLayout {
            Layout.fillWidth: true
            spacing: 6

            Slider {
                id: interpSlider
                Layout.fillWidth: true
                from: 1
                to: root.interpScaleMax
                stepSize: 1
                value: root.interpScale
                snapMode: Slider.SnapAlways

                onMoved: {
                    root.interpScale = Math.round(value)
                    // interpScaleChanged fires automatically via property binding
                }
            }

            Label {
                text: root.interpScale + " " +
                      (root.interpScale === 1 ? qsTr("cell") : qsTr("cells"))
                horizontalAlignment: Text.AlignRight
                Layout.preferredWidth: 64
            }
        }

        // Push content up so the button row stays at the bottom.
        Item { Layout.fillHeight: true }

        // ── Separator ─────────────────────────────────────────────────────
        Rectangle {
            Layout.fillWidth: true
            Layout.topMargin: 4
            height: 1
            color: palette.mid
        }

        // ── OK / Cancel ───────────────────────────────────────────────────
        RowLayout {
            Layout.fillWidth: true
            Layout.topMargin: 4
            Layout.bottomMargin: 4
            spacing: 8

            Item { Layout.fillWidth: true }   // push buttons to the right

            Button {
                text: qsTr("Cancel")
                onClicked: root.rejected()
            }

            Button {
                text: qsTr("OK")
                highlighted: true             // accent colour on most styles
                onClicked: root.accepted()
            }
        }
    }
}
