#!/bin/csh
$CMPGCTP/testproj < parm20101 > testfile
$CMPGCTP/testproj < parm20503 >> testfile
$CMPGCTP/testproj < parm21301 >> testfile
$CMPGCTP/testproj < parm21703 >> testfile
$CMPGCTP/testproj < parm22201 >> testfile
$CMPGCTP/testproj < parm22701 >> testfile
$CMPGCTP/testproj < parm22900 >> testfile
$CMPGCTP/testproj < parm23003 >> testfile
$CMPGCTP/testproj < parm23601 >> testfile
$CMPGCTP/testproj < parm23800 >> testfile
$CMPGCTP/testproj < parm24002 >> testfile
$CMPGCTP/testproj < parm24400 >> testfile
$CMPGCTP/testproj < parm24803 >> testfile
$CMPGCTP/testproj < parm25001 >> testfile
$CMPGCTP/testproj < parm25009 >> testfile
$CMPGCTP/testproj < parm25104 >> testfile
$CMPGCTP/testproj < parm25400 >> testfile
