#------------------------------------------------------------------------------
# MacOs Sierra configure script command line example:
#------------------------------------------------------------------------------
#
# Install MB-System into /usr/local on a Mac running MacOS 10.12 Sierra with most
# prerequisites installed using the homebrew package manager. The other two
# prerequisites are to install the Xcode compiler suite from the Apple App Store
# and to install the X11 windowing system by downloading the XQuartz
# package from xquartz.org.
#
# The primary prerequisite homebrew packages can be installed using:
brew install gdal netcdf proj fftw gv openmotif
brew install homebrew/science/gmt
#
# The tide modeling software package OTPS from Oregon State University can be
# downloaded from: http://volkov.oce.orst.edu/tides/otps.html and installed
# manually (typically in /usr/local/OTPS2 or /usr/local/src/OTPS2.
# Optionally, a homebrew tap is available:
brew install dwcaress/mbsystem/otps --with-tpxo8
#
# These steps assume you have downloaded an MB-System distribution tar.gz file 
# from the ftp site:
#       ftp://mbsystemftp@ftp.mbari.org
# The current distribution file is mbsystem-5.5.2307.tar.gz
# 
# First, unpack the distribution using tar. This can be done in any location,
# but if one is working in a root-owned area such as /usr/local/src, obtaining
# root privileges using sudo is necessary for all steps:
#       sudo tar xvzf mbsystem-5.5.2307.tar.gz
# and then cd into the resulting directory:
#       cd mbsystem-5.5.2307
#
# The following MB-System configure command will work with all prerequisites
# installed via homebrew with the commands listed above:
sudo CFLAGS="-I/opt/X11/include" LDFLAGS="-L/opt/X11/lib" \
./configure \
    --prefix=/usr/local \
    --with-proj-include=/usr/local/include \
    --with-proj-lib=/usr/local/lib \
    --with-fftw-include=/usr/local/include \
    --with-fftw-lib=/usr/local/lib \
    --with-motif-include=/usr/local/include \
    --with-motif-lib=/usr/local/lib \
    --with-otps-dir=/usr/local/opt/otps
#
# Once the makefiles have been generated by configure, build and install
# MB-System using:
        sudo make
        sudo make install
#
#------------------------------------------------------------------------------
