/*
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 * Generated by the ICS Builder Xcessory (BX).
 *
 *
 * Builder Xcessory 3.5.1.
 *
 */
#include <Xm/Xm.h>
#include <Xm/MainW.h>
#include <Xm/RowColumn.h>
#include <Xm/CascadeB.h>
#include <Xm/PushB.h>
#include <Xm/BulletinB.h>
#include <Xm/ToggleB.h>
#include <Xm/ScrolledW.h>
#include <Xm/DrawingA.h>
#include <Xm/Label.h>
#include <Xm/Scale.h>
#include <Xm/DialogS.h>
#include <Xm/MwmUtil.h>
#include <Xm/TextF.h>
#include <Xm/FileSB.h>

/*
 * Global declarations are now stored in the header file.
 *
 * If DECLARE_BX_GLOBALS is defined then this header file
 * declares the globals, otherwise it just externs them.
 */
#define DECLARE_BX_GLOBALS

/*
 * Globally included information.
 */


/*
 * Common constant and pixmap declarations.
 */
#include "mbnavedit_creation.h"

/*
 * Convenience functions from utilities file.
 */
extern void RegisterBxConverters();
extern XtPointer CONVERT();
extern XtPointer DOUBLE();
extern XtPointer SINGLE();
extern void MENU_POST();
extern Pixmap XPM_PIXMAP();
extern void SET_BACKGROUND_COLOR();

/*
 * Declarations for callbacks and handlers.
 */
void BxExitCB();
void do_nextbuffer();
void do_done();
void do_forward();
void do_reverse();
void BxManageCB();
void BxSetValuesCB();
void do_toggle_vru();
void do_set_interval();
void do_showall();
void do_revert();
void do_interpolation();
void do_button_use_cmg();
void do_toggle_show_cmg();
void do_toggle_org_heading();
void do_button_use_smg();
void do_toggle_show_smg();
void do_toggle_org_speed();
void do_toggle_org_lat();
void do_toggle_org_lon();
void do_toggle_speed();
void do_toggle_heading();
void do_toggle_lat();
void do_toggle_lon();
void do_timestep();
void do_timespan();
void do_toggle_pick();
void do_toggle_select();
void do_toggle_deselect();
void do_toggle_selectall();
void do_toggle_deselectall();
void do_resize();
void do_event();
void do_fileselection_nomatch();
void do_fileselection_ok();
void BxUnmanageCB();
void do_fileselection_filter();
void do_fileselection_cancel();
void do_toggle_output_on();
void do_toggle_output_off();

/*
 * Create the mainWindow hierarchy of widgets.
 */
Widget
CreatemainWindow(parent)
Widget parent;
{
    Arg      args[256];
    Cardinal ac=0;
    Boolean  argok=False;
    Widget   mainWindow;
    Widget   menuBar;
    Widget   cascadeButton_file;
    Widget   pulldownMenu_file;
    Widget   pushButton_openmb;
    Widget   cascadeButton_nextbuffer;
    Widget   cascadeButton_done;
    Widget   cascadeButton_forward;
    Widget   cascadeButton_reverse;
    Widget   cascadeButton_quit;
    Widget   bulletinBoard;
    Widget   pushButton_set_interval;
    Widget   pushButton_showall;
    
    /*
     * Register the converters for the widgets.
     */
    RegisterBxConverters(XtWidgetToApplicationContext(parent)); 
    XtInitializeWidgetClass(xmMainWindowWidgetClass);
    XtInitializeWidgetClass(xmRowColumnWidgetClass);
    XtInitializeWidgetClass(xmCascadeButtonWidgetClass);
    XtInitializeWidgetClass(xmRowColumnWidgetClass);
    XtInitializeWidgetClass(xmPushButtonWidgetClass);
    XtInitializeWidgetClass(xmBulletinBoardWidgetClass);
    XtInitializeWidgetClass(xmToggleButtonWidgetClass);
    XtInitializeWidgetClass(xmRowColumnWidgetClass);
    XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
    XtInitializeWidgetClass(xmDrawingAreaWidgetClass);
    XtInitializeWidgetClass(xmLabelWidgetClass);
    XtInitializeWidgetClass(xmScaleWidgetClass);
    XtInitializeWidgetClass(xmDialogShellWidgetClass);
    XtInitializeWidgetClass(xmBulletinBoardWidgetClass);
    XtInitializeWidgetClass(xmTextFieldWidgetClass);
    XtInitializeWidgetClass(xmFileSelectionBoxWidgetClass);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 132); ac++;
    XtSetArg(args[ac], XmNy, 167); ac++;
    XtSetArg(args[ac], XmNwidth, 1140); ac++;
    XtSetArg(args[ac], XmNheight, 849); ac++;
    mainWindow = XmCreateMainWindow(parent,
        "mainWindow",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNentryAlignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNpacking, XmPACK_NONE); ac++;
    XtSetArg(args[ac], XmNwidth, 1140); ac++;
    XtSetArg(args[ac], XmNheight, 29); ac++;
    menuBar = XmCreateMenuBar(mainWindow,
        "menuBar",
        args, 
        ac);
    XtManageChild(menuBar);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "File", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 5); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 41); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    cascadeButton_file = XmCreateCascadeButton(menuBar,
        "cascadeButton_file",
        args, 
        ac);
    XtManageChild(cascadeButton_file);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 137); ac++;
    XtSetArg(args[ac], XmNy, 196); ac++;
    XtSetArg(args[ac], XmNwidth, 242); ac++;
    XtSetArg(args[ac], XmNheight, 31); ac++;
    pulldownMenu_file = XmCreatePulldownMenu(XtParent(cascadeButton_file),
        "pulldownMenu_file",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Open Multibeam File", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    pushButton_openmb = XmCreatePushButton(pulldownMenu_file,
        "pushButton_openmb",
        args, 
        ac);
    XtManageChild(pushButton_openmb);
    XtAddCallback(pushButton_openmb, XmNactivateCallback, BxManageCB, (XtPointer)"bulletinBoard_fileselection");
    XtAddCallback(pushButton_openmb, XmNactivateCallback, BxSetValuesCB, (XtPointer)"label_format.labelString=MBIO Format ID:");
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, pulldownMenu_file); ac++;
    XtSetValues(cascadeButton_file, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Next Buffer", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 119); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 92); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    cascadeButton_nextbuffer = XmCreateCascadeButton(menuBar,
        "cascadeButton_nextbuffer",
        args, 
        ac);
    XtManageChild(cascadeButton_nextbuffer);
    XtAddCallback(cascadeButton_nextbuffer, XmNactivateCallback, do_nextbuffer, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Done", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 317); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 53); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    cascadeButton_done = XmCreateCascadeButton(menuBar,
        "cascadeButton_done",
        args, 
        ac);
    XtManageChild(cascadeButton_done);
    XtAddCallback(cascadeButton_done, XmNactivateCallback, do_done, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Forward", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 431); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 73); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    cascadeButton_forward = XmCreateCascadeButton(menuBar,
        "cascadeButton_forward",
        args, 
        ac);
    XtManageChild(cascadeButton_forward);
    XtAddCallback(cascadeButton_forward, XmNactivateCallback, do_forward, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Reverse", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 581); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 73); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    cascadeButton_reverse = XmCreateCascadeButton(menuBar,
        "cascadeButton_reverse",
        args, 
        ac);
    XtManageChild(cascadeButton_reverse);
    XtAddCallback(cascadeButton_reverse, XmNactivateCallback, do_reverse, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Quit", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 1000); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 46); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    cascadeButton_quit = XmCreateCascadeButton(menuBar,
        "cascadeButton_quit",
        args, 
        ac);
    XtManageChild(cascadeButton_quit);
    XtAddCallback(cascadeButton_quit, XmNactivateCallback, BxExitCB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNwidth, 1140); ac++;
    XtSetArg(args[ac], XmNheight, 820); ac++;
    bulletinBoard = XmCreateBulletinBoard(mainWindow,
        "bulletinBoard",
        args, 
        ac);
    XtManageChild(bulletinBoard);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Roll, Pitch, and Heave Plots", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 730); ac++;
    XtSetArg(args[ac], XmNwidth, 219); ac++;
    XtSetArg(args[ac], XmNheight, 26); ac++;
    toggleButton_vru = XmCreateToggleButton(bulletinBoard,
        "toggleButton_vru",
        args, 
        ac);
    XtManageChild(toggleButton_vru);
    XtAddCallback(toggleButton_vru, XmNvalueChangedCallback, do_toggle_vru, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Pick Time Interval", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 40); ac++;
    XtSetArg(args[ac], XmNy, 200); ac++;
    XtSetArg(args[ac], XmNwidth, 170); ac++;
    XtSetArg(args[ac], XmNheight, 50); ac++;
    pushButton_set_interval = XmCreatePushButton(bulletinBoard,
        "pushButton_set_interval",
        args, 
        ac);
    XtManageChild(pushButton_set_interval);
    XtAddCallback(pushButton_set_interval, XmNactivateCallback, do_set_interval, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Show Entire Buffer", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 40); ac++;
    XtSetArg(args[ac], XmNy, 120); ac++;
    XtSetArg(args[ac], XmNwidth, 170); ac++;
    XtSetArg(args[ac], XmNheight, 50); ac++;
    pushButton_showall = XmCreatePushButton(bulletinBoard,
        "pushButton_showall",
        args, 
        ac);
    XtManageChild(pushButton_showall);
    XtAddCallback(pushButton_showall, XmNactivateCallback, do_showall, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Revert Selection", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 850); ac++;
    XtSetArg(args[ac], XmNy, 60); ac++;
    XtSetArg(args[ac], XmNwidth, 190); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    pushButton_revert = XmCreatePushButton(bulletinBoard,
        "pushButton_revert",
        args, 
        ac);
    XtManageChild(pushButton_revert);
    XtAddCallback(pushButton_revert, XmNactivateCallback, do_revert, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Interpolate Selection", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 640); ac++;
    XtSetArg(args[ac], XmNy, 60); ac++;
    XtSetArg(args[ac], XmNwidth, 190); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    pushButton_interpolate = XmCreatePushButton(bulletinBoard,
        "pushButton_interpolate",
        args, 
        ac);
    XtManageChild(pushButton_interpolate);
    XtAddCallback(pushButton_interpolate, XmNactivateCallback, do_interpolation, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNisHomogeneous, False); ac++;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNpacking, XmPACK_TIGHT); ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 640); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 432); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    radioBox = XmCreateRadioBox(bulletinBoard,
        "radioBox",
        args, 
        ac);
    XtManageChild(radioBox);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Pick", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNwidth, 56); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    toggleButton_pick = XmCreateToggleButton(radioBox,
        "toggleButton_pick",
        args, 
        ac);
    XtManageChild(toggleButton_pick);
    XtAddCallback(toggleButton_pick, XmNvalueChangedCallback, do_toggle_pick, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Select", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNwidth, 69); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    toggleButton_select = XmCreateToggleButton(radioBox,
        "toggleButton_select",
        args, 
        ac);
    XtManageChild(toggleButton_select);
    XtAddCallback(toggleButton_select, XmNvalueChangedCallback, do_toggle_select, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Deselect", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNwidth, 86); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    toggleButton_deselect = XmCreateToggleButton(radioBox,
        "toggleButton_deselect",
        args, 
        ac);
    XtManageChild(toggleButton_deselect);
    XtAddCallback(toggleButton_deselect, XmNvalueChangedCallback, do_toggle_deselect, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Select All", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNwidth, 93); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    toggleButton_selectall = XmCreateToggleButton(radioBox,
        "toggleButton_selectall",
        args, 
        ac);
    XtManageChild(toggleButton_selectall);
    XtAddCallback(toggleButton_selectall, XmNvalueChangedCallback, do_toggle_selectall, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Deselect All", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNwidth, 110); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    toggleButton_deselectall = XmCreateToggleButton(radioBox,
        "toggleButton_deselectall",
        args, 
        ac);
    XtManageChild(toggleButton_deselectall);
    XtAddCallback(toggleButton_deselectall, XmNvalueChangedCallback, do_toggle_deselectall, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Use Course-Made-Good", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 30); ac++;
    XtSetArg(args[ac], XmNy, 690); ac++;
    XtSetArg(args[ac], XmNwidth, 210); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    pushButton_heading_cmg = XmCreatePushButton(bulletinBoard,
        "pushButton_heading_cmg",
        args, 
        ac);
    XtManageChild(pushButton_heading_cmg);
    XtAddCallback(pushButton_heading_cmg, XmNactivateCallback, do_button_use_cmg, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Show Course-Made-Good", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 30); ac++;
    XtSetArg(args[ac], XmNy, 660); ac++;
    XtSetArg(args[ac], XmNwidth, 220); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    toggleButton_show_cmg = XmCreateToggleButton(bulletinBoard,
        "toggleButton_show_cmg",
        args, 
        ac);
    XtManageChild(toggleButton_show_cmg);
    XtAddCallback(toggleButton_show_cmg, XmNvalueChangedCallback, do_toggle_show_cmg, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Show Original Data", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 30); ac++;
    XtSetArg(args[ac], XmNy, 630); ac++;
    XtSetArg(args[ac], XmNwidth, 180); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    toggleButton_org_heading = XmCreateToggleButton(bulletinBoard,
        "toggleButton_org_heading",
        args, 
        ac);
    XtManageChild(toggleButton_org_heading);
    XtAddCallback(toggleButton_org_heading, XmNvalueChangedCallback, do_toggle_org_heading, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Use Speed-Made-Good", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 30); ac++;
    XtSetArg(args[ac], XmNy, 560); ac++;
    XtSetArg(args[ac], XmNwidth, 200); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    pushButton_speed_smg = XmCreatePushButton(bulletinBoard,
        "pushButton_speed_smg",
        args, 
        ac);
    XtManageChild(pushButton_speed_smg);
    XtAddCallback(pushButton_speed_smg, XmNactivateCallback, do_button_use_smg, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Show Speed-Made-Good", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 30); ac++;
    XtSetArg(args[ac], XmNy, 530); ac++;
    XtSetArg(args[ac], XmNwidth, 220); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    toggleButton_show_smg = XmCreateToggleButton(bulletinBoard,
        "toggleButton_show_smg",
        args, 
        ac);
    XtManageChild(toggleButton_show_smg);
    XtAddCallback(toggleButton_show_smg, XmNvalueChangedCallback, do_toggle_show_smg, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Show Original Data", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 30); ac++;
    XtSetArg(args[ac], XmNy, 500); ac++;
    XtSetArg(args[ac], XmNwidth, 210); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    toggleButton_org_speed = XmCreateToggleButton(bulletinBoard,
        "toggleButton_org_speed",
        args, 
        ac);
    XtManageChild(toggleButton_org_speed);
    XtAddCallback(toggleButton_org_speed, XmNvalueChangedCallback, do_toggle_org_speed, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Show Original Data", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 30); ac++;
    XtSetArg(args[ac], XmNy, 430); ac++;
    XtSetArg(args[ac], XmNwidth, 180); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    toggleButton_org_lat = XmCreateToggleButton(bulletinBoard,
        "toggleButton_org_lat",
        args, 
        ac);
    XtManageChild(toggleButton_org_lat);
    XtAddCallback(toggleButton_org_lat, XmNvalueChangedCallback, do_toggle_org_lat, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Show Original Data", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 30); ac++;
    XtSetArg(args[ac], XmNy, 360); ac++;
    XtSetArg(args[ac], XmNwidth, 210); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    toggleButton_org_lon = XmCreateToggleButton(bulletinBoard,
        "toggleButton_org_lon",
        args, 
        ac);
    XtManageChild(toggleButton_org_lon);
    XtAddCallback(toggleButton_org_lon, XmNvalueChangedCallback, do_toggle_org_lon, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Speed Plot", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 470); ac++;
    XtSetArg(args[ac], XmNwidth, 160); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    toggleButton_speed = XmCreateToggleButton(bulletinBoard,
        "toggleButton_speed",
        args, 
        ac);
    XtManageChild(toggleButton_speed);
    XtAddCallback(toggleButton_speed, XmNvalueChangedCallback, do_toggle_speed, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Heading Plot", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 600); ac++;
    XtSetArg(args[ac], XmNwidth, 180); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    toggleButton_heading = XmCreateToggleButton(bulletinBoard,
        "toggleButton_heading",
        args, 
        ac);
    XtManageChild(toggleButton_heading);
    XtAddCallback(toggleButton_heading, XmNvalueChangedCallback, do_toggle_heading, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Latitude Plot", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 400); ac++;
    XtSetArg(args[ac], XmNwidth, 200); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    toggleButton_lat = XmCreateToggleButton(bulletinBoard,
        "toggleButton_lat",
        args, 
        ac);
    XtManageChild(toggleButton_lat);
    XtAddCallback(toggleButton_lat, XmNvalueChangedCallback, do_toggle_lat, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Longitude Plot", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNstringDirection, XmSTRING_DIRECTION_R_TO_L); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 330); ac++;
    XtSetArg(args[ac], XmNwidth, 150); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    toggleButton_lon = XmCreateToggleButton(bulletinBoard,
        "toggleButton_lon",
        args, 
        ac);
    XtManageChild(toggleButton_lon);
    XtAddCallback(toggleButton_lon, XmNvalueChangedCallback, do_toggle_lon, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNscrollingPolicy, XmAUTOMATIC); ac++;
    XtSetArg(args[ac], XmNx, 250); ac++;
    XtSetArg(args[ac], XmNy, 110); ac++;
    XtSetArg(args[ac], XmNwidth, 870); ac++;
    XtSetArg(args[ac], XmNheight, 700); ac++;
    scrolledWindow = XmCreateScrolledWindow(bulletinBoard,
        "scrolledWindow",
        args, 
        ac);
    XtManageChild(scrolledWindow);
    
    ac = 0;
    XtSetArg(args[ac], XmNborderWidth, 1); ac++;
    XtSetArg(args[ac], XmNbackground, 
        CONVERT(parent, "white", 
        XmRPixel, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNwidth, 837); ac++;
    XtSetArg(args[ac], XmNheight, 2000); ac++;
    drawingArea = XmCreateDrawingArea(scrolledWindow,
        "drawingArea",
        args, 
        ac);
    XtManageChild(drawingArea);
    XtAddCallback(drawingArea, XmNresizeCallback, do_resize, (XtPointer)0);
    XtAddCallback(drawingArea, XmNinputCallback, do_event, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "500", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 580); ac++;
    XtSetArg(args[ac], XmNy, 60); ac++;
    XtSetArg(args[ac], XmNwidth, 40); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    label_timestep_2 = XmCreateLabel(bulletinBoard,
        "label_timestep_2",
        args, 
        ac);
    XtManageChild(label_timestep_2);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_END); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Time Step (sec):  1", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 60); ac++;
    XtSetArg(args[ac], XmNwidth, 200); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    label_timestep_1 = XmCreateLabel(bulletinBoard,
        "label_timestep_1",
        args, 
        ac);
    XtManageChild(label_timestep_1);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "500", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 580); ac++;
    XtSetArg(args[ac], XmNy, 30); ac++;
    XtSetArg(args[ac], XmNwidth, 40); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    label_timespan_2 = XmCreateLabel(bulletinBoard,
        "label_timespan_2",
        args, 
        ac);
    XtManageChild(label_timespan_2);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_END); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "TIme Span Shown (sec):  1", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 20); ac++;
    XtSetArg(args[ac], XmNwidth, 200); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    label_timespan_1 = XmCreateLabel(bulletinBoard,
        "label_timespan_1",
        args, 
        ac);
    XtManageChild(label_timespan_1);
    
    ac = 0;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNshowValue, True); ac++;
    XtSetArg(args[ac], XmNx, 210); ac++;
    XtSetArg(args[ac], XmNy, 50); ac++;
    XtSetArg(args[ac], XmNwidth, 360); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    scale_timestep = XmCreateScale(bulletinBoard,
        "scale_timestep",
        args, 
        ac);
    XtManageChild(scale_timestep);
    XtAddCallback(scale_timestep, XmNvalueChangedCallback, do_timestep, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNstringDirection, XmSTRING_DIRECTION_L_TO_R); ac++;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNtitleString, 
        CONVERT(parent, " ", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNshowValue, True); ac++;
    XtSetArg(args[ac], XmNx, 210); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 360); ac++;
    XtSetArg(args[ac], XmNheight, 50); ac++;
    scale_timespan = XmCreateScale(bulletinBoard,
        "scale_timespan",
        args, 
        ac);
    XtManageChild(scale_timespan);
    XtAddCallback(scale_timespan, XmNvalueChangedCallback, do_timespan, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNallowShellResize, False); ac++;
    XtSetArg(args[ac], XmNtitle, "Select Input Data File"); ac++;
    XtSetArg(args[ac], XmNx, 535); ac++;
    XtSetArg(args[ac], XmNy, 280); ac++;
    XtSetArg(args[ac], XmNwidth, 737); ac++;
    XtSetArg(args[ac], XmNheight, 727); ac++;
    xmDialogShell_fileselection = XtCreatePopupShell("xmDialogShell_fileselection",
        xmDialogShellWidgetClass,
        bulletinBoard,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_NONE); ac++;
    XtSetArg(args[ac], XmNx, 535); ac++;
    XtSetArg(args[ac], XmNy, 280); ac++;
    XtSetArg(args[ac], XmNwidth, 737); ac++;
    XtSetArg(args[ac], XmNheight, 727); ac++;
    bulletinBoard_fileselection = XmCreateBulletinBoard(xmDialogShell_fileselection,
        "bulletinBoard_fileselection",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 20); ac++;
    XtSetArg(args[ac], XmNy, 670); ac++;
    XtSetArg(args[ac], XmNwidth, 700); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    textField_output_file = XmCreateTextField(bulletinBoard_fileselection,
        "textField_output_file",
        args, 
        ac);
    XtManageChild(textField_output_file);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Output File Name:", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 630); ac++;
    XtSetArg(args[ac], XmNwidth, 150); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    label_filename = XmCreateLabel(bulletinBoard_fileselection,
        "label_filename",
        args, 
        ac);
    XtManageChild(label_filename);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Output Mode:", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 340); ac++;
    XtSetArg(args[ac], XmNy, 550); ac++;
    XtSetArg(args[ac], XmNwidth, 120); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    label_output_mode = XmCreateLabel(bulletinBoard_fileselection,
        "label_output_mode",
        args, 
        ac);
    XtManageChild(label_output_mode);
    
    ac = 0;
    XtSetArg(args[ac], XmNisHomogeneous, False); ac++;
    XtSetArg(args[ac], XmNx, 360); ac++;
    XtSetArg(args[ac], XmNy, 590); ac++;
    XtSetArg(args[ac], XmNwidth, 165); ac++;
    XtSetArg(args[ac], XmNheight, 61); ac++;
    radioBox_output = XmCreateRadioBox(bulletinBoard_fileselection,
        "radioBox_output",
        args, 
        ac);
    XtManageChild(radioBox_output);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Output Edited Data", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNwidth, 159); ac++;
    XtSetArg(args[ac], XmNheight, 26); ac++;
    toggleButton_output_on = XmCreateToggleButton(radioBox_output,
        "toggleButton_output_on",
        args, 
        ac);
    XtManageChild(toggleButton_output_on);
    XtAddCallback(toggleButton_output_on, XmNvalueChangedCallback, do_toggle_output_on, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Browse Only", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNwidth, 159); ac++;
    XtSetArg(args[ac], XmNheight, 26); ac++;
    toggleButton_output_off = XmCreateToggleButton(radioBox_output,
        "toggleButton_output_off",
        args, 
        ac);
    XtManageChild(toggleButton_output_off);
    XtAddCallback(toggleButton_output_off, XmNvalueChangedCallback, do_toggle_output_off, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 150); ac++;
    XtSetArg(args[ac], XmNy, 550); ac++;
    XtSetArg(args[ac], XmNwidth, 100); ac++;
    XtSetArg(args[ac], XmNheight, 35); ac++;
    textField_format = XmCreateTextField(bulletinBoard_fileselection,
        "textField_format",
        args, 
        ac);
    XtManageChild(textField_format);
    
    ac = 0;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "MBIO Format ID:", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 550); ac++;
    XtSetArg(args[ac], XmNwidth, 150); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    label_format = XmCreateLabel(bulletinBoard_fileselection,
        "label_format",
        args, 
        ac);
    XtManageChild(label_format);
    
    ac = 0;
    XtSetArg(args[ac], XmNbuttonFontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlabelFontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNtextFontList, 
        CONVERT(parent, "-adobe-helvetica-bold-r-normal--14-140-75-75-p-82-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNautoUnmanage, False); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_NONE); ac++;
    XtSetArg(args[ac], XmNnoResize, True); ac++;
    XtSetArg(args[ac], XmNdialogTitle, 
        CONVERT(parent, "", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlistVisibleItemCount, 14); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 720); ac++;
    XtSetArg(args[ac], XmNheight, 540); ac++;
    fileSelectionBox = XmCreateFileSelectionBox(bulletinBoard_fileselection,
        "fileSelectionBox",
        args, 
        ac);
    XtManageChild(fileSelectionBox);
    XtAddCallback(fileSelectionBox, XmNnoMatchCallback, do_fileselection_nomatch, (XtPointer)0);
    XtAddCallback(fileSelectionBox, XmNokCallback, do_fileselection_ok, (XtPointer)0);
    XtAddCallback(fileSelectionBox, XmNokCallback, BxUnmanageCB, (XtPointer)"bulletinBoard_fileselection");
    XtAddCallback(fileSelectionBox, XmNapplyCallback, do_fileselection_filter, (XtPointer)0);
    XtAddCallback(fileSelectionBox, XmNcancelCallback, do_fileselection_cancel, (XtPointer)0);
    XtAddCallback(fileSelectionBox, XmNcancelCallback, BxUnmanageCB, (XtPointer)"bulletinBoard_fileselection");
    
    return( mainWindow );
}
