
/* Begin user code block <abstract> */
/* End user code block <abstract> */

/**
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 *
 * Created by BuilderXcessory Version 6.1.2
 * Generated by Code Generator Xcessory 6.1.2 (07/02/03) CGX Scripts 6.1 Motif 2.1 
 *
 */
#ifndef creation_c_H
#define creation_c_H

/*
 * Global widget declarations.
 *        - EXTERNAL is set to extern if the
 *          defs file is not included from the
 *          main file.
 */
#ifdef DECLARE_BX_GLOBALS
#define EXTERNAL
#else
#define EXTERNAL extern
#endif

#include "MB3DView.h"
/**
 * Start Global Widget Declarations.
 */
EXTERNAL MB3DViewData mbview_mbgrdviz;
/**
 * End Global Widget Declarations.
 */
#endif
