/*
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 *
 * Created by Builder Xcessory Version 5.0.3
 * Generated by Code Generator Xcessory 5.0.1 (09/29/98) 
 *
 */
#ifndef creation_c_H
#define creation_c_H

/*
 * Global widget declarations.
 *        - EXTERNAL is set to extern if the
 *          defs file is not included from the
 *          main file.
 */
#ifdef DECLARE_BX_GLOBALS
#define EXTERNAL
#else
#define EXTERNAL extern
#endif

#include "MB3DView.h"
/*
 * Start Global Widget Declarations.
 */
EXTERNAL MB3DViewData mbview_mbgrdviz;
/*
 * End Global Widget Declarations.
 */
#endif
