/*
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 *
 * Created by Builder Xcessory Version 5.0.3
 * Generated by Code Generator Xcessory 5.0.1 (09/29/98) 
 *
 */
#ifndef mbgrdviz_creation_H
#define mbgrdviz_creation_H

/*
 * Global widget declarations.
 *        - EXTERNAL is set to extern if the
 *          defs file is not included from the
 *          main file.
 */
#ifdef DECLARE_BX_GLOBALS
#define EXTERNAL
#else
#define EXTERNAL extern
#endif

/*
 * Start Global Widget Declarations.
 */
EXTERNAL Widget   dialogShell_open;
EXTERNAL Widget   fileSelectionBox;
EXTERNAL Widget   label_about_version;
EXTERNAL Widget   pushButton_file_openprimary;
EXTERNAL Widget   pulldownMenu_openoverlay;
EXTERNAL Widget   pulldownMenu_openroute;
EXTERNAL Widget   pulldownMenu_opensite;
EXTERNAL Widget   pulldownMenu_opennav;
EXTERNAL Widget   pulldownMenu_saveroute;
EXTERNAL Widget   pulldownMenu_savesite;
/*
 * End Global Widget Declarations.
 */
#endif
