.TH mbm_plot l "17 February 2009" "MB-System 5.0" "MB-System 5.0"
.SH NAME
\fBmbm_plot\fP - Create an executable shellscript which will generate
a GMT plot of swath sonar swath data.

.SH VERSION
Version 5.0

.SH SYNOPSIS
\fBmbm_plot\fP \fB-F\fP\fIformat\fP \fB-I\fP\fIfile\fP 
[\fB-A\fP[\fImagnitude\fP[\fI/azimuth\fP] 
\fB-C\fP\fI[cont_int/col_int/tic_int/lab_int/tic_len/lab_hgt]\fP
\fB-D\fP[\fIflipcolor/flipshade\fP]
\fB-G\fP\fIcolor_mode[F]\fP \fB-H\fP
\fB-N\fP\fI[time_tick/time_annot/date_annot/time_tick_len[/name_hgt] | F | FP]\fP
\fB-O\fP\fIroot\fP \fB-P\fP\fIpagesize \fP
\fB-S\fP\fI[color/shade]\fP \fB-T\fP
\fB-U\fP\fIorientation\fP \fB-V\fP 
\fB-W\fP\fI[color_style\fP[\fI/pallette\fP[\fIncolors\fP]] | \fIcptfile]\fP ]

Additional Options:
.br
[\fB-B\fP\fItickinfo\fP
\fB-J\fP\fIprojection\fP[\fI/scale | width\fP]
\fB-L\fP\fItitle\fP[\fI:scale_label\fP] \fB-M\fP\fImisc\fP 
\fB-Q\fP \fB-R\fP\fIw/e/s/n\fP \fB-X\fP \fB-Y\fP 
\fB-Z\fP\fImin/max\fP ]

Miscellaneous Options:
.br
[\fB-MGD\fP\fIgmtdef/value\fP 
\fB-MGF\fP\fIscale_loc\fP
\fB-MGL\fP[\fIf\fP][\fIx\fP]\fIlon0/lat0/slat/length\fP[\fIm\fP]
\fB-MGQ\fP\fIdpi\fP 
\fB-MGT\fP\fIx/y/size/angle/font/just/text\fP
\fB-MGU\fP\fP[\fI/dx/dy/\fP][\fIlabel\fP] 
\fB-MMA\fP\fIfactor/mode/depth\fP
\fB-MMB\fP\fIyr/mo/da/hr/mn/sc\fP
\fB-MMD\fP\fImode/scale[/min/max]\fP
\fB-MME\fP\fIyr/mo/da/hr/mn/sc\fP
\fB-MML\fP\fIlonflip\fP
\fB-MMN\fP\fInplot\fP \fB-MMP\fP\fIpings \fP
\fB-MMS\fP\fIspeedmin\fP 
\fB-MMT\fP\fItimegap\fP \fB-MMZ\fP\fIalgorithm\fP
\fB-MNA\fP\fI[name_hgt[/P] | P]\fP
\fB-MNP\fP\fI[pingnumber_tick/pingnumber_annot/pingnumber_tick_len]\fP
\fB-MTC\fP\fIfill\fP \fB-MTD\fP\fIresolution\fP 
\fB-MTG\fP\fIfill\fP \fB-MTI\fP\fIriver[/pen]\fP 
\fB-MTN\fP\fIborder[/pen]\fP \fB-MTS\fP\fIfill\fP 
\fB-MTW\fP\fIpen\fP
\fB-MXG\fP\fIfill\fP \fB-MXI\fP\fIxy_file \fP
\fB-MXM\fP
\fB-MXS\fP\fIsymbol/size\fP \fB-MXW\fP\fIpen\fP]

.SH DESCRIPTION
\fBmbm_plot\fP is a macro to generate a shellscript of MB-System and GMT commands 
which, when executed, will generate a Postscript plot of the 
specified swath sonar data. The plot may include bathymetry color 
fill (\fB-G\fP\fI1\fP), bathymetry color shaded relief (\fB-G\fP\fI2\fP), bathymetry 
shaded with amplitudes (\fB-G\fP\fI3\fP), greyshade fill amplitude (\fB-G\fP\fI4\fP), 
greyshade fill sidescan (\fB-G\fP\fI5\fP), contoured bathymetry (\fB-C\fP),
or annotated navigation. The plot may also include navigation tracks, text
labels, xy data in lines or symbols, and coastlines. 
Five different color 
schemes are included. The plot will be scaled to fit on 
the specified page size or, if the scale is user defined, 
the page size will be chosen in accordance with the plot 
size. The primary purpose of this macro is to allow the 
simple, semi-automated production of nice looking maps with 
a few command line arguments. For users seeking more control 
over the plot appearance, a number of additional optional 
arguments are provided. Truly ambitious users may edit the 
plot shellscript to take advantage of MB-System and GMT 
capabilites not supported by this macro.

.SH AUTHORSHIP
David W. Caress (caress@mbari.org)
.br
  Monterey Bay Aquarium Research Institute
.br
Dale N. Chayes (dale@ldeo.columbia.edu)
.br
  Lamont-Doherty Earth Observatory
.br
  Suzanne H. O'Hara (sohara@ldeo.columbia.edu)
.br
  Lamont-Doherty Earth Observatory

.SH SIMPLE DESCRIPTION OF BASIC OPTIONS
.TP
.B \-A
\fImagnitude/azimuth\fP or \fImagnitude/median\fP
.br
Sets the parameters which control how \fBmbswath\fP generates
simulated illumination of bathymetry, which can be either
shaded relief bathymetry or bathymetry draped with amplitude data.
If \fImode\fP is set to 2 (shaded relief bathymetry) using the
\fB-G\fP option, then the value \fImagnitude\fP
is an effective vertical exageration which modulates the intensity of
the shading; typical values are in the 1-5 range.  The value \fIazimuth\fP
is the azimuth from which the bathymetry is illuminated.
If \fImode\fP is set to 3 (bathymetry shaded using amplitudes) using the
\fB-G\fP option, then the value \fImagnitude\fP
modulates the intensity of the shading; the value \fImedian\fP sets the
amplitude value which serves as the zero or neutral level.  
.TP
.B \-C
Given by itself, the \fB-C\fP option produces a contour plot
of the bathymetry data with a contour interval chosen according
to the data in the file or files. If the \fB-G\fP option is used, 
the default contours will be drawn in black; otherwise, the
default contours will be drawn in four colors (black, red, 
green, and blue) with color changes, annotations, and tickmarks
every fourth contour interval. Additional optional parameters are
described in the COMPLETE DESCRIPTION OF OPTIONS section below.
.TP
.B \-D
\fI[flipcolor/flipshade]\fP
.br
This option flips the color and shading conventions used by
\fBmbm_plot\fP.
Normally, the color or grayscale tables used for color bathymetry
maps run from
cool colors (or dark grays) for large depth values 
to hot colors (or light grays) for small depth values.
In contrast, sidescan and beam amplitude data is normally plotted
using light grays (or hot colors) for small amplitudes and
dark grays (or cool colors) for large amplitudes. 
If \fB-D\fP is given alone or with \fIflipcolor\fP = 1, 
it applies to the color table used
for color or gray fill plots,  shaded or unshaded. If the plot
is to be shaded,  either by synthetic illumination (\fB-G\fP\fI2\fP) 
or by overlaying amplitude data (\fB-G\fP\fI3\fP option), then
setting \fIflipshade\fP = 1 will cause the shading convention
to be reversed (e.g. high amplitudes overlaid as light shading).
Using \fB-D\fP\fI0/1\fP will flip the shading convention
but leave the default color convention.
.TP
.B \-F
\fIformat\fP
.br
Sets the data format for the input data. 
If \fIformat\fP < 0, then the input file specified
with the \fB-I\fP option will actually contain a list of input swath sonar
data files. This program uses the \fBMBIO\fP library 
and will read or write any swath sonar
format supported by \fBMBIO\fP. A list of the swath sonar data formats
currently supported by \fBMBIO\fP and their identifier values
is given in the \fBMBIO\fP manual page. Default: \fIformat\fP = -1.
.TP
.B \-G
\fImode[F]\fP
.br
Turns on color fill swath plot and sets the style of the plot.
 	\fImode\fP = 1:	Color fill of bathymetry data.
 	\fImode\fP = 2:	Color shaded relief bathymetry.
 	\fImode\fP = 3:	Bathymetry shaded using amplitude data.
 	\fImode\fP = 4:	Grayscale fill of amplitude data.
 	\fImode\fP = 5:	Grayscale fill of sidescan data.
.br
If "F" is appended to \fImode\fP, then \fBmbm_plot\fP will attempt
to plot amplitude or sidescan data that have been filtered with \fBmbfilter\fP. 
If the desired filtered data files do not exist, then the plotting script
generated by \fBmbm_plot\fP will fail when
\fBmbswath\fP exits with an error message. Filtered amplitude
data are stored in ancilliary files ending with ".ffa", and filtered
sidescan files end in ".ffs". Filtering of bathymetry data is not supported,
and so appending "F" to \fImode\fP values of 1 or 2 will have no effect.
.TP
.B \-H
This "help" flag cause the program to print out a description
of its operation and then exit immediately.
.TP
.B \-I
\fIfilename\fP
.br
Sets the input filename. If \fIformat\fP > 0 (set with the 
\fB-f\fP option) then the swath sonar data contained in \fIinfile\fP 
is read and processed. If \fIformat\fP < 0 (the default), 
then \fIinfile\fP
is assumed to be an ascii file containing a list of the input swath sonar
data files to be processed and their formats.  The program will read 
the data in each one of these files.
In the \fIinfile\fP file, each
data file should be followed by a data format identifier, e.g.:
 	datafile1 11
 	datafile2 24
.br
This program uses the \fBMBIO\fP library and will read or write any swath sonar
format supported by \fBMBIO\fP. A list of the swath sonar data formats
currently supported by \fBMBIO\fP and their identifier values
is given in the \fBMBIO\fP manual page. The default input filename is
"datalist.mb-1".
.TP
.B \-N
Given by itself, this option causes a navigation track plot to be generated.
Additional optional parameters, including annotation control, are
described in the COMPLETE DESCRIPTION OF OPTIONS section below.
.TP
.B \-O
\fIroot\fP
.br
Sets the root used to construct the filename of the output shellscript
(\fIroot\fP.cmd) and names of files created when the shellscript is 
run.  By default, the 
name of the input data file or list file is used as the \fIroot\fP. 
.TP
.B \-P
\fIpagesize\fP
.br
This option sets the size of the page the plot will be centered
on. If the user does not set the plot scale, the plot will be
sized as large as will fit on the designated page. If the user
sets the plot scale such that the plot will not fit on the
designated page, a larger page will be used.
The supported page sizes include ANSI A, B, C, D, E,
F, and E1, as well as most metric page sizes. See the
COMPLETE DESCRIPTION OF OPTIONS section 
below for a complete list of 
the supported page sizes. The default page size is A.
.TP
.B \-S
\fI[color/shade]\fP
.br
This option enables effective histogram equalization of the
color and/or shading of thedata. The equalization is
not achieved by changing the data values, but rather by
constructing the color or shading tables so that
the boundaries in the tables encompass equal fractions of
the datapoints. This serves to focus color or shading contrasts
in value ranges corresponding to the bulk of the data values,
and is particularly useful for
enhancing the contrast of sidescan and beam amplitude plots. 
If \fB-S\fP is given alone or with \fIcolor\fP = 1,
it enables equalization of the color table used
for color or gray fill plots,  shaded or unshaded. If the plot
is to be shaded,  either by synthetic illumination (\fB-G\fP\fI2\fP) 
or by overlaying amplitude data (\fB-G\fP\fI3\fP option), then
setting \fIshade\fP = 1 will cause the shading to be equalized.
Using \fB-S\fP\fI0/1\fP will equalize the shading without
equalizing the color table.
.TP
.B \-T
If \fB-T\fP is given, it causes a coastline to be drawn
on the map. The default is to draw the coastline and shade
all dry land a uniform gray. To exercise greater control of
the coastline plotting, use the 
\fB-MTC\fP, \fB-MTD\fP, \fB-MTG\fP, \fB-MTI\fP, 
\fB-MTN\fP, \fB-MTS\fP, and \fB-MTW\fP options described in the
COMPLETE DESCRIPTION OF OPTIONS section below.
.TP
.B \-U
\fIorientation\fP
.br
Normally the orientation of the plot (portrait or landscape)
is selected automatically so as to maximize the plot scale.
The \fB-U\fP option allows the user to set the plot orientation. If
\fIorientation\fP = 1, a portrait plot will be produced; if
\fIorientation\fP = 2, a landscape plot will be produced.
.TP
.B \-V
Causes \fBmbm_plot\fP to operate in "verbose" mode 
so that it outputs
more information than usual.
.TP
.B \-W
\fI[color_style\fP[\fI/pallette\fP[\fIncolors\fP]] | cptfile]
.br
This option controls the color scheme used for color
fill plots. 

If \fIcolor_style\fP = 1 [default], then
the color scheme used will be a continuous grading
of colors. If \fIcolor_style\fP = 2, the color scheme
will be a set of discrete color intervals. The color
pallette used is set using \fIpallette\fP. Five pallettes
are available:
 	\fIpallette\fP = 1:	Haxby colors [default]
 	\fIpallette\fP = 2:	high Intensity colors
 	\fIpallette\fP = 3:	low Intensity colors
 	\fIpallette\fP = 4:	grayscale
 	\fIpallette\fP = 5:	uniform grayscale
.br
A complete description of the color pallettes is given
in the COMPLETE DESCRIPTION OF OPTIONS section below.
 
The \fIncolors\fP parameter sets the number of color
values used in plotting, whether the colors are 
represented in a continuous color scale or a
stepped, discrete color scale [default is 11].

If the option argument is the path to an existing \fBGMT\fP 
color pallette (CPT) file, then that CPT file and its
color scheme will be used for the plot

.SH COMPLETE DESCRIPTION OF OPTIONS
.TP
.B \-A
\fImagnitude/azimuth\fP or \fImagnitude/median\fP
.br
Sets the parameters which control how \fBmbm_plot\fP generates
simulated illumination of bathymetry, which can be either
shaded relief bathymetry or bathymetry draped with amplitude data.
If \fImode\fP is set to 2 (shaded relief bathymetry) using the
\fB-G\fP option, then the value \fImagnitude\fP
is an effective vertical exageration which modulates the intensity of
the shading; typical values are in the 1-5 range.  The value \fIazimuth\fP
is the azimuth from which the bathymetry is illuminated.
If \fImode\fP is set to 3 (bathymetry shaded using amplitudes) using the
\fB-G\fP option, then the value \fImagnitude\fP
modulates the intensity of the shading; the value \fImedian\fP sets the
amplitude value which serves as the zero or neutral level.  
.TP
.B \-B
\fItickinfo\fP
.br
Sets map boundary tickmark intervals. See the \fBpsbasemap\fP
manual page for details. By default the program chooses
basemap annotations based on the map boundaries.
.TP
.B \-C
\fI[cont_int/col_int/tic_int/lab_int/tic_len/lab_hgt]\fP
.br
Given by itself, the \fB-C\fP option produces a contour plot
of the bathymetry data with a contour interval chosen according
to the data in the file or files. If the \fB-G\fP option is used, 
the default contours will be drawn in black; otherwise, the
default contours will be drawn in four colors (black, red, 
green, and blue) with color changes, annotations, and tickmarks
every fourth contour interval.  If any of the optional
parameters are appended, these values will control the contour interval
and other contour characteristics.
Contours will be
generated at invervals of \fIcont_int\fP meters.  Color changes
will occur at intervals of \fIcol_int\fP meters.  Contours will have
downhill facing tickmarks \fItic_len\fP inches long every \fItic_int\fP
meters. Contours will have annotations 
\fIlab_hgt\fP inches high every \fIlab_int\fP meters.
.TP
.B \-D
\fI[flipcolor/flipshade]\fP
.br
This option flips the color and shading conventions used by
\fBmbm_plot\fP.
Normally, the color or grayscale tables used for color bathymetry
maps run from
cool colors (or dark grays) for large depth values 
to hot colors (or light grays) for small depth values.
In contrast, sidescan and beam amplitude data is normally plotted
using (light grays (or hot colors) for small amplitudes and
dark grays (or cool colors) for large amplitudes. 
If \fB-D\fP is given alone or with \fIflipcolor\fP = 1, 
it applies to the color table used
for color or gray fill plots,  shaded or unshaded. If the plot
is to be shaded,  either by synthetic illumination (\fB-G\fP\fI2\fP) 
or by overlaying amplitude data (\fB-G\fP\fI3\fP option), then
setting \fIflipshade\fP = 1 will cause the shading convention
to be reversed (e.g. high amplitudes overlaid as light shading).
Using \fB-D\fP\fI0/1\fP will flip the shading convention
but leave the default color convention.
.TP
.B \-F
\fIformat\fP
.br
Sets the data format for the input data. 
If \fIformat\fP < 0, then the input file specified
with the \fB-I\fP option will actually contain a list of input swath sonar
data files. This program uses the \fBMBIO\fP library 
and will read or write any swath sonar
format supported by \fBMBIO\fP. A list of the swath sonar data formats
currently supported by \fBMBIO\fP and their identifier values
is given in the \fBMBIO\fP manual page. Default: \fIformat\fP = -1.
.TP
.B \-G
\fImode\fP
.br
Turns on color fill swath plot and sets the style of the plot.
 	\fImode\fP = 1:	Color fill of bathymetry data.
 	\fImode\fP = 2:	Color shaded relief bathymetry.
 	\fImode\fP = 3:	Bathymetry shaded using amplitude data.
 	\fImode\fP = 4:	Grayscale fill of amplitude data.
 	\fImode\fP = 5:	Grayscale fill of sidescan data.
.TP
.B \-H
This "help" flag cause the program to print out a description
of its operation and then exit immediately.
.TP
.B \-I
\fIfilename\fP
.br
Sets the input filename. If \fIformat\fP > 0 (set with the 
\fB-f\fP option) then the swath sonar data contained in \fIinfile\fP 
is read and processed. If \fIformat\fP < 0 (the default), 
then \fIinfile\fP
is assumed to be an ascii file containing a list of the input swath sonar
data files to be processed and their formats.  The program will read 
the data in each one of these files.
In the \fIinfile\fP file, each
data file should be followed by a data format identifier, e.g.:
 	datafile1 11
 	datafile2 24
.br
This program uses the \fBMBIO\fP library and will read or write any swath sonar
format supported by \fBMBIO\fP. A list of the swath sonar data formats
currently supported by \fBMBIO\fP and their identifier values
is given in the \fBMBIO\fP manual page.
.TP
.B \-J
\fIprojection\fP[\fI/scale | /width\fP]
.br
Selects the map projection. By default the map projection is
Mercator and the plot scale is chosen to fit on the selected
page size (see \fB-P\fP option). The user may specify a
different projection to be used, in which case the plot scale
is still automatically chosen to fit the page. The user may
also specify both the projection and the plot scale. If
the projection specifying character is upper case, a plot
width rather than a plot scale is used.
The scale values are specified in inch/degree or in 1:xxxxx
ratios. Plot widths are specified in inches. If the user
specifies a plot scale such that the plot will not fit
on the default A size page, a appropriately larger page
size will be chosen.
.br
.sp
\fBCYLINDRICAL PROJECTIONS:\fP
.br
.sp
\fB\-Jc\fP\fIlon0/lat0/scale\fP (Cassini)
.br
\fB\-Jm\fP\fIscale\fP (Mercator)
.br
\fB\-Joa\fP\fIlon0/lat0/azimuth/scale\fP (Oblique Mercator - point and azimuth)
.br
\fB\-Job\fP\fIlon0/lat0/lon1/lat1/scale\fP (Oblique Mercator - two points)
.br
\fB\-Joc\fP\fIlon0/lat0/lonp/latp/scale\fP (Oblique Mercator - point and pole)
.br
\fB\-Jq\fP\fIlon0/scale\fP (Equidistant Cylindrical Projection (Plate Carree))
.br
\fB\-Jt\fP\fIlon0/scale\fP (TM - Transverse Mercator)
.br
\fB\-Ju\fP\fIzone/scale\fP (UTM - Universal Transverse Mercator)
.br
\fB\-Jy\fP\fIlon0/lats/scale\fP (Basic Cylindrical Projection) 
.br
.sp
\fBAZIMUTHAL PROJECTIONS:\fP
.br
.sp
\fB\-Ja\fP\fIlon0/lat0/scale\fP (Lambert).
.br
\fB\-Je\fP\fIlon0/lat0/scale\fP (Equidistant).
.br
\fB\-Jg\fP\fIlon0/lat0/scale\fP (Orthographic).
.br
\fB\-Js\fP\fIlon0/lat0/scale\fP (General Stereographic)
.br
.sp
\fBCONIC PROJECTIONS:\fP
.br
.sp
\fB\-Jb\fP\fIlon0/lat0/lat1/lat2/scale\fP (Albers)
.br
\fB\-Jl\fP\fIlon0/lat0/lat1/lat2/scale\fP (Lambert)
.br
.sp
\fBMISCELLANEOUS PROJECTIONS:\fP
.br
.sp
\fB\-Jh\fP\fIlon0/scale\fP (Hammer)
.br
\fB\-Ji\fP\fIlon0/scale\fP (Sinusoidal)
.br
\fB\-Jk\fP\fIlon0/scale\fP (Eckert VI)
.br
\fB\-Jn\fP\fIlon0/scale\fP (Robinson)
.br
\fB\-Jr\fP\fIlon0/scale\fP (Winkel Tripel)
.br
\fB\-Jw\fP\fIlon0/scale\fP (Mollweide)
.br
.sp
\fBNON-GEOGRAPHICAL PROJECTIONS:\fP
.br
.sp
\fB\-Jp\fP\fIscale\fP (Linear projection for polar (theta,r) coordinates)
.br
\fB\-Jx\fP\fIx-scale\fP[\fBl|p\fP\fIpow\fP][\fI/y-scale\fP[\fBl|p\fP\fIpow\fP]] (Linear, log, and power scaling)
.br
More details can be found in the \fBpsbasemap\fP manpages.
.TP
.B \-L
\fItitle:scalelabel\fP
.br
Sets the title and the label for the colorscale (if used) of
the plot. Note that a colon (:) rather than a slash (/) is
used to separate the labels. Colons cannot be used in the
labels themselves. If this option is not used, then a default title
and colorscale label are provided. If the title is supplied
alone, a default colorscale label will be provided. To force
no title use \fB-L\fP" "; to force no title or colorscale
label use \fB-L\fP" : ".
.TP
.B \-M
A series of "miscellaneous" options are provided which are
given as \fB-M\fP followed by a two character identifier, followed
by any other parameters associated with that option.
The \fB-M\fP options may be strung together separated by
colons, e.g. "-MGQ100:GU", which is equivalent to
"-MGQ -MGU". 
.TP
.B \-MGD
\fIgmtdef/value\fP
.br
Allows the user to set the \fBGMT\fP default values used as
the plot is constructed. This command may be given repeatedly
to set as many \fBGMT\fP defaults as required. For example, to
set the basemap annotation font to Courier, use 
"-MGDANOT_FONT/Courier".
.TP
.B \-MGF
\fIscale_loc\fP
.br
Sets the location of the color scale. The possible values
of \fIscale_loc\fP are:
 	\fIscale_loc\fP = b:	bottom of plot
 	\fIscale_loc\fP = t:	top of plot
 	\fIscale_loc\fP = l:	left of plot
 	\fIscale_loc\fP = r:	right of plot
.br
[Default \fIscale_loc\fP = b]
.TP
.B \-MGL
[\fIf\fP][\fIx\fP]\fIlon0/lat0/slat/length\fP[\fIm\fP]
.br
Draws a simple map scale centered on \fIlon0/lat0\fP.  Use \fB\-Lx\fP to specify position in inch instead.
Scale is calculated at latitude \fIslat\fP, \fIlength\fP is in km [miles if m is appended].
Use \fB\-Lf\fP to get a "fancy" scale [Default is plain].
.TP
.B \-MGQ
\fIdpi\fP
.br
Sets the resolution in dots per inch of the raster image used
for color fill maps. Larger values of \fIdpi\fP produce larger
Postscript plot files. [Default is 100].
.TP
.B \-MGT
\fIx/y/size/angle/font/just/text\fP
.br
Causes a text label to plotted on the map.
\fIsize\fP is text size in points, \fIangle\fP is 
measured in degrees counter-clockwise from horizontal, 
\fIfontno\fP sets the font type, \fIjustify\fP sets the alignment. 
If \fIfontno\fP starts with a leading hyphen, then 
the remainder of \fIfontno\fP is taken to be a 
textstring with the desired fontname.  See the 
\fBgmtdefaults\fP man page for names and numbers of available fonts 
(or run \fBpstext \-L\fP).  The alignment 
number refers to the part of the textstring that will be mapped 
onto the (\fIx,y\fP) point: 1 = Lower Left corner, 
2 = Lower Center, 3 = Lower Right, 5 = Mid Left, 6 = Mid Center, 
7 = Mid Right, 9 = Upper Left, 10 = Upper Center, 
11 = Upper Right. This option may be given as many times as
needed.
.TP
.B \-MGU
[\fI/dx/dy/\fP][\fIlabel\fP]
.br
Draw Unix System time stamp on plot.  User may specify where the lower left corner
of the stamp should fall on the page relative to lower left corner of plot in inch [Default is (-0.75,-0.75)].  Optionally,
append a label, or \fBc\fP (which will plot the command string.)
.TP
\fB-MMA\fP\fIfactor/mode/depth\fP
This option determines how the along-track dimension of the
beam or pixel footprints is calculated. If \fImode\fP = 1,
then the fore-aft beam angle width of the sonar is used so that
the width increases towards the outer parts of the swath.
The fore-aft beam angle width (\fBMB-System\fP internally stores
a value for each format/sonar) is multiplied by the \fIfactor\fP
value; a \fIfactor\fP < 1.0 can be useful if the data highly
oversamples the seafloor and a \fIfactor\fP > 1.0 can fill in
plots of data which undersample the seafloor. If the data
stream does not include depth values (e.g. one is plotting
pure sidescan data), then the \fIdepth\fP value sets the
depth value in meters used in the footprint calculations.
If \fImode\fP = 2, then the along-track dimension of the beam
or pixel footprints is just the along-track distance between
pings multiplied by the \fIfactor\fP value.
If mode = 3, then each data point is
plotted as a point, and the factor and depth parameters
are ignored. 
Default: \fIfactor\fP = 1.0, \fImode\fP = 1, \fIdepth\fP = 3000.0.
.TP
\fB-MMB\fP\fIyr/mo/da/hr/mn/sc\fP
Sets the starting time for data allowed in the input data; pings
with times before the starting time will be ignored. 
Default: \fIyr/mo/da/hr/mn/sc\fP = 1962/2/21/10/30/0.
.TP
\fB-MMD\fP\fImode/scale[/min/max]\fP
Sets scaling of beam amplitude or sidescan pixel values which
can be applied before plotting. If \fImode\fP = 1 or 2, then
a linear scaling of the form:
 	scaled_value = scale * (value - min) / (max - min)
.br
is applied.  If \fImode\fP = 3 or 4, then a log10 scaling of
the form:
 	scaled_value = scale * (20 * log10(value) - min) / (max - min)
.br
is applied.  If \fImode\fP = 2 or 4, then the value (or 20*log10(value))
will be clipped to \fImin\fP if it is smaller than \fImin\fP or \fImax\fP
if it is greater than \fImax\fP; this clipping happens prior to the
multiplication by \fIscale\fP. Default: \fImode\fP = 1, \fIscale\fP = 1.0,
\fImin\fP = 0.0, \fImax\fP = 1.0.
.TP
\fB-MME\fP\fIyr/mo/da/hr/mn/sc\fP
Sets the ending time for data allowed in the input data; pings
with times after the ending time will be ignored. 
Default: \fIyr/mo/da/hr/mn/sc\fP = 2062/2/21/10/30/0.
.TP
\fB-MML\fP\fIlonflip\fP
If the \fB-R\fP option is not used to explicitly set the plot bounds, then
the \fIlonflip\fP value sets the range of the longitude values used for
calculating the desired bounds.  If  lonflip=-1
then  the  longitude  values will be in the range from -360 to 0
degrees. If lonflip=0 then the longitude values will be  in  the
range  from -180 to 180 degrees. If lonflip=1 then the longitude
values will be in the range from 0  to  360  degrees.   Default:
\fBmbm_plot\fP uses the \fIlonflip\fP value set by \fBmbdefaults\fP.
.TP
\fB-MMN\fP\fInplot\fP
Sets the number of pings to be read in before each contouring
episode. See the description of the \fB-MMZ\fP\fIalgorithm\fP option
for advice on reasonable values
Default: \fInplot\fP = 50 unless \fB-MMZ\fP\fI1\fP is specified,
in which case the default is \fInplot\fP = 5.
.TP
.B \-MMP\
\fIpings \fP
.br
Sets the ping averaging of the input swath sonar data. If \fIpings\fP = 1, then
no ping averaging is performed. If \fIpings\fP > 0, then
that number of input pings will be averaged to produce one output
ping.  If \fIpings\fP = 0, then the ping averaging will automatically
be done so that the along-track ping spacing is equal to the across-track
beam spacing. 
Default: \fIpings\fP = 1 (no ping averaging).
.TP
\fB-MMS\fP\fIspeedmin\fP
Sets the minimum speed in km/hr (5.5 kts ~ 10 km/hr) allowed in 
the input data; pings associated with a smaller ship speed will not be
processed. Default: \fIspeed\fP = 0.
.TP 
.B \-MMT
\fItimegap\fP
.br
Sets the maximum time gap in minutes between adjacent pings allowed before
the data is considered to have a gap. Default: \fItimegap\fP = 1.
.TP
.B \-MMZ
\fIalgorithm\fP
.br
Sets the contouring algorithm to be used. If \fIalgorithm\fP=0,
a simple ping to ping contouring approach is used; this algorithm
is fast but produces poor looking contours when used with data
where beams from one ping may lie "behind" beams from previous
pings (this happens for sonars that ping at nonnull pitch
angles or for the "inside" beams when ships make sharp turns).
If \fIalgorithm\fP=1 then a triangular network is constructed from
the available soundings and this network is in turn contoured;
this algorithm is slow but produces good looking contours in
most cases. It is important to note that the time required for
"triangle" algorithm increases with the square of the number
of beams to be contoured; thus it is sensible to keep the number
of pings contoured at a time small (e.g. use \fB-N\fP\fI5\fP).
The time required for the "ping to ping" algorithm varies linearly
with the number of pings contoured; thus larger numbers of pings
may be reasonably contoured at a time (e.g. use \fB-N\fP\fI50\fP). 
Default: \fIalgorithm\fP = 0 unless \fIformat\fP = 41.
.TP
.B \-MNA
\fI[name_hgt[/P] | P]\fP
.br
Turns on filename annotation of navigation tracks. If \fB-MNA\fP is given
without specifying any controlling parameters, then the lettering height 
\fIname_hgt\fP is 0.15 and the filenames are plotted parallel to the 
navigation track from the start of the track. The lettering height can be
specified using either \fB-MNA\fP\fIname_hgt\fP or \fB-MNA\fP\fIname_hgt/P\fP.
If \fB-MNA\fP\fIP\fP or \fB-MNA\fP\fIname_hgt/P\fP is specified, 
the filename will be plotted perpendicular to the navigation track.
Filename annotation can also be specified using the \fB-N\fP option.
Defaults: Filename annotation off. 
.TP
.B \-MNP
\fI[pingnumber_tick/pingnumber_annot/pingnumber_tick_len]\fP
.br
Turns on ping number (or shot number) annotation of navigation tracks.
Tick marks are made along the shiptrack at \fIpingnumber_tick\fP intervals; these
are \fItime_tick_len\fP inches long. Longer tick marks are made along the 
shiptrack at \fIpingnumber_annot\fP intervals; these are 1.5 times \fItime_tick_len\fP 
inches long.
Defaults: Pingnumber annotation off. If the \fB-MNP\fP option is given without
specifying the controlling parameters, then \fIpingnumber_tick\fP = 50, 
\fIpingnumber_annot\fP = 100, and \fIpingnumber_tick_len\fP = 0.1.
.TP
.B \-MTC
\fIfill\fP 
.br
Coastline plotting option.
Set the shade (0-255), color (r/g/b), or pattern
(p|Pdpi/pattern; see \fB-MTG\fP) for lakes  [Default is the
fill chosen for "wet" areas (-S)].
.TP
.B \-MTD
\fIresolution\fP 
.br
Coastline plotting option.
Selects the resolution of the coastline data set to use ((f)ull,
(h)igh, (i)ntermediate, (l)ow, and (c)rude).  The
resolution drops off by 80% between data sets. [Default
is l].
.TP
.B \-MTG
\fIfill\fP 
.br
Coastline plotting option.
Select painting or clipping of "dry" areas.  Append a
shade, color, pattern, or c for clipping.  Specify the
shade (0-255) or color (r/g/b), or \fB-MTG\fP\fIpdpi/pattern\fP,
where pattern gives the number of the built-in pattern
(1-90) OR the name of a Sun 1-, 8-, or 24-bit raster
file.  dpi sets the resolution of the image.  See \fBGMT\fP
Cookbook & Technical Reference Appendix E for
information on individual patterns.
.TP
.B \-MTI
\fIriver[/pen]\fP 
.br
Coastline plotting option.
Draw rivers.  Specify the type of rivers and
[optionally] append pen attributes  [Default pen:
width = 1, color = 0/0/0, texture = solid].  Choose
from the list of river types below.  Repeat option -I
as often as necessary.
     1 = Permanent major rivers
     2 = Additional major rivers
     3 = Additional rivers
     4 = Minor rivers
     5 = Intermittent rivers - major
     6 = Intermittent rivers - additional
     7 = Intermittent rivers - minor
     8 = Major canals
     9 = Minor canals
     10 = Irrigation canals
     a = All rivers and canals (1-10)
     r = All permanent rivers (1-4)
     i = All intermittent rivers (5-7)
     c = All canals (8-10)
.TP
.B \-MTN
\fIborder[/pen]\fP 
.br
Coastline plotting option.
Draw political boundaries.  Specify the type of
boundary and [optionally] append pen attributes
[Default pen:  width = 1, color = 0/0/0, texture =
solid].  Choose from the list of boundaries below.
Repeat option \fB-MTN\fP as often as necessary.
     1 = National boundaries
     2 = State boundaries within the Americas
     3 = Marine boundaries
     a = All boundaries (1-3)
.TP
.B \-MTS
\fIfill\fP 
.br
Coastline plotting option.
Select painting or clipping of "wet" areas.  Append the
shade (0-255), color (r/g/b), pattern (see \fB-MTG\fP), or c
for clipping.
.TP
.B \-MTW
\fIpen\fP 
.br
Coastline plotting option.
Append pen attributes  [Defaults:  width = 1, color = 0/0/0,
texture = solid].
.TP
.B \-MXG
\fIfill\fP 
.br
Select filling of symbols for xy plotting.  
Set the shade (0\-255) or color 
(r/g/b) [Default is no fill]. To reset no fill,
use \fIfill\fP = "N".
For polygons, you may optionally specify 
\fB\-Gp\fP\fIicon_size/pattern\fP, where 
\fIpattern\fP gives the number of the
image pattern (1-32) OR the name of a 
icon-format file.  \fIicon_size\fP sets 
the unit size in inch.
To invert black and white pixels, use 
\fB\-GP\fP instead of \fB\-Gp\fP.  See 
\fBGMTs\fP Cookbook & Technical Reference
Appendix E for information on individual patterns.
.TP
.B \-MXI
\fIxy_file \fP
.br
Specifies a file containing (x,y) pairs to be plotted
as lines or symbols. The line and symbol characteristics
are set using the last \fB-MXG\fP, \fB-MXS\fP, and \fB-MXW\fP
options used. All of the \fB-MX\fP commands can be
given multiple times, so by stringing series of these
commands together the user can plot different files
using different line or symbol characteristics.
[Default is a solid black line].
.TP
.B \-MXM
.br
Toggles expectation for xy data files having multiple
segments, in which each segment is to be plotted 
separately. Segments are separated by a
record whose first character is '>'. By default, 
unsegmented files are expected. Users may give this
command multiple times, allowing some input files to
be handled as segmented and others not.
.TP
.B \-MXS
\fIsymbol/size\fP 
.br
Selects symbol to be used for plotting the next xy data
file. Setting \fIsymbol\fP = "N" causes line plotting.
Choose between:
.TP
.B \-MXSa
st\fBa\fPr.  \fIsize\fP is radius of circumscribing circle.
.TP
.B \-MXSb
\fBb\fPar extending from \fIbase\fP to y.  \fIsize\fP is bar width.  By default,
\fIbase\fP = 0.  Append /\fIbase\fP to change this value.  Append \fBu\fP if \fIsize\fP
is in x-units [Default is inch].
.TP
.B \-MXSc
\fBc\fPircle.  \fIsize\fP is diameter of circle.
.TP
.B \-MXSd
\fBd\fPiamond.  \fIsize\fP is side of diamond.
.TP
.B \-MXSe
\fBe\fPllipse.  Direction (in degrees counterclockwise from horizontal), major_axis (in inch), and minor_axis (in inch) must be found in columns 3, 4, and 5.
.TP
.B \-MXSf
\fBf\fPault.  Give distance gap between ticks and ticklength in inch.  If gap is
negative, it is interpreted to mean number of ticks instead.  Append \fBl\fP or \fBr\fP to draw tick on
the left or right side of line [Default is centered].  Upper case \fBL\fP or \fBR\fP draws a triangle
instead of line segment.
.TP
.B \-MXSh
\fBh\fPexagon.  Give side in inch.
.TP
.B \-MXSi
\fBi\fPnverted triangle.  Give side in inch.
.TP
.B \-MXSl
\fBl\fPetter or text string.  Give size in inch, and append /\fIstring\fP after the size.  Note that the size is only approximate; no individual scaling
is done for different characters.  Remember to escape special characters like *.
.TP
.B \-MXSp
\fBp\fPoint.  No size needs to be specified (1 pixel is used).
.TP
.B \-MXSs
\fBs\fPquare.  Give side in inch.
.TP
.B \-MXSt
\fBt\fPriangle.  Give side in inch.
.TP
.B \-MXSv
\fBv\fPector.  Direction (in degrees counterclockwise from horizontal) and length (in inch) must be found in columns 3 and 4.  \fIsize\fP,
if present, will be interpreted as arrowwidth/headlength/headwidth (in inch) [Default is 0.03/0.12/0.1 inch].
By default arrow attributes remains invariant to the length
of the arrow.  To have the size of the vector scale down with decreasing size,
append n\fPnorm\fP, where vectors shorter than \fInorm\fP will have their
attributes scaled by length/\fInorm\fP.
.TP
.B \-MXSV
Same as \fB\-MXSv\fP, except azimuth (in degrees east of north) should be given instead of direction.  The azimuth will
be mapped into an angle based on the chosen map projection (\fB\-MXSv\fP leaves the directions
unchanged.)
.TP
.B \-MXSx
cross.  Give length in inch.
.TP
.B \-MXW
\fIpen\fP
.br
Set pen attributes for xy plotting. See chapter 4.12 in the
GMT Technical reference for a discussion of GMT pen values.  
[Defaults: width = 1, color = 0/0/0, 
texture = solid]. 
.TP
.B \-N
\fI[time_tick/time_annot/date_annot/time_tick_len[/name_hgt/name_perp]] | F | FP]\fP
.br
This option causes a navigation track plot to be generated, and 
can also set the start of each swath file to be annotated with the 
filename. If the \fB-N\fP option is given alone, then the 
navigation track will be plotted without any annotation,  The optional 
parameters allow users to control the details of the navigation 
track annotation. Time marks are made with "X" marks along the 
shiptrack; annotated time marks show the time in HH:MM format 
next to the time mark and annotated date marks show the time 
and julian day in HH:MM/DDD format.  The "X" marks are
\fItime_tick_len\fP inches high for normal time marks and 
1.5 times \fItime_tick_len\fP inches high for annotated time or date
marks.  The interval of time ticks, annotated time ticks, and 
annotated date ticks are given in hours by \fItime_tick\fP, 
\fItime_annot\fP, and \fIdate_annot\fP, respectively.
If the \fIname_hgt\fP parameter is not given when the other parameters
are specified, then no filename annotation will be done. If given,
\fIname_hgt\fP sets the height in inches of the filename annotation
and turns that annotation on. If given as 1, \fIname_perp\fP causes 
the filename annotation to be perpendicular to the shiptrack rather 
than parallel (the default). If the \fB-N\fP\fIF\fP is given, then 
a navigation track will be generated using the default parameters 
and also with filename annotation along the shiptrack. If the 
\fB-N\fP\fIFP\fP is given, then a navigation track will be generated 
with the default parameters and also with filename annotation 
perpendicular to the shiptrack.
Defaults if annotation is enabled: \fItime_tick\fP = 0.25; 
\fItime_annot\fP = 1.0; \fIdate_annot\fP = 4.0; 
\fItime_tick_len\fP = 0.1; \fIname_hgt\fP = 0.1; \fIname_perp\fP = 0.
.TP
.B \-O
\fIroot\fP
.br
Sets the root used to construct the filename of the output shellscript
(\fIroot\fP.cmd) and names of files created when the shellscript is 
run.  By default, the 
name of the input data file or list file is used as the \fIroot\fP. 
.TP
.B \-P
\fIpagesize\fP
.br
This option sets the size of the page the plot will be centered
on. If the user does not set the plot scale, the plot will be
sized as large as will fit on the designated page. If the user
sets the plot scale such that the plot will not fit on the
designated page, a larger page will be used.
The supported page sizes are:

          American ANSI sizes:
          A     8.5 x 11.0 in.    ( 215.9 x  279.4 mm)
          B    11.0 x 17.0 in.    ( 279.4 x  431.8 mm)
          C    17.0 x 22.0 in.    ( 431.8 x  558.8 mm)
          D    22.0 x 34.0 in.    ( 558.8 x  863.6 mm)
          E    34.0 x 44.0 in.    ( 863.6 x 1117.6 mm)
          F    28.0 x 40.0 in.    ( 711.2 x 1016.0 mm)
          E1   44.0 x 68.0 in.    (1117.6 x 1727.2 mm)

          Metric ISO A sizes:
          A0   841.0 x 1189.0 mm  (33.11 x 46.81 in.)
          A1   594.0 x  841.0 mm  (23.39 x 33.11 in.)
          A2   420.0 x  594.0 mm  (16.54 x 23.39 in.)
          A3   297.0 x  420.0 mm  (11.69 x 16.54 in.)
          A4   210.0 x  297.0 mm  ( 8.27 x 11.69 in.)
          A5   148.0 x  210.0 mm  ( 5.83 x  8.27 in.)
          A6   105.0 x  148.0 mm  ( 4.13 x  5.83 in.)
          A7    74.0 x  105.0 mm  ( 2.91 x  4.13 in.)
          A8    52.0 x   74.0 mm  ( 2.05 x  2.91 in.)
          A9    37.0 x   52.0 mm  ( 1.46 x  2.05 in.)
          A10   26.0 x   37.0 mm  ( 1.02 x  1.46 in.)

          Metric ISO B sizes:
          B0   1000.0x 1414.0 mm  (39.37 x 55.67 in.)
          B1   707.0 x 1000.0 mm  (27.83 x 39.37 in.)
          B2   500.0 x  707.0 mm  (19.68 x 27.83 in.)
          B3   353.0 x  500.0 mm  (13.90 x 19.68 in.)
          B4   250.0 x  353.0 mm  ( 9.84 x 13.90 in.)
          B5   176.0 x  250.0 mm  ( 6.93 x  9.84 in.)
          B6   125.0 x  176.0 mm  ( 4.92 x  6.93 in.)
          B7    88.0 x  125.0 mm  ( 3.46 x  4.92 in.)
          B8    62.0 x   88.0 mm  ( 2.44 x  3.46 in.)
          B9    44.0 x   62.0 mm  ( 1.73 x  2.44 in.)
          B10   31.0 x   44.0 mm  ( 1.22 x  1.73 in.)

          Metric ISO C sizes:
          C0   914.4 x 1300.5 mm  (36.00 x 51.20 in.)
          C1   650.2 x  914.4 mm  (25.60 x 36.00 in.)
          C2   457.2 x  650.2 mm  (18.00 x 25.60 in.)
          C3   325.1 x  457.2 mm  (12.80 x 18.00 in.)
          C4   228.6 x  325.1 mm  ( 9.00 x 12.80 in.)
          C5   162.6 x  228.6 mm  ( 6.40 x  9.00 in.)
          C6   114.3 x  162.6 mm  ( 4.50 x  6.40 in.)
          C7    81.3 x  114.3 mm  ( 3.20 x  4.50 in.)

	  MB-System large format sizes:
          m1  1371.6 x 1828.8 mm  (54.00 x 72.00 in.)
          m2  1371.6 x 2133.6 mm  (54.00 x 84.00 in.)
          m3  1371.6 x 2438.4 mm  (54.00 x 96.00 in.)
          m4  1524.0 x 1828.8 mm  (54.00 x 72.00 in.)
          m5  1524.0 x 2133.6 mm  (54.00 x 84.00 in.)
          m6  1524.0 x 2438.4 mm  (54.00 x 96.00 in.)

The default page size is A.
.TP
.B \-Q
Normally, the output plot generation shellscript 
includes lines which execute
a program to display the Postscript image on the screen.  
This option causes those lines to be commented out so
that executing the shellscript produces a Postscript plot
but does not attempt to display it on the screen.
The program
to be used to display the Postscript is set 
using \fBmbdefaults\fP;
the default value can be overridden by setting the environment
variable $MB_PS_VIEWER. 
.TP
.B \-R
\fIwest/east/south/north\fP
.br
Sets the longitude and latitude bounds within which swath sonar 
data will be read. Normally the bounds are automatically chosen
to include all of the input data. 
.TP
.B \-S
\fI[color/shade]\fP
.br
This option enables effective histogram equalization of the
color and/or shading of thedata. The equalization is
not achieved by changing the data values, but rather by
constructing the color or shading tables so that
the boundaries in the tables encompass equal fractions of
the datapoints. This serves to focus color or shading contrasts
in value ranges corresponding to the bulk of the data values,
and is particularly useful for
enhancing the contrast of sidescan and beam amplitude plots. 
If \fB-S\fP is given alone or with \fIcolor\fP = 1,
it enables equalization of the color table used
for color or gray fill plots,  shaded or unshaded. If the plot
is to be shaded,  either by synthetic illumination (\fB-G\fP\fI2\fP) 
or by overlaying amplitude data (\fB-G\fP\fI3\fP option), then
setting \fIshade\fP = 1 will cause the shading to be equalized.
Using \fB-S\fP\fI0/1\fP will equalize the shading without
equalizing the color table.
.TP
.B \-T
If \fB-T\fP is given, it causes a coastline to be drawn
on the map. The default is to draw the coastline and shade
all dry land a uniform gray. To exercise greater control of
the coastline plotting, use the 
\fB-MTC\fP, \fB-MTD\fP, \fB-MTG\fP, \fB-MTI\fP, 
\fB-MTN\fP, \fB-MTS\fP, and \fB-MTW\fP options described in the
.TP
.B \-U
\fIorientation\fP
.br
Normally the orientation of the plot (portrait or landscape)
is selected automatically so as to maximize the plot scale.
The \fB-U\fP option allows the user to set the plot orientation. If
\fIorientation\fP = 1, a portrait plot will be produced; if
\fIorientation\fP = 2, a landscape plot will be produced.
.TP
.B \-V
Causes \fBmbm_plot\fP to operate in "verbose" mode so that it 
outputs more information than usual.
.TP
.B \-W
\fI[color_style\fP[\fI/pallette\fP[\fIncolors\fP]] | cptfile]
.br
This option controls the color scheme used for color
fill plots. 

If \fIcolor_style\fP = 1 [default], then
the color scheme used will be a continuous grading
of colors. If \fIcolor_style\fP = 2, the color scheme
will be a set of discrete color intervals. The color
pallette used is set using \fIpallette\fP. Seven pallettes
are available:
 	\fIpallette\fP = 1:	Haxby colors [default]
 	\fIpallette\fP = 2:	high Intensity colors
 	\fIpallette\fP = 3:	low Intensity colors
 	\fIpallette\fP = 4:	grayscale
 	\fIpallette\fP = 5:	uniform grayscale
 	\fIpallette\fP = 6:	uniform black
 	\fIpallette\fP = 7:	uniform white

The RGB definitions of the color pallettes are:

color pallette 1 - Haxby Color Table
  red:   255 255 255 255 240 205 138 106  50  40  37
  green: 255 186 161 189 236 255 236 235 190 127  57
  blue:  255 133  68  87 121 162 174 255 255 251 175

color pallette 2 - High Intensity Colors
  red:   255 255 255 255 128   0   0   0   0 128 255
  green:   0  64 128 255 255 255 255 128   0   0   0
  blue:    0   0   0   0   0   0 255 255 255 255 255

color pallette 3 - Low Intensity Colors
  red:   200 194 179 141  90   0   0   0   0  90 141
  green:   0  49  90 141 179 200 141  90   0   0   0
  blue:    0   0   0   0   0   0 141 179 200 179 141

color pallette 4 - Grayscale
  red:   255 230 204 179 153 128 102  77  51  26   0
  green: 255 230 204 179 153 128 102  77  51  26   0
  blue:  255 230 204 179 153 128 102  77  51  26   0

color pallette 5 - Uniform Grayscale
  red:   128 128 128 128 128 128 128 128 128 128 128
  green: 128 128 128 128 128 128 128 128 128 128 128
  blue:  128 128 128 128 128 128 128 128 128 128 128

color pallette 6 - Uniform Black
  red:     0   0   0   0   0   0   0   0   0   0   0
  green:   0   0   0   0   0   0   0   0   0   0   0
  blue:    0   0   0   0   0   0   0   0   0   0   0

color pallette 7 - Uniform White
  red:   255 255 255 255 255 255 255 255 255 255 255
  green: 255 255 255 255 255 255 255 255 255 255 255
  blue:  255 255 255 255 255 255 255 255 255 255 255
 
The Haxby colors have been adapted from a pallette
developed by Dr. William Haxby of the Lamont-Doherty
Earth Observatory; this pallette is pleasing to the
eye and well suited for shading. The high intensity
colors describe linear paths through RGB space from
red to blue to green to purple; because the colors are high
intensity they are not well suited to shading.
The low intensity colors are similar to the high
intensity, but muted and thus well suited to shading.
The grayscale pallette runs linearly from white to
black and is commonly used for plots of sidescan and amplitude
data. The uniform grayscale is useful for non-color
shaded relief plots.
 
The \fIncolors\fP parameter sets the number of color
values used in plotting, whether the colors are 
represented in a continuous color scale or a
stepped, discrete color scale [default is 11].

If the option argument is the path to an existing \fBGMT\fP 
color pallette (CPT) file, then that CPT file and its
color scheme will be used for the plot
.TP
.B \-X
Normally, \fBmbm_plot\fP creates an executable shellscript and
then exits.  This option will cause the shellscript to be executed
in the background before \fBmbm_plot\fP exits.
.TP
.B \-Y
Normally, \fBmbm_plot\fP generates nicely rounded numbers
for the boundaries of the color pallette. Often, the resulting
color bounds extend well outside the range of the gridded data.
This option causes
the color boundaries to be uniformly distributed between the
minimum and maximum values of the grid.
.TP
.B \-Z
\fImin/max\fP
.br
This option overrides the minimum and maximum values of
bathymetry data, affecting the color pallette and the
contour interval if those parameters are not specified
by the user.

.SH EXAMPLES
Suppose we have obtained a swath sonar data file called
sb2112_example.mb41 collected using a SeaBeam 2112 sonar.
This file contains bathymetry, beam amplitude, and
sidescan data. In order to obtain initial views of the
data in the file, we use \fBmbm_plot\fP to generate
shellscripts which in turn generate plots when executed.
The following five commands generate plotting shellscripts
for color fill bathymetry overlaid with contours, color shaded
relief bathymetry, color fill bathymetry overlaid with 
amplitudes, grayscale amplitudes, and grayscale sidescan,
respectively:

 	mbm_plot -F41 -I sb2112_example.mb41 -G1 -C    \\
 		-N -V -Obathcont
 	mbm_plot -F41 -I sb2112_example.mb41 -G2       \\
 		-N -V -Obathshade
 	mbm_plot -F41 -I sb2112_example.mb41 -G3 -S0/1 \\
 		-N -V -Obathamp
 	mbm_plot -F41 -I sb2112_example.mb41 -G4 -S    \\
 		-N -V -Oamp
 	mbm_plot -F41 -I sb2112_example.mb41 -G5 -S    \\
 		-N -V -Oss
 
When the following shellscripts are executed, each will 
generate a postscript plot file and then display the plot
on the screen:
 
 	bathcont.cmd
 	bathshade.cmd
 	bathamp.cmd
 	amp.cmd
 	ss.cmd
 
Note that we use the \fB-S\fP option to apply histogram 
equalization to the amplitude and sidescan data, but not
the bathymetry data. Also note that by specifying \fB-N\fP
we obtain a track plot of the ship's navigation overlaid
on the color or grayscale file plots.
 
Now suppose we have a set of SeaBeam 2112 data files
comprising a short survey and that we want a plot
of all the data together.  We create an ASCII text file which has
a list of the filenames, each followed by the appropriate \fBMBIO\fP 
format id number, e.g.:

 	sb2112_example_1.mb41 41
 	sb2112_example_2.mb41 41
 	sb2112_example_3.mb41 41

If the name of the data file list is "datalist", then
using "\fB-F\fP\fI-1\fP \fB-I\fP\fIdatalist\fP" will
cause the macro to operate on all of the files
together.  We desire a plot including color fill bathymetry
overlaid with 25 meter contours and the ship's navigation.
For this plot, we want a very bright colortable and we would like
the colors to be discretely stepped rather than continous;
thus we use \fB-W\fP\fI2/2\fP. We also choose to use the
\fB-X\fP option, which causes \fBmbm_plot\fP to execute
the shellscript it creates in the background before
exiting. The \fBmbm_plot\fP command is:
 
 	mbm_plot -F-1 -Idatalist -G1 -C25 -N \\
 			-X -V -Obathtest
 
As an example, the contents of the plotting shellscript 
"bathtest.cmd" are:
 
 #
 # Shellscript to create Postscript plot of swath sonar data
 # Created by macro mbm_plot
 #
 # This shellscript created by following command line:
 # mbm_plot -F-1 -Idatalist -G1 -C25 -N -V -Obathtest
 #
 # Save existing GMT defaults
 echo Saving GMT defaults...
 gmtdefaults -L > gmtdefaults$$
 #
 # Set new GMT defaults
 echo Setting new GMT defaults...
 gmtset ANOT_FONT Helvetica
 gmtset LABEL_FONT Helvetica
 gmtset HEADER_FONT Helvetica
 gmtset ANOT_FONT_SIZE 8
 gmtset LABEL_FONT_SIZE 8
 gmtset HEADER_FONT_SIZE 10
 gmtset FRAME_WIDTH 0.074999999999999997
 gmtset TICK_LENGTH 0.074999999999999997
 gmtset PAGE_ORIENTATION LANDSCAPE
 gmtset COLOR_BACKGROUND 0/0/0
 gmtset COLOR_FOREGROUND 255/255/255
 gmtset COLOR_NAN 255/255/255
 #
 # Make color pallette table file
 echo Making color pallette table file...
 echo   2975 255 255 255   3150 255 186 133 > bathtest.cpt
 echo   3150 255 186 133   3325 255 161  68 >> bathtest.cpt
 echo   3325 255 161  68   3500 255 189  87 >> bathtest.cpt
 echo   3500 255 189  87   3675 240 236 121 >> bathtest.cpt
 echo   3675 240 236 121   3850 205 255 162 >> bathtest.cpt
 echo   3850 205 255 162   4025 138 236 174 >> bathtest.cpt
 echo   4025 138 236 174   4200 106 235 255 >> bathtest.cpt
 echo   4200 106 235 255   4375  50 190 255 >> bathtest.cpt
 echo   4375  50 190 255   4550  40 127 251 >> bathtest.cpt
 echo   4550  40 127 251   4725  37  57 175 >> bathtest.cpt
 #
 # Run mbswath
 echo Running mbswath...
 mbswath -f-1 -Idatalist \\
 	-Jm22.198543775528325 \\
 	-R114.210795/114.430905/-31.91322/-31.62458 \\
 	-Cbathtest.cpt \\
 	-p1 -A1 -Z1 \\
 	-p1 \\
 	-P -X1.8069392647842304 -Y2 -K -V > bathtest.ps
 #
 # Run mbcontour
 echo Running mbcontour...
 mbcontour -f-1 -Idatalist \\
 	-Jm22.198543775528325 \\
 	-R114.210795/114.430905/-31.91322/-31.62458 \\
 	-A50/100000/100000/100000/0.01/0.1 \\
 	-D0.25/1/4/0.15 \\
  	-p1 \\
 	-P -K -O -V >> bathtest.ps
 #
 # Make color scale
 echo Running psscale...
 psscale -Cbathtest.cpt \\
 	-D2.4431/-0.5000/4.8861/0.1500h \\
 	-B":.Depth (meters):" \\
 	-P -K -O -V >> bathtest.ps
 #
 # Make basemap
 echo Running psbasemap...
 psbasemap -Jm22.198543775528325 \\
 	-R114.210795/114.430905/-31.91322/-31.62458 \\
 	-B5m/5m:."Data List File datalist": \\
 	-P -O -V >> bathtest.ps
 #
 # Delete surplus files
 echo Deleting surplus files...
 rm -f bathtest.cpt
 #
 # Reset GMT default fonts
 echo Resetting GMT fonts...
 mv gmtdefaults$$ .gmtdefaults
 #
 # Run xpsview
 echo Running xpsview in background...
 xpsview -ps a -maxp 4m bathtest.ps &
 #
 # All done!
 echo All done!

.SH SEE ALSO
\fBmbsystem\fP(l), \fBmbcontour\fP(l), 
\fBmbswath\fP(l), \fBmbdefaults\fP(l), 
\fBmbm_grdplot\fP(l), \fBmbm_grd3dplot\fP(l), \fBmbfilter\fP(l)

.SH BUGS
By making this macro more useful, we have also made it
more complex. 


