
/* Begin user code block <abstract> */
/* End user code block <abstract> */

/**
 * README: Portions of this file are merged at file generation
 * time. Edits can be made *only* in between specified code blocks, look
 * for keywords <Begin user code> and <End user code>.
 */
/*
 * Generated by the ICS Builder Xcessory (BX).
 *
 * BuilderXcessory Version 6.1.3
 * Code Generator Xcessory 6.1.3 (08/19/04) CGX Scripts 6.1 Motif 2.1 
 *
 */
#ifndef MB3DRouteList_H
#define MB3DRouteList_H

/**
 * Forward declare the class data pointer type so that it can
 * easily be used as a parameter to class functions and data members.
 */
typedef struct _MB3DRouteListData *MB3DRouteListDataPtr;

/**
 * Globally included information.
 */


/**
 * Class specific includes.
 */


typedef struct _MB3DRouteListData
{
    /*
     * Classes created by this class.
     */
    
    /*
     * Widgets created by this class.
     */
    Widget MB3DRouteList;
    Widget mbview_routelist_label;
    Widget mbview_pushButton_routelist_delete;
    Widget mbview_pushButton_routelist_dismiss;
    Widget mbview_scrolledWindow_routelist;
    Widget mbview_list_routelist;
    
    /**
     * All methods and data..
     */
} MB3DRouteListData;

/*
 * Function: MB3DRouteListCreate()
 *		The creation for class MB3DRouteList.
 */
MB3DRouteListDataPtr MB3DRouteListCreate(MB3DRouteListDataPtr, Widget, String, ArgList, Cardinal);

/**
 * Set routines for exposed resources.
 */
#endif
