<!-- WEBMAGIC VERSION NUMBER="2.0.2" -->
<!-- WEBMAGIC TRANSLATION NAME="ServerRoot" SRC="/var/www/htdocs/" DST="/" -->
<!-- WEBMAGIC TRANSLATION NAME="ProjectRoot" SRC="./" DST="" -->
</HEAD>
<BODY TEXT="#000000" BGCOLOR="#FFFFFF" LINK="#336699" VLINK="#997040" ALINK="#CC9900">
<BODY>
<CENTER><H3><U>MB-System Unix Manual Page</U></H3></CENTER>
<PRE>
