
/* Begin user code block <abstract> */
/* End user code block <abstract> */

/**
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 *
 * Created by BuilderXcessory Version 6.1.3
 * Generated by Code Generator Xcessory 6.1.3 (08/19/04) CGX Scripts 6.1 Motif 2.1 
 *
 */
#ifndef mbnavadjust_creation_H
#define mbnavadjust_creation_H
#define MBNA_FILESELECTION_NONE 0
#define MBNA_FILESELECTION_NEW 1
#define MBNA_FILESELECTION_OPEN 2
#define MBNA_FILESELECTION_IMPORT 3

/*
 * Global widget declarations.
 *        - EXTERNAL is set to extern if the
 *          defs file is not included from the
 *          main file.
 */
#ifdef DECLARE_BX_GLOBALS
#define EXTERNAL
#else
#define EXTERNAL extern
#endif

/**
 * Start Global Widget Declarations.
 */
EXTERNAL Widget   bulletinBoard_modelplot;
EXTERNAL Widget   radioBox;
EXTERNAL Widget   toggleButton_modelplot_sequential;
EXTERNAL Widget   toggleButton_modelplot_block;
EXTERNAL Widget   drawingArea_modelplot;
EXTERNAL Widget   scale_controls_zoffset;
EXTERNAL Widget   scale_controls_smoothing;
EXTERNAL Widget   scale_controls_sectionlength;
EXTERNAL Widget   scale_controls_tickinterval;
EXTERNAL Widget   scale_controls_colorinterval;
EXTERNAL Widget   scale_controls_contourinterval;
EXTERNAL Widget   scale_controls_decimation;
EXTERNAL Widget   scale_controls_sectionsoundings;
EXTERNAL Widget   label_about_version;
EXTERNAL Widget   pushButton_biases_applyall;
EXTERNAL Widget   scale_biases_heading2;
EXTERNAL Widget   scale_biases_roll2;
EXTERNAL Widget   scale_biases_roll1;
EXTERNAL Widget   scale_biases_heading1;
EXTERNAL Widget   label_biases_files;
EXTERNAL Widget   toggleButton_biases_together;
EXTERNAL Widget   toggleButton_biases_separate;
EXTERNAL Widget   bulletinBoard_naverr;
EXTERNAL Widget   pushButton_naverr_unset;
EXTERNAL Widget   pushButton_naverr_minxymisfit;
EXTERNAL Widget   drawingArea_naverr_zcorr;
EXTERNAL Widget   pushButton_naverr_zerozoffset;
EXTERNAL Widget   pushButton_naverr_settie;
EXTERNAL Widget   toggleButton_misfitcenter_zero;
EXTERNAL Widget   toggleButton_misfitcenter_auto;
EXTERNAL Widget   pushButton_naverr_resettie;
EXTERNAL Widget   pushButton_naverr_addtie;
EXTERNAL Widget   pushButton_naverr_deletetie;
EXTERNAL Widget   pushButton_naverr_fullsize;
EXTERNAL Widget   pushButton_naverr_zerooffset;
EXTERNAL Widget   label_naverr_offsets;
EXTERNAL Widget   pushButton_naverr_nextunset;
EXTERNAL Widget   label_naverr_status;
EXTERNAL Widget   drawingArea_naverr_cont;
EXTERNAL Widget   drawingArea_naverr_corr;
EXTERNAL Widget   pushButton_naverr_dismiss;
EXTERNAL Widget   pushButton_naverr_selecttie;
EXTERNAL Widget   pushButton_naverr_minimum;
EXTERNAL Widget   pushButton_naverr_next;
EXTERNAL Widget   pushButton_naverr_previous;
EXTERNAL Widget   pushButton_naverr_setnone;
EXTERNAL Widget   xmDialogShell_fileselection;
EXTERNAL Widget   bulletinBoard_fileselection;
EXTERNAL Widget   textField_format;
EXTERNAL Widget   label_format;
EXTERNAL Widget   fileSelectionBox;
EXTERNAL Widget   bulletinBoard_error;
EXTERNAL Widget   label_error_two;
EXTERNAL Widget   label_error_one;
EXTERNAL Widget   label_error_three;
EXTERNAL Widget   bulletinBoard_message;
EXTERNAL Widget   label_message;
EXTERNAL Widget   pushButton_new;
EXTERNAL Widget   pushButton_open;
EXTERNAL Widget   pushButton_close;
EXTERNAL Widget   pushButton_importdata;
EXTERNAL Widget   pushButton_quit;
EXTERNAL Widget   pushButton_showsurveys;
EXTERNAL Widget   pushButton_showdata;
EXTERNAL Widget   pushButton_showsections;
EXTERNAL Widget   pushButton_showcrossings;
EXTERNAL Widget   pushButton_showgoodcrossings;
EXTERNAL Widget   pushButton_showbettercrossings;
EXTERNAL Widget   pushButton_showtruecrossings;
EXTERNAL Widget   pushButton_showties;
EXTERNAL Widget   toggleButton_showallsurveys;
EXTERNAL Widget   toggleButton_showselectedsurvey;
EXTERNAL Widget   toggleButton_showselectedfile;
EXTERNAL Widget   toggleButton_showselectedsection;
EXTERNAL Widget   pushButton_makegrid;
EXTERNAL Widget   pushButton_showmodelplot;
EXTERNAL Widget   pushButton_poornav;
EXTERNAL Widget   pushButton_goodnav;
EXTERNAL Widget   pushButton_fixednav;
EXTERNAL Widget   pushButton_autopick;
EXTERNAL Widget   pushButton_newcrossings;
EXTERNAL Widget   pushButton_analyzecrossings;
EXTERNAL Widget   pushButton_zerozoffsets;
EXTERNAL Widget   pushButton_invertnav;
EXTERNAL Widget   pushButton_applynav;
EXTERNAL Widget   form_mbnavadjust;
EXTERNAL Widget   scrolledWindow_messages;
EXTERNAL Widget   text_messages;
EXTERNAL Widget   label_status;
EXTERNAL Widget   label_listdata;
EXTERNAL Widget   scrolledWindow_datalist;
EXTERNAL Widget   list_data;
/**
 * End Global Widget Declarations.
 */
#endif
