#!/bin/csh
$CMPGCTP/testproj < parm14 > testfile
$CMPGCTP/testproj < parm14a >> testfile
$CMPGCTP/testproj < parm14b >> testfile
$CMPGCTP/testproj < parm14c >> testfile
$CMPGCTP/testproj < parm14d >> testfile
