#! /bin/sh
# $Id: packup,v 3.0 1993-05-14 23:05:58 sohara Exp $
# $Log: not supported by cvs2svn $

PDIR=/home/hs/tmp/packup
mkdir $PDIR


for f in `cat doem`
do
	echo converting $f
	unix2dos $f $PDIR/$f
done

cd $PDIR
cd ..
tar cvf pack.tar packup
