
/* Begin user code block <abstract> */
/* End user code block <abstract> */

/**
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 *
 * Created by BuilderXcessory Version 6.1.3
 * Generated by Code Generator Xcessory 6.1.3 (08/19/04) CGX Scripts 6.1 Motif 2.1 
 *
 */
#ifndef mbnavedit_creation_H
#define mbnavedit_creation_H

/*
 * Global widget declarations.
 *        - EXTERNAL is set to extern if the
 *          defs file is not included from the
 *          main file.
 */
#ifdef DECLARE_BX_GLOBALS
#define EXTERNAL
#else
#define EXTERNAL extern
#endif

/**
 * Start Global Widget Declarations.
 */
EXTERNAL Widget   bulletinBoard_deletebadtimetag;
EXTERNAL Widget   bulletinBoard_timeinterpolation;
EXTERNAL Widget   bulletinBoard_useprevious;
EXTERNAL Widget   textField_modeling_acceleration;
EXTERNAL Widget   textField_modeling_speed;
EXTERNAL Widget   scale_driftlat;
EXTERNAL Widget   scale_driftlon;
EXTERNAL Widget   toggleButton_modeling_off;
EXTERNAL Widget   toggleButton_modeling_dr;
EXTERNAL Widget   toggleButton_modeling_inversion;
EXTERNAL Widget   label_timestep_2;
EXTERNAL Widget   scale_timestep;
EXTERNAL Widget   label_timestep_1;
EXTERNAL Widget   label_timespan_2;
EXTERNAL Widget   scale_timespan;
EXTERNAL Widget   label_timespan_1;
EXTERNAL Widget   xmDialogShell_fileselection;
EXTERNAL Widget   bulletinBoard_fileselection;
EXTERNAL Widget   textField_output_file;
EXTERNAL Widget   label_filename;
EXTERNAL Widget   label_output_mode;
EXTERNAL Widget   radioBox_output;
EXTERNAL Widget   toggleButton_output_on;
EXTERNAL Widget   toggleButton_output_off;
EXTERNAL Widget   textField_format;
EXTERNAL Widget   label_format;
EXTERNAL Widget   fileSelectionBox;
EXTERNAL Widget   bulletinBoard_error;
EXTERNAL Widget   label_error_two;
EXTERNAL Widget   label_error_one;
EXTERNAL Widget   label_error_three;
EXTERNAL Widget   bulletinBoard_message;
EXTERNAL Widget   label_message;
EXTERNAL Widget   label_about_version;
EXTERNAL Widget   bulletinBoard;
EXTERNAL Widget   pushButton_interpolaterepeats;
EXTERNAL Widget   pushButton_unflag;
EXTERNAL Widget   pushButton_flag;
EXTERNAL Widget   pushButton_controls_timeinterpolation;
EXTERNAL Widget   pushButton_controls_deletebadtimetag;
EXTERNAL Widget   toggleButton_org_sonardepth;
EXTERNAL Widget   toggleButton_sonardepth;
EXTERNAL Widget   pushButton_solution;
EXTERNAL Widget   toggleButton_dr_lat;
EXTERNAL Widget   toggleButton_dr_lon;
EXTERNAL Widget   toggleButton_org_time;
EXTERNAL Widget   toggleButton_time;
EXTERNAL Widget   pushButton_file;
EXTERNAL Widget   toggleButton_vru;
EXTERNAL Widget   pushButton_revert;
EXTERNAL Widget   pushButton_interpolate;
EXTERNAL Widget   radioBox;
EXTERNAL Widget   toggleButton_pick;
EXTERNAL Widget   toggleButton_select;
EXTERNAL Widget   toggleButton_deselect;
EXTERNAL Widget   toggleButton_selectall;
EXTERNAL Widget   toggleButton_deselectall;
EXTERNAL Widget   pushButton_heading_cmg;
EXTERNAL Widget   toggleButton_show_cmg;
EXTERNAL Widget   toggleButton_org_heading;
EXTERNAL Widget   pushButton_speed_smg;
EXTERNAL Widget   toggleButton_show_smg;
EXTERNAL Widget   toggleButton_org_speed;
EXTERNAL Widget   toggleButton_org_lat;
EXTERNAL Widget   toggleButton_org_lon;
EXTERNAL Widget   toggleButton_speed;
EXTERNAL Widget   toggleButton_heading;
EXTERNAL Widget   toggleButton_lat;
EXTERNAL Widget   toggleButton_lon;
EXTERNAL Widget   scrolledWindow;
EXTERNAL Widget   drawingArea;
/**
 * End Global Widget Declarations.
 */
#endif
