#!/usr/bin/env python3
#--------------------------------------------------------------------
#    The MB-system:  mbpy_grdplot_script.py
#
#    Copyright (c) 2026 by
#    David W. Caress (caress@mbari.org)
#      Monterey Bay Aquarium Research Institute
#      Moss Landing, California, USA
#
#    See README.md file for copying and redistribution conditions.
#--------------------------------------------------------------------
#
# Purpose:
#   Wires mbpy_layout.py / mbpy_color.py / mbpy_misc.py
#   together into an actual GMT **modern mode** plotting script -- the
#   Python-port equivalent of mbm_grdplot's own classic-mode <root>.cmd
#   shellscript generator (mbm_grdplot lines ~2050-3095), but targeting
#   `gmt begin`/`gmt end` and subcommands (grdimage, coast, grdcontour,
#   basemap, plot, text, colorbar) instead of ps-prefixed classic-mode
#   commands with manual -K/-O bookkeeping.
#
#   This intentionally drops several things mbm_grdplot's own script
#   had to do only because of classic mode's statelessness: no -K/-O
#   flags at all (gmt begin/end tracks the session), and -R/-J are
#   still passed explicitly on every map-layer command below for
#   clarity/robustness even though modern mode would let later ones
#   omit them (both are equally correct; being explicit costs nothing
#   and makes each command runnable/copyable on its own).
#
# Status:
#   Covers color_mode 1 (plain color fill), 2 (color shaded relief via
#   a custom illumination model), 3 (color shaded by an intensity
#   grid, raw or histogram-equalized), 4 (color fill of slope
#   magnitude), 5 (color shaded by slope magnitude), 6 (image plot
#   using an image's own embedded georeferencing), and 7 (image plot
#   placed using -R bounds, for an image with no georeferencing of its
#   own) -- each with or without a grdcontour overlay -- plus
#   coastline, a swath-navigation/ping-tick overlay (via MB-System's
#   own `gmt mbcontour` GMT supplement module), xy overlays, text
#   labels, a basemap with mbm_grdplot's own tick-interval heuristic,
#   and (color_mode 1-5 only, and only when the palette/grid type
#   makes a scale meaningful -- see _show_colorscale()) a color scale
#   bar placed per mbpy_layout's scale_loc geometry. Verified by
#   running the generated script through a real GMT 6 installation and
#   checking it exits cleanly and produces a non-trivial output file --
#   see test_mbpy_grdplot_script.py, test_mbpy_grdplot_shade.py,
#   test_mbpy_grdplot_image.py, and test_mbpy_grdplot_navigation.py.
#
#   A real bug in this module (not upstream mbm_grdplot) was found while
#   testing it through the actual mbm_grdplotnew CLI rather than only
#   through hand-built ScriptOptions in test scripts: the grdcontour
#   command never included a -C flag at all, so every contour overlay
#   generated by any earlier test in this port silently fell back to
#   GMT's own automatic contour levels instead of the level/interval the
#   caller asked for. Fixed by adding ScriptOptions.contour_interval,
#   which defaults to layout.contour_int when not given, mirroring
#   mbm_grdplot's own $contour_control fallback (mbm_grdplot line
#   ~1932-1934) exactly.
#
#   A second real bug in this module was found while comparing real
#   mbm_grdplotnew output against archived mbm_grdplot output for an
#   actual survey: the color scale bar's -D placement used both
#   layout.colorscale_offx and colorscale_offy together
#   ("-Dx{offx}/{offy}..."), but mbm_grdplot itself hardcodes whichever
#   of the two does not apply to the bar's orientation to 0 (mbm_grdplot
#   lines ~2965-2974) -- colorscale_offx is only meaningful for a
#   vertical bar, colorscale_offy only for a horizontal one. This was
#   silently shifting every colorbar this port had ever generated. Fixed
#   in the colorbar emission below.
#
#   A third real bug turned up in the same comparison: the baseline
#   `gmt gmtset` defaults included PS_MEDIA and PS_PAGE_ORIENTATION
#   LANDSCAPE, a literal port of mbm_grdplot's own classic-mode
#   baseline. In modern mode these did not just go unused -- PS_PAGE_
#   ORIENTATION LANDSCAPE rotated the auto-sized output 90 degrees, and
#   PS_MEDIA forced a full physical-page canvas with large blank
#   margins around it, both confirmed by comparing rendered output
#   against a real mbm_grdplot map before and after removing them (see
#   baseline_gmt_defaults()'s docstring). Removed from the baseline
#   entirely; modern mode's own content-based auto-sizing replaces
#   what both were for in classic mode.
#
import math
import shlex
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import List, Optional, Tuple

from mbpy_color import CptLine
from mbpy_layout import GridInfo, Layout
from mbpy_misc import ContourOptions, CoastOptions, NavigationOptions, XYOverlayEntry

# mbm_grdplot's own approximation of pi (mbm_grdplot line ~87: "$DTR =
# 3.1415926 / 180.0"), not math.pi -- kept for parity with its exact
# illumination-vector numbers, though the difference is far below any
# visually or numerically meaningful threshold.
_DTR = 3.1415926 / 180.0

# Page-size-keyed GMT media name and annotation/title font sizes
# (mbm_grdplot lines ~122-158: %page_anot_font, %page_header_font,
# %page_gmt_name), used only to build the baseline `gmt gmtset` lines
# below -- geometry-affecting page dimensions live in
# mbpy_layout.PAGE_WIDTH_IN/PAGE_HEIGHT_IN instead.
PAGE_ANOT_FONT = {
    "a": 8, "b": 12, "c": 16, "d": 24,
    "e": 24, "f": 24, "e1": 24, "a0": 24,
    "a1": 24, "a2": 16, "a3": 12, "a4": 8,
    "a5": 6, "a6": 6, "a7": 6, "a8": 4,
    "a9": 4, "a10": 4, "b0": 24, "b1": 24,
    "b2": 16, "b3": 16, "b4": 12, "b5": 8,
    "b6": 6, "b7": 4, "b8": 4, "b9": 4,
    "b10": 4, "c0": 24, "c1": 24, "c2": 16,
    "c3": 12, "c4": 8, "c5": 6, "c6": 6,
    "c7": 6, "m1": 24, "m2": 24, "m3": 24,
    "m4": 24, "m5": 24, "m6": 24,
}

PAGE_HEADER_FONT = {
    "a": 10, "b": 15, "c": 20, "d": 30,
    "e": 30, "f": 30, "e1": 30, "a0": 30,
    "a1": 30, "a2": 20, "a3": 15, "a4": 10,
    "a5": 8, "a6": 8, "a7": 8, "a8": 5,
    "a9": 5, "a10": 5, "b0": 30, "b1": 30,
    "b2": 20, "b3": 20, "b4": 15, "b5": 10,
    "b6": 8, "b7": 5, "b8": 5, "b9": 5,
    "b10": 5, "c0": 30, "c1": 30, "c2": 20,
    "c3": 15, "c4": 10, "c5": 8, "c6": 8,
    "c7": 8, "m1": 30, "m2": 30, "m3": 30,
    "m4": 30, "m5": 30, "m6": 30,
}

# Not currently used by baseline_gmt_defaults() -- see its docstring
# for why PS_MEDIA (the only consumer this table would have) is not
# set in modern mode. Kept because it is still a faithful, potentially
# useful port of mbm_grdplot's own %page_gmt_name table, not because
# anything here reads it today.
PAGE_GMT_NAME = {
    "a": "archA", "b": "archB", "c": "archC", "d": "archD",
    "e": "archE", "f": "B0", "e1": "B0", "a0": "A0",
    "a1": "A1", "a2": "A2", "a3": "A3", "a4": "A4",
    "a5": "A5", "a6": "A6", "a7": "A7", "a8": "A8",
    "a9": "A9", "a10": "A10", "b0": "B0", "b1": "B1",
    "b2": "B2", "b3": "B3", "b4": "B4", "b5": "B5",
    "b6": "A6", "b7": "A7", "b8": "A8", "b9": "A9",
    "b10": "A10", "c0": "B0", "c1": "B1", "c2": "B2",
    "c3": "B3", "c4": "B4", "c5": "B5", "c6": "B6",
    "c7": "B7", "m1": "Custom_4241x5655", "m2": "Custom_4241x6578",
    "m3": "Custom_4241x7540", "m4": "Custom_4712x5655",
    "m5": "Custom_4712x6578", "m6": "Custom_4712x7540",
}


def baseline_gmt_defaults(pagesize: str, color_flip: bool, degree_format: str) -> List[str]:
    """Port of the baseline `gmt gmtset` lines mbm_grdplot always emits
    before any user -MGD overrides (mbm_grdplot lines ~2069-2100).
    Returns a list of "PARAM value" strings, one gmtset call each.

    NOTE: mbm_grdplot's own baseline also sets PS_MEDIA (to the chosen
    page size's classic media name) and PS_PAGE_ORIENTATION (always
    "LANDSCAPE", with portrait pages instead requested per-command via
    a separate classic-mode -P flag). Neither is reproduced here: they
    are classic-mode page-layout concepts for positioning a plot on a
    fixed full-size physical page via explicit -X/-Y, which modern
    mode does not use at all (it sizes the canvas to the actual plotted
    content instead). Confirmed directly, not assumed: including them
    verbatim did not just leave stray unused settings -- PS_PAGE_
    ORIENTATION LANDSCAPE actively rotated modern mode's auto-sized
    output 90 degrees, and PS_MEDIA forced a full physical-page-sized
    canvas around it with large blank margins, when compared against
    real mbm_grdplot output for the same data. Dropping both lets
    modern mode's own auto-sizing take over, which then matched the
    classic-mode reference image closely (same content, tightly
    cropped, correctly oriented). COLOR_BACKGROUND/COLOR_FOREGROUND
    are still swapped when color_flip is set, matching mbm_grdplot
    exactly -- those are unrelated to page sizing.
    """
    anot_font = PAGE_ANOT_FONT[pagesize]
    header_font = PAGE_HEADER_FONT[pagesize]
    lines = [
        "PROJ_LENGTH_UNIT inch",
        f"FONT_ANNOT_PRIMARY {anot_font},Helvetica,black",
        f"FONT_ANNOT_SECONDARY {anot_font},Helvetica,black",
        f"FONT_LABEL {anot_font},Helvetica,black",
        f"FONT_TITLE {header_font},Helvetica,black",
    ]
    if color_flip:
        lines += ["COLOR_BACKGROUND white", "COLOR_FOREGROUND black"]
    else:
        lines += ["COLOR_BACKGROUND black", "COLOR_FOREGROUND white"]
    lines += ["COLOR_NAN white", f"FORMAT_GEO_MAP {degree_format}"]
    return lines


def write_cpt_file(path: str, lines: List[CptLine]) -> None:
    """Write CPT lines directly to `path` in GMT's plain-text CPT
    format (one "z0 r0 g0 b0 z1 r1 g1 b1" segment per line). mbm_grdplot
    builds the same content in its classic-mode script via a chain of
    `echo ... >> $CPT_FILE` shell commands; here Python just writes the
    file directly, so there is no equivalent step in the generated
    script at all.
    """
    with open(path, "w") as f:
        for line in lines:
            f.write(line.format_echo() + "\n")


@dataclass
class ShadeOptions:
    """Parameters for color_mode 2/3/4/5 (mbm_grdplot's shading/slope
    family). Leave unset (ScriptOptions.shade = None) for color_mode 1
    (plain color fill).

    color_mode:
      2 -- color shaded relief: the data grid, colored by the normal
           z-value CPT, shaded by a custom illumination model built
           from azimuth/elevation/magnitude (mbm_grdplot lines
           ~2499-2549);
      3 -- color shaded by an intensity grid (file_intensity), either
           used as-is or histogram-equalized and scaled by magnitude
           first if stretch_shade (lines ~2553-2569);
      4 -- color fill of slope magnitude: grdimage draws the computed
           slope-magnitude grid itself (through the color_mode == 4
           CPT already built by mbpy_color.build_slope_boundaries),
           no separate intensity layer (lines ~2571-2602, ~2609-2611);
      5 -- color shaded by slope magnitude: the data grid, colored by
           the normal z-value CPT, shaded by the slope-magnitude grid
           scaled by `magnitude` (same lines, plus -I$file_slope at
           line ~2639-2642).
    """
    color_mode: int
    magnitude: Optional[float] = None
    azimuth: Optional[float] = None
    elevation: Optional[float] = None
    shade_flip: bool = False                 # -D's second field ($shade_flip)
    file_intensity: Optional[str] = None     # mode 3 only: user-supplied intensity grid
    stretch_shade: bool = False              # mode 3 only: histogram-equalize file_intensity first


def resolve_shade_defaults(shade: ShadeOptions) -> ShadeOptions:
    """Port of the magnitude/azimuth/elevation defaulting at mbm_grdplot
    lines ~800-818 and the shade_flip negation at line ~884-887."""
    magnitude, azimuth, elevation = shade.magnitude, shade.azimuth, shade.elevation
    if shade.color_mode == 2:
        if azimuth is None:
            azimuth = 0.0
        if magnitude is None:
            magnitude = 1.0
        if elevation is None:
            elevation = 30.0
    elif shade.color_mode == 3 and magnitude is None:
        magnitude = -0.4
    if shade.color_mode >= 4 and magnitude is None:
        magnitude = 1.0
    if shade.shade_flip and magnitude is not None:
        magnitude = -1 * magnitude
    return replace(shade, magnitude=magnitude, azimuth=azimuth, elevation=elevation)


def _illumination_commands(
    grid: str, root: str, magnitude: float, azimuth: float, elevation: float, geographic: bool
) -> Tuple[List[str], str]:
    """Port of the color_mode == 2 shading-array pipeline (mbm_grdplot
    lines ~2499-2549): a custom Lambertian illumination model built
    from the x/y gradient components, not a plain `grdgradient -A -Nt`.
    Returns (commands, path-to-final-intensity-grid).
    """
    fg = " -fg" if geographic else ""
    light_x = math.sin(_DTR * azimuth) * math.cos(_DTR * elevation)
    light_y = math.cos(_DTR * azimuth) * math.cos(_DTR * elevation)
    light_z = math.sin(_DTR * elevation)

    drvx, drvy = f"{root}_drvx.grd", f"{root}_drvy.grd"
    magx, magy = f"{root}_magx.grd", f"{root}_magy.grd"
    denom = f"{root}_denom.grd"
    normx, normy, normz = f"{root}_normx.grd", f"{root}_normy.grd", f"{root}_normz.grd"
    intfile = f"{root}_int.grd"

    commands = [
        f"gmt grdgradient {grid} -A90 -G{drvx}{fg}",
        f"gmt grdgradient {grid} -A0 -G{drvy}{fg}",
        f"gmt grdmath {drvx} {magnitude:.6g} MUL 10 MUL = {magx}",
        f"gmt grdmath {drvy} {magnitude:.6g} MUL 10 MUL = {magy}",
        f"gmt grdmath {magx} 2.0 POW {magy} 2.0 POW ADD 1.0 ADD SQRT = {denom}",
        f"gmt grdmath {magx} {denom} DIV = {normx}",
        f"gmt grdmath {magy} {denom} DIV = {normy}",
        f"gmt grdmath 1.0 {denom} DIV = {normz}",
        f"gmt grdmath {normx} {light_x:.6g} MUL {normy} {light_y:.6g} MUL ADD "
        f"{normz} {light_z:.6g} MUL ADD -0.5 ADD = {intfile}",
        f"rm -f {drvx} {drvy} {magx} {magy} {denom} {normx} {normy} {normz}",
    ]
    return commands, intfile


def _intensity_commands_mode3(
    file_intensity: str, root: str, stretch_shade: bool, magnitude: float
) -> Tuple[List[str], str]:
    """Port of the color_mode == 3 intensity-file handling (mbm_grdplot
    lines ~2553-2569). Returns (commands, path-to-final-intensity-grid);
    commands is empty when the intensity grid is used unaltered."""
    if not stretch_shade:
        return [], file_intensity
    eqfile = f"{root}_intenseq.grd"
    intfile = f"{root}_int.grd"
    commands = [
        f"gmt grdhisteq {file_intensity} -G{eqfile} -N",
        f"gmt grdmath {eqfile} {magnitude:.6g} MUL = {intfile}",
        f"rm -f {eqfile}",
    ]
    return commands, intfile


def _slope_commands(
    grid: str, root: str, geographic: bool, scale_by_magnitude: Optional[float]
) -> Tuple[List[str], str]:
    """Port of the color_mode == 4/5 slope-magnitude pipeline
    (mbm_grdplot lines ~2571-2602). Pass `scale_by_magnitude` (mode 5
    only) to multiply the slope grid by `magnitude`; leave None for
    mode 4, which does not scale it (the color_mode == 4 CPT itself
    already spans 0..magnitude -- see
    mbpy_color.build_slope_boundaries()).
    """
    fg = " -fg" if geographic else ""
    drvx, drvy = f"{root}_drvx.grd", f"{root}_drvy.grd"
    slope = f"{root}_slope.grd"
    expr = f"gmt grdmath {drvx} 2.0 POW {drvy} 2.0 POW ADD SQRT"
    if scale_by_magnitude is not None:
        expr += f" {scale_by_magnitude:.6g} MUL"
    expr += f" = {slope}"
    commands = [
        f"gmt grdgradient {grid} -A90 -G{drvx}{fg}",
        f"gmt grdgradient {grid} -A0 -G{drvy}{fg}",
        expr,
        f"rm -f {drvx} {drvy}",
    ]
    return commands, slope


@dataclass
class ScriptOptions:
    grid: str
    root: str
    layout: Layout
    grid_info: GridInfo
    output_format: str = "pdf"          # gmt begin's figure format: pdf, png, ps, jpg, ...
    title: Optional[str] = None
    tick_info: Optional[str] = None     # raw -B string override; else computed from layout.base_tick
    colorbar_label: Optional[str] = None   # -B+l"..." on the color scale bar [default: "z"]
    length_scale: Optional[str] = None      # raw -MGL value, emitted as -L<value> on `gmt basemap`
                                             # (a GMT distance scale bar, e.g. "fx10/2/32.70/5.0+lkm")
    dpi: Optional[int] = None               # -MGQ: -E<dpi> on grdimage, and the final raster's own
                                             # resolution (emitted via `gmt figure` after `gmt begin`)

    # color fill / shading (color_mode 1-5) or image plot (6/7)
    color_fill: bool = True
    shade: Optional[ShadeOptions] = None   # None => plain color_mode 1 fill
    image_mode: Optional[int] = None       # 6 or 7 -- see generate_script(); overrides shade/cpt_*
    color_palette: int = 1                  # from mbpy_color.ColorControl.color_palette;
                                             # consulted for _show_colorscale() and the baseline
                                             # gmtset defaults below
    color_flip: bool = False                # from mbpy_color.ColorControl / -D's first field;
                                             # swaps COLOR_BACKGROUND/COLOR_FOREGROUND in the baseline
                                             # gmtset defaults, matching mbm_grdplot exactly
    data_scale: Optional[float] = None      # -MGS: rescale the grid before colorizing/shading
    cpt_lines: Optional[List[CptLine]] = None   # generated CPT content, written to <root>.cpt
    cpt_file: Optional[str] = None               # OR: an existing CPT file to use as-is (-W<file>)

    # optional overlays
    contour: Optional[ContourOptions] = None
    contour_interval: Optional[str] = None   # raw -C value (a level, spacing, or .cpt path) for
                                              # grdcontour; defaults to layout.contour_int if unset,
                                              # matching mbm_grdplot's own $contour_control fallback
                                              # (mbm_grdplot line ~1932-1934)
    contour_file: Optional[str] = None   # grid to contour; defaults to `grid` if contour is set
    coast: Optional[CoastOptions] = None
    navigation: Optional[NavigationOptions] = None   # requires .swathnavdatalist; see generate_script()
    xy_entries: List[XYOverlayEntry] = field(default_factory=list)
    text_labels: List[str] = field(default_factory=list)   # raw "tx/ty/tsize/tangle/font/just/txt"

    gmt_defs: List[str] = field(default_factory=list)   # user "PARAM/value" overrides (-MGD)


def _basemap_axes(opts: ScriptOptions) -> str:
    """Port of the -B assembly at mbm_grdplot lines ~2745-2801.

    NOTE: -BWESN forces annotations on all four sides of the frame. This
    is required in GMT modern mode (unlike classic mode, which mbm_grdplot
    targets): when an earlier plot layer in the same figure -- here,
    grdimage -- implicitly claims a subset of frame sides, a later `gmt
    basemap` call with a bare interval (e.g. -B2m) only annotates the
    sides not yet claimed, silently dropping tick labels from two sides.
    Confirmed directly: without -BWESN, the generated maps were missing
    lat/lon tick labels on the top and right sides entirely (only
    bottom/left were annotated), while the classic-mode reference always
    annotates all four sides.
    """
    grid = opts.grid_info
    tick = opts.layout.base_tick

    # WESN and +t<title> both belong to the single "frame settings" -B
    # invocation GMT allows (axes-side selectors and +t/+g/etc. modifiers
    # cannot be split across two separate -B occurrences); the interval
    # spec(s) below are the separate "axes parameters" -B occurrence(s).
    frame = "-BWESN" + (f'+t"{opts.title}"' if opts.title else "")

    if opts.tick_info:
        interval = f"-B{opts.tick_info}"
    elif tick.tick_x == tick.tick_y and tick.xlabel is None and tick.ylabel is None:
        interval = f"-B{tick.tick_x}"
    else:
        interval = f"-Bx{tick.tick_x}+l{tick.xlabel}" if tick.xlabel else f"-Bx{tick.tick_x}"
        interval += f" -By{tick.tick_y}+l{tick.ylabel}" if tick.ylabel else f" -By{tick.tick_y}"

    return f"{frame} {interval}"


def _show_colorscale(opts: ScriptOptions) -> bool:
    """Port of the psscale/colorbar gate at mbm_grdplot lines ~2958-2960:
    ($color_mode && $color_mode < 6 && ($color_palette < 5 || $color_palette
    >= 8) && $gridprojected != 2). Only meaningful when opts.color_fill is
    true and opts.image_mode is None (color_mode 1-5) -- image plots
    (6/7) never reach this, since they have no scalar z to key a scale
    to at all (see the image_mode branch in generate_script()).

    color_palette 5-7 are Uniform Gray/Black/White (a single flat color,
    so a scale bar would show nothing meaningful); gridprojected == 2 is
    a seismic profile (trace number vs. time), which mbm_grdplot never
    gives a z color scale either.
    """
    return (
        (opts.color_palette < 5 or opts.color_palette >= 8)
        and opts.grid_info.gridprojected != 2
    )


def generate_script(opts: ScriptOptions) -> str:
    """Build the full GMT modern-mode shellscript text for `opts`.
    Does not touch the filesystem (except that the caller is expected
    to have already written opts.cpt_lines via write_cpt_file(), or to
    do so before running the returned script) -- see generate_and_write().
    """
    lay = opts.layout
    j = f"-J{lay.projection}{lay.projection_pars}"
    r = f"-R{lay.region}"
    cptfile = opts.cpt_file or f"{opts.root}.cpt"

    lines = [
        "#!/usr/bin/env bash",
        "#",
        f"# GMT modern-mode plotting script for {opts.grid}",
        "# Generated by mbpy_grdplot_script.py (Python port of mbm_grdplot)",
        "#",
        "set -e",
        "",
        f"gmt begin {opts.root} {opts.output_format}",
        "",
    ]

    if opts.dpi:
        # sets the final raster's own resolution (the psconvert-equivalent
        # -E<dpi>, not grdimage's own -E<dpi> below); see
        # ScriptOptions.dpi's docstring and gmt figure's "psconvertoptions".
        lines.append(f"gmt figure {opts.root} {opts.output_format} E{opts.dpi}")
        lines.append("")

    # `gmt set` (not the classic-mode-era `gmt gmtset` name) sets GMT
    # defaults for the session; both baseline and user overrides are
    # batched into one call each, matching modern mode's own idiom of
    # "gmt set PARAM1 val1 PARAM2 val2 ..." rather than one call per
    # parameter.
    lines.append("# Set temporary GMT defaults")
    baseline_pairs = []
    for gmt_def in baseline_gmt_defaults(lay.pagesize, opts.color_flip, lay.degree_format):
        param, _, value = gmt_def.partition(" ")
        baseline_pairs.append(f"{param} {value}")
    lines.append(f"gmt set {' '.join(baseline_pairs)}")
    lines.append("")

    if opts.gmt_defs:
        lines.append("# User-defined GMT parameter overrides")
        user_pairs = []
        for gmt_def in opts.gmt_defs:
            param, _, value = gmt_def.partition("/")
            user_pairs.append(f"{param} {value}")
        lines.append(f"gmt set {' '.join(user_pairs)}")
        lines.append("")

    # rescale the grid if requested (-MGS), mirroring mbm_grdplot's
    # $file_use, which every mode below draws/shades/contours from
    # instead of the raw input grid whenever a data_scale is given
    file_use = opts.grid
    if opts.data_scale is not None:
        file_use = f"{opts.root}_scaled.grd"
        lines.append("# Rescale data")
        lines.append(f"gmt grdmath {opts.grid} {opts.data_scale:.6g} MUL = {file_use}")
        lines.append("")

    # the color_mode 4/5 slope grid is the one intermediate mbm_grdplot
    # itself deletes at the end (mbm_grdplot line ~3042-3044); unlike
    # the color_mode 2/3 intensity grid, which it leaves behind -- both
    # behaviors are reproduced here rather than "improved"
    temp_file_cleanup = None

    if opts.image_mode is not None:
        # color_mode 6/7: grdimage of an already-colored image (mbm_grdplot
        # lines ~2618-2634) -- no CPT, no -I shading, and (unlike color_mode
        # 1-5) no color scale bar, since there is no scalar z to key one to.
        if opts.image_mode == 6:
            # No -D option: GMT's grdimage auto-detects an image's embedded
            # georeferencing on its own. Explicitly passing -D/-Dr causes
            # GMT (as of 6.7.0) to zero the image's read padding before it
            # knows whether reprojection is needed, which then aborts with
            # "gmt_img_project: Input image does not have sufficient (2)
            # padding" for any non-Cartesian projection (e.g. -Jm) -- the
            # same bug already fixed in mbm_grdplot itself for this mode
            # (see ChangeLog 5.8.3beta21).
            lines.append(f"gmt grdimage {file_use} {j} {r}" + (f" -E{opts.dpi}" if opts.dpi else ""))
        elif opts.image_mode == 7:
            # mbm_grdplot passes -Dr here (the image carries no
            # georeferencing of its own, so GMT must be told to place it
            # using the -R bounds instead) -- but -Dr hits the exact same
            # GMT 6.7.0 padding bug as mode 6's -D under a non-Cartesian
            # projection, and mode 7 cannot simply omit it the way mode 6
            # does, since that -R placement is the whole point of this
            # mode. Worked around instead by pre-attaching -R to the image
            # as if it were real embedded georeferencing, then treating it
            # exactly like mode 6 -- no -D/-Dr needed at all once the image
            # "has" georeferencing.
            #
            # NOTE: `gmt grdedit` cannot do this attachment -- it is a
            # scalar-grid tool and silently collapses a 3-band RGB image
            # down to one grayscale band (confirmed directly: a real RGB
            # PNG round-tripped through grdedit came out Band 1 Type=
            # Float32 ColorInterp=Gray), which grdimage then renders
            # through its own default rainbow CPT instead of the image's
            # real colors. `gdal_translate -a_ullr` performs the same
            # attachment while preserving all bands untouched, so it is
            # used here instead, at the cost of depending on the gdal_
            # translate CLI tool (present alongside any GMT built with
            # GDAL image support, which -A/=gd: image I/O already requires).
            xmin, xmax, ymin, ymax = lay.region.split("/")
            georef_file = f"{opts.root}_georef.tif"
            lines.append(
                f"gdal_translate -a_ullr {xmin} {ymax} {xmax} {ymin} {file_use} {georef_file}"
            )
            lines.append(f"gmt grdimage {georef_file} {j} {r}" + (f" -E{opts.dpi}" if opts.dpi else ""))
            temp_file_cleanup = georef_file
        else:
            raise ValueError(f"image_mode must be 6 or 7, got {opts.image_mode}")
        lines.append("")

    elif opts.color_fill:
        shade = resolve_shade_defaults(opts.shade) if opts.shade else None
        geographic = opts.grid_info.gridprojected == 0
        grid_for_image = file_use
        intensity_file = None

        if shade is None or shade.color_mode == 1:
            pass
        elif shade.color_mode == 2:
            cmds, intensity_file = _illumination_commands(
                file_use, opts.root, shade.magnitude, shade.azimuth, shade.elevation, geographic
            )
            lines.append("# Get shading array")
            lines.extend(cmds)
            lines.append("")
        elif shade.color_mode == 3:
            if not shade.file_intensity:
                raise ValueError("color_mode 3 requires shade.file_intensity")
            cmds, intensity_file = _intensity_commands_mode3(
                shade.file_intensity, opts.root, shade.stretch_shade, shade.magnitude
            )
            if cmds:
                lines.append("# Get shading array")
                lines.extend(cmds)
                lines.append("")
        elif shade.color_mode == 4:
            cmds, grid_for_image = _slope_commands(file_use, opts.root, geographic, None)
            temp_file_cleanup = grid_for_image
            lines.append("# Get slope array")
            lines.extend(cmds)
            lines.append("")
        elif shade.color_mode == 5:
            cmds, intensity_file = _slope_commands(file_use, opts.root, geographic, shade.magnitude)
            temp_file_cleanup = intensity_file
            lines.append("# Get slope array")
            lines.extend(cmds)
            lines.append("")
        else:
            raise ValueError(f"unsupported color_mode: {shade.color_mode}")

        grdimage_parts = [f"gmt grdimage {grid_for_image} {j} {r} -C{cptfile}"]
        if intensity_file:
            grdimage_parts.append(f"-I{intensity_file}")
        if opts.dpi:
            grdimage_parts.append(f"-E{opts.dpi}")
        lines.append(" ".join(grdimage_parts))
        if _show_colorscale(opts):
            label = opts.colorbar_label if opts.colorbar_label is not None else "z"
            # Port of mbm_grdplot lines ~2965-2974: for a vertical bar
            # (scale_loc l/r) the Y half of -Dx<x>/<y> is hardcoded to 0
            # and only colorscale_offx is used; for a horizontal bar
            # (scale_loc t/b) it's the reverse -- X is hardcoded to 0 and
            # only colorscale_offy is used. colorscale_offx/offy are NOT
            # both used together the way a naive "-Dx{offx}/{offy}"
            # reading of the layout fields would suggest -- confirmed
            # against real mbm_grdplot output (a wrong offx there was
            # silently shifting every colorbar generated by this port
            # until this was caught).
            if lay.colorscale_vh == "+v":
                d_xy = f"{lay.colorscale_offx:.5g}/0"
            else:
                d_xy = f"0/{lay.colorscale_offy:.5g}"
            lines.append(
                f"gmt colorbar -C{cptfile} "
                f"-Dx{d_xy}"
                f"{lay.colorscale_vh}+w{lay.colorscale_length:.5g}/{lay.colorscale_thick:.5g} "
                f'-B+l"{label}"'
            )
        lines.append("")

    if opts.contour is not None:
        cfile = opts.contour_file or file_use
        contour_interval = opts.contour_interval or lay.contour_int
        cparts = [f"gmt grdcontour {cfile} {j} {r} -C{contour_interval}"]
        c = opts.contour
        if c.contour_anot_int:
            cparts.append(f"-A{c.contour_anot_int}")
        cparts.append(f"-W{c.contour_pen or 'c1p'}")
        if c.contour_gap:
            cparts.append(f"-G{c.contour_gap}")
        if c.contour_cut:
            cparts.append(f"-Q{c.contour_cut}")
        if c.contour_tick_on:
            cparts.append(f"-T+d{c.contour_tick}" if c.contour_tick else "-T")
        lines.append(" ".join(cparts))
        lines.append("")

    if opts.coast is not None:
        co = opts.coast
        cparts = [f"gmt coast {j} {r}"]
        if co.coast_resolution:
            cparts.append(f"-D{co.coast_resolution}")
        if co.coast_dryfill:
            cparts.append(f"-G{co.coast_dryfill}")
        if co.coast_wetfill:
            cparts.append(f"-S{co.coast_wetfill}")
        if co.coast_lakefill:
            cparts.append(f"-C{co.coast_lakefill}")
        if co.coast_river:
            cparts.append(f"-I{co.coast_river}")
        for boundary in co.coast_boundaries:
            cparts.append(f"-N{boundary}")
        if co.coast_pen:
            cparts.append(f"-W{co.coast_pen}")
        lines.append(" ".join(cparts))
        lines.append("")

    if opts.navigation is not None and opts.navigation.swathnavdatalist:
        # Port of the swath nav plot (mbm_grdplot lines ~2900-2940): the
        # ship track, tick/date annotations, filename label, and
        # ping-number annotations are all handled by MB-System's own
        # `gmt mbcontour` GMT supplement module, not built up here from
        # primitive psxy-style calls. `opts.navigation.swathformat` must
        # already be resolved to a concrete value (see
        # mbpy_misc.resolve_swath_format()) and navigation_control/
        # pingnumber_control already normalized (see
        # mbpy_misc.resolve_navigation_control()) -- this function
        # only assembles the command line, matching generate_script()'s
        # no-filesystem-access contract.
        nav = opts.navigation
        nparts = [f"gmt mbcontour -F{nav.swathformat} -I{nav.swathnavdatalist} {j} {r}"]
        if nav.navigation_mode:
            nparts.append(f"-D{nav.navigation_control}")
        if nav.name_mode and nav.name_perp:
            nparts.append(f"-G{nav.nav_name_hgt}/1")
        elif nav.name_mode:
            nparts.append(f"-G{nav.nav_name_hgt}")
        if nav.pingnumber_mode:
            nparts.append(f"-M{nav.pingnumber_control}")
        if nav.nav_pen:
            # NOTE: mbm_grdplot's own comment on this flag (line ~2936-2938):
            # mbcontour does not actually use standard GMT pen attributes
            # for the track line, setting PostScript pen state directly
            # instead -- so -W here is reproduced for parity but is
            # documented upstream as not working.
            nparts.append(f"-W{nav.nav_pen}")
        lines.append(" ".join(nparts))
        lines.append("")

    basemap_parts = [f"gmt basemap {j} {r} {_basemap_axes(opts)}"]
    if opts.length_scale:
        basemap_parts.append(f"-L{opts.length_scale}")
    lines.append(" ".join(basemap_parts))
    lines.append("")

    for entry in opts.xy_entries:
        xparts = [f"gmt plot {shlex.quote(entry.file)} {j} {r}"]
        if entry.fill != "N":
            xparts.append(f"-G{entry.fill}")
        if entry.symbol != "N":
            xparts.append(f"-S{entry.symbol}")
        if entry.pen != "N":
            xparts.append(f"-W{entry.pen}")
        lines.append(" ".join(xparts))
    if opts.xy_entries:
        lines.append("")

    if opts.text_labels:
        # -F+f+a+j (each modifier bare, no value) tells `gmt text` to read
        # that attribute from the data columns instead of applying one
        # fixed value to every record -- the modern-mode equivalent of
        # classic pstext's implicit "x y size angle font justify text"
        # input format. Unlike that classic format, modern `gmt text`
        # takes one combined "size,font" column (GMT's "fontinfo"), not
        # separate size and font columns, so they are joined here with a
        # comma rather than kept as two space-separated fields.
        lines.append(f"gmt text {j} {r} -F+f+a+j <<EOF")
        for raw in opts.text_labels:
            tx, ty, tsize, tangle, font, just, txt = raw.split("/", 6)
            lines.append(f"{tx} {ty} {tsize},{font} {tangle} {just} {txt}")
        lines.append("EOF")
        lines.append("")

    if temp_file_cleanup:
        lines.append("# Delete surplus files")
        lines.append(f"rm -f {temp_file_cleanup}")
        lines.append("")

    lines.append("gmt end")
    lines.append("")
    return "\n".join(lines)


def generate_and_write(opts: ScriptOptions, script_path: str) -> None:
    """Write both the CPT file (if opts.cpt_lines is set) and the
    generated shellscript to disk, and make the script executable."""
    if opts.cpt_lines is not None and opts.cpt_file is None:
        write_cpt_file(f"{opts.root}.cpt", opts.cpt_lines)
    Path(script_path).write_text(generate_script(opts))
    Path(script_path).chmod(0o755)
