
/* Begin user code block <abstract> */
/* End user code block <abstract> */

/**
 * README: Portions of this file are merged at file generation
 * time. Edits can be made *only* in between specified code blocks, look
 * for keywords <Begin user code> and <End user code>.
 */
/*
 * Generated by the ICS Builder Xcessory (BX).
 *
 * BuilderXcessory Version 6.1.3
 * Code Generator Xcessory 6.1.3 (08/19/04) CGX Scripts 6.1 Motif 2.1 
 *
 */
#include <Xm/Xm.h>
#include <Xm/Form.h>
#include <Xm/Text.h>
#include <Xm/PushB.h>
#include <Xm/DrawingA.h>
#include <Xm/RowColumn.h>
#include <Xm/ToggleB.h>
#include <Xm/Form.h>
#include <Xm/Text.h>
#include <Xm/PushB.h>
#include <Xm/DrawingA.h>
#include <Xm/RowColumn.h>
#include <Xm/ToggleB.h>
#include "Mb3dsdg.h"

/**
 * Common constant and pixmap declarations.
 */
#include "mb3dsoundings_creation.h"

/**
 * Convenience functions from utilities file.
 */
extern void RegisterBxConverters(XtAppContext);
extern XtPointer BX_CONVERT(Widget, char *, char *, int, Boolean *);
extern XtPointer BX_DOUBLE(double);
extern XtPointer BX_SINGLE(float);
extern void BX_MENU_POST(Widget, XtPointer, XEvent *, Boolean *);
extern Pixmap XPM_PIXMAP(Widget, char **);
extern void BX_SET_BACKGROUND_COLOR(Widget, ArgList, Cardinal *, Pixel);

/**
 * Declarations for callbacks and handlers.
 */
extern void do_mb3dsdg_dismiss(Widget, XtPointer, XtPointer);
extern void do_mb3dsdg_input(Widget, XtPointer, XtPointer);
extern void do_mb3dsdg_mouse_toggle(Widget, XtPointer, XtPointer);
extern void do_mb3dsdg_mouse_pick(Widget, XtPointer, XtPointer);
extern void do_mb3dsdg_mouse_erase(Widget, XtPointer, XtPointer);
extern void do_mb3dsdg_mouse_restore(Widget, XtPointer, XtPointer);
extern void do_mb3dsdg_mouse_grab(Widget, XtPointer, XtPointer);
extern void do_mb3dsdg_mouse_info(Widget, XtPointer, XtPointer);

/*
 * This table is used to define class resources that are placed
 * in app-defaults. This table is necessary so each instance
 * of this class has the proper default resource values set.
 * This eliminates the need for each instance to have
 * its own app-defaults values. This table must be NULL terminated.
 */
typedef struct _UIAppDefault {
    char*      cName;       /* Class name */
    char*      wName;       /* Widget name */
    char*      cInstName;   /* Name of class instance (nested class) */
    char*      wRsc;        /* Widget resource */
    char*      value;       /* value read from app-defaults */
} UIAppDefault;

static Boolean doInitAppDefaults = True;
static UIAppDefault  appDefaults[] = {
    {NULL, NULL, NULL, NULL, NULL}
};
/*
 * The functions to call in the apputils.c
 */
extern void InitAppDefaults(Widget, UIAppDefault*);
extern void SetAppDefaults(Widget, UIAppDefault*, char*, Boolean);

Mb3dsdgDataPtr
Mb3dsdgCreate ( Mb3dsdgDataPtr class_in, Widget parent, String name, ArgList args_in, Cardinal ac_in)
{
    Cardinal ac = 0;
    Arg      args[256];
    Cardinal cdc = 0;
    Boolean  argok = False;
    
    /**
     * Register the converters for the widgets.
     */
    RegisterBxConverters(XtWidgetToApplicationContext(parent));
    XtInitializeWidgetClass((WidgetClass)xmFormWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmTextWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmPushButtonWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmDrawingAreaWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmRowColumnWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmToggleButtonWidgetClass);
    /**
     * Setup app-defaults fallback table if not already done.
     */
    if (doInitAppDefaults)
    {
        InitAppDefaults(parent, appDefaults);
        doInitAppDefaults = False;
    }
    /**
     * Now set the app-defaults for this instance.
     */
    SetAppDefaults(parent, appDefaults, name, False);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(parent, (char *)"3D Soundings", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNdialogTitle, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
        XtSetArg(args[ac], XmNx, 102); ac++;
        XtSetArg(args[ac], XmNy, 50); ac++;
        XtSetArg(args[ac], XmNwidth, 528); ac++;
        XtSetArg(args[ac], XmNheight, 533); ac++;
        class_in->Mb3dsdg = XmCreateForm(parent,
            (char *)name,
            args, 
            ac);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNbackground, 
        BX_CONVERT(class_in->Mb3dsdg, (char *)"white", 
        XmRPixel, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 120); ac++;
    XtSetArg(args[ac], XmNy, 40); ac++;
    XtSetArg(args[ac], XmNwidth, 400); ac++;
    XtSetArg(args[ac], XmNheight, 50); ac++;
    XtSetArg(args[ac], XmNfontList, 
        BX_CONVERT(class_in->Mb3dsdg, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    class_in->text_status = XmCreateText(class_in->Mb3dsdg,
        (char *)"text_status",
        args, 
        ac);
    XtManageChild(class_in->text_status);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(class_in->Mb3dsdg, (char *)"Dismiss", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 50); ac++;
        XtSetArg(args[ac], XmNwidth, 100); ac++;
        XtSetArg(args[ac], XmNheight, 32); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(class_in->Mb3dsdg, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        class_in->pushButton_dismiss = XmCreatePushButton(class_in->Mb3dsdg,
            (char *)"pushButton_dismiss",
            args, 
            ac);
        XtManageChild(class_in->pushButton_dismiss);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(class_in->pushButton_dismiss, XmNactivateCallback, do_mb3dsdg_dismiss, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNborderWidth, 1); ac++;
    XtSetArg(args[ac], XmNbackground, 
        BX_CONVERT(class_in->Mb3dsdg, (char *)"white", 
        XmRPixel, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNborderColor, 
        BX_CONVERT(class_in->Mb3dsdg, (char *)"black", 
        XmRPixel, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 100); ac++;
    XtSetArg(args[ac], XmNwidth, 510); ac++;
    XtSetArg(args[ac], XmNheight, 420); ac++;
    class_in->drawingArea = XmCreateDrawingArea(class_in->Mb3dsdg,
        (char *)"drawingArea",
        args, 
        ac);
    XtManageChild(class_in->drawingArea);
    XtAddCallback(class_in->drawingArea, XmNinputCallback, do_mb3dsdg_input, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 519); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    XtSetArg(args[ac], XmNisHomogeneous, False); ac++;
    class_in->radioBox_soundingsmode = XmCreateRadioBox(class_in->Mb3dsdg,
        (char *)"radioBox_soundingsmode",
        args, 
        ac);
    XtManageChild(class_in->radioBox_soundingsmode);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"Toggle", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNwidth, 83); ac++;
        XtSetArg(args[ac], XmNheight, 28); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        class_in->toggleButton_mouse_toggle = XmCreateToggleButton(class_in->radioBox_soundingsmode,
            (char *)"toggleButton_mouse_toggle",
            args, 
            ac);
        XtManageChild(class_in->toggleButton_mouse_toggle);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(class_in->toggleButton_mouse_toggle, XmNvalueChangedCallback, do_mb3dsdg_mouse_toggle, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"Pick", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNwidth, 83); ac++;
        XtSetArg(args[ac], XmNheight, 28); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        class_in->toggleButton_mouse_pick = XmCreateToggleButton(class_in->radioBox_soundingsmode,
            (char *)"toggleButton_mouse_pick",
            args, 
            ac);
        XtManageChild(class_in->toggleButton_mouse_pick);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(class_in->toggleButton_mouse_pick, XmNvalueChangedCallback, do_mb3dsdg_mouse_pick, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"Erase", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNwidth, 83); ac++;
        XtSetArg(args[ac], XmNheight, 28); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        class_in->toggleButton_mouse_erase = XmCreateToggleButton(class_in->radioBox_soundingsmode,
            (char *)"toggleButton_mouse_erase",
            args, 
            ac);
        XtManageChild(class_in->toggleButton_mouse_erase);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(class_in->toggleButton_mouse_erase, XmNvalueChangedCallback, do_mb3dsdg_mouse_erase, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"Restore", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNwidth, 83); ac++;
        XtSetArg(args[ac], XmNheight, 28); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        class_in->toggleButton_mouse_restore = XmCreateToggleButton(class_in->radioBox_soundingsmode,
            (char *)"toggleButton_mouse_restore",
            args, 
            ac);
        XtManageChild(class_in->toggleButton_mouse_restore);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(class_in->toggleButton_mouse_restore, XmNvalueChangedCallback, do_mb3dsdg_mouse_restore, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"Grab", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNwidth, 83); ac++;
        XtSetArg(args[ac], XmNheight, 28); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        class_in->toggleButton_mouse_grab = XmCreateToggleButton(class_in->radioBox_soundingsmode,
            (char *)"toggleButton_mouse_grab",
            args, 
            ac);
        XtManageChild(class_in->toggleButton_mouse_grab);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(class_in->toggleButton_mouse_grab, XmNvalueChangedCallback, do_mb3dsdg_mouse_grab, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"Info", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNwidth, 83); ac++;
        XtSetArg(args[ac], XmNheight, 28); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(class_in->radioBox_soundingsmode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        class_in->toggleButton_mouse_info = XmCreateToggleButton(class_in->radioBox_soundingsmode,
            (char *)"toggleButton_mouse_info",
            args, 
            ac);
        XtManageChild(class_in->toggleButton_mouse_info);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(class_in->toggleButton_mouse_info, XmNvalueChangedCallback, do_mb3dsdg_mouse_info, (XtPointer)0);
    ac = 0;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftOffset, 120); ac++;
    XtSetArg(args[ac], XmNrightOffset, 8); ac++;
    XtSetArg(args[ac], XmNtopOffset, 40); ac++;
    XtSetValues(class_in->text_status, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 50); ac++;
    XtSetValues(class_in->pushButton_dismiss, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 11); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNrightOffset, 6); ac++;
    XtSetArg(args[ac], XmNtopOffset, 100); ac++;
    XtSetValues(class_in->drawingArea, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 10); ac++;
    XtSetValues(class_in->radioBox_soundingsmode, args, ac);
    
    
    /*
     * Assign functions to class record
     */
    
    
    /* Begin user code block <end_Mb3dsdgCreate> */
    /* End user code block <end_Mb3dsdgCreate> */
    
    return( class_in );
}
