/*
 * mbedit_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `mbedit.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "mbedit_ui.h"

/*
 * Create object `menu_file' in the specified instance.
 */
Xv_opaque
mbedit_menu_file_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Menu_item	mbedit_menu_file_item0_callback();
	extern Menu_item	action_show_colors();
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_TITLE_ITEM, "File",
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Load",
			MENU_GEN_PROC, mbedit_menu_file_item0_callback,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Show Colors",
			MENU_GEN_PROC, action_show_colors,
			NULL,
		MENU_GEN_PIN_WINDOW, owner, "File",
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `window_mbedit'.
 */
mbedit_window_mbedit_objects *
mbedit_window_mbedit_objects_initialize(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (mbedit_window_mbedit_objects *) calloc(1, sizeof (mbedit_window_mbedit_objects))))
		return (mbedit_window_mbedit_objects *) NULL;
	if (!ip->window_mbedit)
		ip->window_mbedit = mbedit_window_mbedit_window_mbedit_create(ip, owner);
	if (!ip->controls_mbedit)
		ip->controls_mbedit = mbedit_window_mbedit_controls_mbedit_create(ip, ip->window_mbedit);
	if (!ip->button_file)
		ip->button_file = mbedit_window_mbedit_button_file_create(ip, ip->controls_mbedit);
	if (!ip->button_quit)
		ip->button_quit = mbedit_window_mbedit_button_quit_create(ip, ip->controls_mbedit);
	if (!ip->slider_scale_x)
		ip->slider_scale_x = mbedit_window_mbedit_slider_scale_x_create(ip, ip->controls_mbedit);
	if (!ip->textfield_x_interval)
		ip->textfield_x_interval = mbedit_window_mbedit_textfield_x_interval_create(ip, ip->controls_mbedit);
	if (!ip->slider_scale_y)
		ip->slider_scale_y = mbedit_window_mbedit_slider_scale_y_create(ip, ip->controls_mbedit);
	if (!ip->textfield_y_interval)
		ip->textfield_y_interval = mbedit_window_mbedit_textfield_y_interval_create(ip, ip->controls_mbedit);
	if (!ip->button_next_buffer)
		ip->button_next_buffer = mbedit_window_mbedit_button_next_buffer_create(ip, ip->controls_mbedit);
	if (!ip->button_done)
		ip->button_done = mbedit_window_mbedit_button_done_create(ip, ip->controls_mbedit);
	if (!ip->slider_number_pings)
		ip->slider_number_pings = mbedit_window_mbedit_slider_number_pings_create(ip, ip->controls_mbedit);
	if (!ip->slider_buffer_size)
		ip->slider_buffer_size = mbedit_window_mbedit_slider_buffer_size_create(ip, ip->controls_mbedit);
	if (!ip->button_forward)
		ip->button_forward = mbedit_window_mbedit_button_forward_create(ip, ip->controls_mbedit);
	if (!ip->button_reverse)
		ip->button_reverse = mbedit_window_mbedit_button_reverse_create(ip, ip->controls_mbedit);
	if (!ip->textfield_number_step)
		ip->textfield_number_step = mbedit_window_mbedit_textfield_number_step_create(ip, ip->controls_mbedit);
	if (!ip->slider_buffer_hold)
		ip->slider_buffer_hold = mbedit_window_mbedit_slider_buffer_hold_create(ip, ip->controls_mbedit);
	if (!ip->setting_mode)
		ip->setting_mode = mbedit_window_mbedit_setting_mode_create(ip, ip->controls_mbedit);
	if (!ip->button_goto)
		ip->button_goto = mbedit_window_mbedit_button_goto_create(ip, ip->controls_mbedit);
	if (!ip->canvas_mbedit)
		ip->canvas_mbedit = mbedit_window_mbedit_canvas_mbedit_create(ip, ip->window_mbedit);
	return ip;
}

/*
 * Create object `window_mbedit' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_window_mbedit_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 897,
		XV_HEIGHT, 764,
		XV_LABEL, "MBEDIT Version $Id: mbedit_ui.c,v 4.1 1994-10-21 12:00:33 caress Exp $",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls_mbedit' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_controls_mbedit_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 134,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `button_file' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_button_file_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_LABEL_STRING, "File",
		PANEL_ITEM_MENU, mbedit_menu_file_create((caddr_t) ip, ip->window_mbedit),
		NULL);
	return obj;
}

/*
 * Create object `button_quit' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_button_quit_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		do_quit();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Quit",
		PANEL_NOTIFY_PROC, do_quit,
		NULL);
	return obj;
}

/*
 * Create object `slider_scale_x' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_slider_scale_x_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		set_scale_x();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 8,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_TICKS, 0,
		PANEL_LABEL_STRING, "X Scale (m/100 pixels):",
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 1,
		PANEL_MAX_VALUE, 50000,
		PANEL_VALUE, 1000,
		PANEL_NOTIFY_PROC, set_scale_x,
		NULL);
	return obj;
}

/*
 * Create object `textfield_x_interval' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_textfield_x_interval_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	do_x_interval();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 616,
		XV_Y, 8,
		PANEL_VALUE_DISPLAY_LENGTH, 5,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "X Axis Tick Interval (m):",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, do_x_interval,
		NULL);
	return obj;
}

/*
 * Create object `slider_scale_y' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_slider_scale_y_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		set_scale_y();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 32,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_TICKS, 0,
		PANEL_LABEL_STRING, "Vertical Exageration (X 0.01):",
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 1,
		PANEL_MAX_VALUE, 5000,
		PANEL_VALUE, 100,
		PANEL_NOTIFY_PROC, set_scale_y,
		NULL);
	return obj;
}

/*
 * Create object `textfield_y_interval' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_textfield_y_interval_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	do_y_interval();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 616,
		XV_Y, 32,
		PANEL_VALUE_DISPLAY_LENGTH, 5,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Y Axis Tick Interval (m):",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 100,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, do_y_interval,
		NULL);
	return obj;
}

/*
 * Create object `button_next_buffer' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_button_next_buffer_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		do_next_buffer();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Next Buffer",
		PANEL_NOTIFY_PROC, do_next_buffer,
		NULL);
	return obj;
}

/*
 * Create object `button_done' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_button_done_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		do_done();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 104,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Done",
		PANEL_NOTIFY_PROC, do_done,
		NULL);
	return obj;
}

/*
 * Create object `slider_number_pings' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_slider_number_pings_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		set_number_pings();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 56,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_TICKS, 0,
		PANEL_LABEL_STRING, "Number of pings shown:",
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 1,
		PANEL_MAX_VALUE, 20,
		PANEL_VALUE, 10,
		PANEL_NOTIFY_PROC, set_number_pings,
		NULL);
	return obj;
}

/*
 * Create object `slider_buffer_size' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_slider_buffer_size_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		do_buffer_size();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 552,
		XV_Y, 56,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_TICKS, 0,
		PANEL_LABEL_STRING, "Data Buffer Size:   ",
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 100,
		PANEL_VALUE, 0,
		PANEL_NOTIFY_PROC, do_buffer_size,
		NULL);
	return obj;
}

/*
 * Create object `button_forward' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_button_forward_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		do_forward();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 72,
		PANEL_LABEL_STRING, "Forward",
		PANEL_NOTIFY_PROC, do_forward,
		NULL);
	return obj;
}

/*
 * Create object `button_reverse' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_button_reverse_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		do_reverse();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 88,
		XV_Y, 72,
		PANEL_LABEL_STRING, "Reverse",
		PANEL_NOTIFY_PROC, do_reverse,
		NULL);
	return obj;
}

/*
 * Create object `textfield_number_step' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_textfield_number_step_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	set_number_step();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 80,
		PANEL_VALUE_DISPLAY_LENGTH, 3,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Number of pings to step:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 20,
		PANEL_MIN_VALUE, 1,
		PANEL_VALUE, 5,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, set_number_step,
		NULL);
	return obj;
}

/*
 * Create object `slider_buffer_hold' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_slider_buffer_hold_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		do_buffer_hold();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 552,
		XV_Y, 80,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_TICKS, 0,
		PANEL_LABEL_STRING, "Buffer Retain Size:",
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 100,
		PANEL_VALUE, 0,
		PANEL_NOTIFY_PROC, do_buffer_hold,
		NULL);
	return obj;
}

/*
 * Create object `setting_mode' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_setting_mode_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		mbedit_window_mbedit_setting_mode_notify_callback();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 104,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Mode:",
		PANEL_NOTIFY_PROC, mbedit_window_mbedit_setting_mode_notify_callback,
		PANEL_CHOICE_STRINGS,
			"Pick",
			"Erase",
			"Restore",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `button_goto' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_button_goto_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern void		mbedit_window_mbedit_button_goto_notify_callback();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 272,
		XV_Y, 104,
		PANEL_LABEL_STRING, "Go To",
		PANEL_NOTIFY_PROC, mbedit_window_mbedit_button_goto_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `canvas_mbedit' in the specified instance.
 */
Xv_opaque
mbedit_window_mbedit_canvas_mbedit_create(ip, owner)
	mbedit_window_mbedit_objects	*ip;
	Xv_opaque	owner;
{
	extern Notify_value	do_event();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, (int)xv_get(ip->controls_mbedit, XV_Y) +
		      (int)xv_get(ip->controls_mbedit, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	xv_set(canvas_paint_window(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_MOVE,
		LOC_DRAG,
		LOC_WINENTER,
		LOC_WINEXIT,
		WIN_ASCII_EVENTS,
		WIN_LEFT_KEYS,
		WIN_RIGHT_KEYS,
		WIN_TOP_KEYS,
		NULL, NULL);
	notify_interpose_event_func(canvas_paint_window(obj),
		(Notify_func) do_event, NOTIFY_SAFE);
	/*
	 * This line is here for backwards compatibility. It will be
	 * removed for the next release.
	 */
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

/*
 * Initialize an instance of object `popup_load'.
 */
mbedit_popup_load_objects *
mbedit_popup_load_objects_initialize(ip, owner)
	mbedit_popup_load_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (mbedit_popup_load_objects *) calloc(1, sizeof (mbedit_popup_load_objects))))
		return (mbedit_popup_load_objects *) NULL;
	if (!ip->popup_load)
		ip->popup_load = mbedit_popup_load_popup_load_create(ip, owner);
	if (!ip->controls_load)
		ip->controls_load = mbedit_popup_load_controls_load_create(ip, ip->popup_load);
	if (!ip->list_files)
		ip->list_files = mbedit_popup_load_list_files_create(ip, ip->controls_load);
	if (!ip->textfield_format)
		ip->textfield_format = mbedit_popup_load_textfield_format_create(ip, ip->controls_load);
	if (!ip->textfield_output)
		ip->textfield_output = mbedit_popup_load_textfield_output_create(ip, ip->controls_load);
	if (!ip->button_load_cancel)
		ip->button_load_cancel = mbedit_popup_load_button_load_cancel_create(ip, ip->controls_load);
	if (!ip->button_load_ok)
		ip->button_load_ok = mbedit_popup_load_button_load_ok_create(ip, ip->controls_load);
	return ip;
}

/*
 * Create object `popup_load' in the specified instance.
 */
Xv_opaque
mbedit_popup_load_popup_load_create(ip, owner)
	mbedit_popup_load_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 267,
		XV_HEIGHT, 375,
		XV_LABEL, "Load Input Multibeam File",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls_load' in the specified instance.
 */
Xv_opaque
mbedit_popup_load_controls_load_create(ip, owner)
	mbedit_popup_load_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `list_files' in the specified instance.
 */
Xv_opaque
mbedit_popup_load_list_files_create(ip, owner)
	mbedit_popup_load_objects	*ip;
	Xv_opaque	owner;
{
	extern int		set_output_name();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 16,
		PANEL_LIST_WIDTH, 220,
		PANEL_LIST_DISPLAY_ROWS, 10,
		PANEL_LIST_TITLE, "Set Input Multibeam File:",
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		PANEL_NOTIFY_PROC, set_output_name,
		NULL);
	return obj;
}

/*
 * Create object `textfield_format' in the specified instance.
 */
Xv_opaque
mbedit_popup_load_textfield_format_create(ip, owner)
	mbedit_popup_load_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 256,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "MBIO Format ID:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 20,
		PANEL_MIN_VALUE, 1,
		PANEL_VALUE, 1,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `textfield_output' in the specified instance.
 */
Xv_opaque
mbedit_popup_load_textfield_output_create(ip, owner)
	mbedit_popup_load_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 280,
		PANEL_VALUE_DISPLAY_LENGTH, 29,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Output File:",
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `button_load_cancel' in the specified instance.
 */
Xv_opaque
mbedit_popup_load_button_load_cancel_create(ip, owner)
	mbedit_popup_load_objects	*ip;
	Xv_opaque	owner;
{
	extern void		do_load_cancel();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 32,
		XV_Y, 336,
		PANEL_LABEL_STRING, "Cancel",
		PANEL_NOTIFY_PROC, do_load_cancel,
		NULL);
	return obj;
}

/*
 * Create object `button_load_ok' in the specified instance.
 */
Xv_opaque
mbedit_popup_load_button_load_ok_create(ip, owner)
	mbedit_popup_load_objects	*ip;
	Xv_opaque	owner;
{
	extern void		do_load_ok();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 192,
		XV_Y, 336,
		PANEL_LABEL_STRING, "OK",
		PANEL_NOTIFY_PROC, do_load_ok,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `popup_goto'.
 */
mbedit_popup_goto_objects *
mbedit_popup_goto_objects_initialize(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (mbedit_popup_goto_objects *) calloc(1, sizeof (mbedit_popup_goto_objects))))
		return (mbedit_popup_goto_objects *) NULL;
	if (!ip->popup_goto)
		ip->popup_goto = mbedit_popup_goto_popup_goto_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = mbedit_popup_goto_controls1_create(ip, ip->popup_goto);
	if (!ip->textfield_year)
		ip->textfield_year = mbedit_popup_goto_textfield_year_create(ip, ip->controls1);
	if (!ip->textfield_month)
		ip->textfield_month = mbedit_popup_goto_textfield_month_create(ip, ip->controls1);
	if (!ip->textfield_day)
		ip->textfield_day = mbedit_popup_goto_textfield_day_create(ip, ip->controls1);
	if (!ip->textfield_hour)
		ip->textfield_hour = mbedit_popup_goto_textfield_hour_create(ip, ip->controls1);
	if (!ip->textfield_minute)
		ip->textfield_minute = mbedit_popup_goto_textfield_minute_create(ip, ip->controls1);
	if (!ip->textfield_second)
		ip->textfield_second = mbedit_popup_goto_textfield_second_create(ip, ip->controls1);
	if (!ip->button_goto_apply)
		ip->button_goto_apply = mbedit_popup_goto_button_goto_apply_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `popup_goto' in the specified instance.
 */
Xv_opaque
mbedit_popup_goto_popup_goto_create(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 179,
		XV_HEIGHT, 220,
		XV_LABEL, "Great Leap Forward?",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
mbedit_popup_goto_controls1_create(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `textfield_year' in the specified instance.
 */
Xv_opaque
mbedit_popup_goto_textfield_year_create(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 24,
		PANEL_VALUE_DISPLAY_LENGTH, 4,
		PANEL_VALUE_STORED_LENGTH, 4,
		PANEL_LABEL_STRING, "Year:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 2062,
		PANEL_MIN_VALUE, 1962,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `textfield_month' in the specified instance.
 */
Xv_opaque
mbedit_popup_goto_textfield_month_create(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 48,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 2,
		PANEL_LABEL_STRING, "Month:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 12,
		PANEL_MIN_VALUE, 1,
		PANEL_VALUE, 2,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `textfield_day' in the specified instance.
 */
Xv_opaque
mbedit_popup_goto_textfield_day_create(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 72,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 2,
		PANEL_LABEL_STRING, "Day:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 31,
		PANEL_MIN_VALUE, 1,
		PANEL_VALUE, 21,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `textfield_hour' in the specified instance.
 */
Xv_opaque
mbedit_popup_goto_textfield_hour_create(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 96,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 2,
		PANEL_LABEL_STRING, "Hour:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 23,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `textfield_minute' in the specified instance.
 */
Xv_opaque
mbedit_popup_goto_textfield_minute_create(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 120,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 2,
		PANEL_LABEL_STRING, "Minute:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 59,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `textfield_second' in the specified instance.
 */
Xv_opaque
mbedit_popup_goto_textfield_second_create(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 144,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 2,
		PANEL_LABEL_STRING, "Second:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 59,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `button_goto_apply' in the specified instance.
 */
Xv_opaque
mbedit_popup_goto_button_goto_apply_create(ip, owner)
	mbedit_popup_goto_objects	*ip;
	Xv_opaque	owner;
{
	extern void		mbedit_popup_goto_button_goto_apply_notify_callback();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 56,
		XV_Y, 176,
		PANEL_LABEL_STRING, "Apply",
		PANEL_NOTIFY_PROC, mbedit_popup_goto_button_goto_apply_notify_callback,
		NULL);
	return obj;
}

