.TH MBGRD2GLTF 1 "17 April, 2024" "MB-System version 5.8" "MB-System User Commands"
.SH NAME
mbgrd2gltf \- convert bathymetric grid data to GLTF format with optional settings, including Draco compression.

.SH SYNOPSIS
.B mbgrd2gltf
.I <filepath>
[\fB\-b\fR | \-\-binary]
[\fB\-o\fR | \-\-output
.I <output filepath>]
[\fB\-e\fR | \-\-exaggeration
.I <vertical exaggeration>]
[\fB\-m\fR | \-\-max-size
.I <max size>]
[\fB\-s\fR | \-\-stride
.I <stride ratio>]
[\fB\-d\fR | \-\-draco]
[\fB\-qp\fR | \fB\-qn\fR | \fB\-qt\fR | \fB\-qc\fR
.I <quantization numbers>]
[\fB\-h\fR | \-\-help]

.SH DESCRIPTION
.B mbgrd2gltf
is a tool designed to convert grid data files (GRD) to Graphics Library Transmission Format (GLTF) files. It can generate output in: a binary to create a more compact GLTF file, exaggerate vertex altitude to enhance topographic features, and cap the max-size of the GLTF so the output files don't exceed size constraints. Furthermore, optional Draco compression can reduce the outputed GLTF file size even more while maintaining good visual quality. With Draco, one can specify the quantization level, which affects the compression level of mesh vertices.

.SH MB-SYSTEM AUTHORSHIP
David W. Caress - Monterey Bay Aquarium Research Institute
.br
Dale N. Chayes - Center for Coastal and Ocean Mapping, University of New Hampshire
.br
Christian dos Santos Ferreira - MARUM, University of Bremen

.SH OPTIONS
.TP
.B <filepath> :
Specify the path to the input GMT GRD file.

.TP
.B \-b, \-\-binary :
Generate the output in binary GLTF format. Binary GLTF is more compact and typically loads faster in applications.

.TP
.B \-o, \-\-output :
Specify the path to the folder where the output GLTF file will be written.

.TP
.B \-e, \-\-exaggeration :
Specify the vertical exaggeration factor as a decimal number, which multiplies the vertex altitudes. This can enhance the visibility of topographic features.

.TP
.B \-m, \-\-max-size :
Specify the maximum size of the output buffer data in megabytes. This is useful for ensuring that the output files do not exceed certain size constraints. Actual size may vary based on compression settings.

.TP
.B \-s, \-\-stride :
Specify the decimal number representing the the amount of stride('Skip') to apply to the buffer data of the output as a ratio of normal to running. As you stride, you skip over portions of data.
The bigger the stride, the more points are skipped.

.TP
.B \-d, \-\-draco :
Enable Draco compression to reduce the file size by encoding meshes and point clouds.

.TP
.B \-qp | -qn | -qt | -qc :
Specify the quantization level for Draco compression. Positional quantization (-qp) value affects the compression level of mesh vertices. Lower values increase compression but reduce precision, potentially affecting the visual quality of the terrain. Other quantization values are available
for experimentation. They include -qn: Normal, -qt: TexCoord, -qc: Color. The default quantization value is 16 for position, 7 for normal, 10 for texcoord, 8 for color.

.TP
.B \-h, \-\-help :
Display help message and exit. Provides more information on command usage and options.

.SH EXAMPLES
Convert a GMT GRD file to a GLTF file with default settings:
.RS
.nf
.B mbgrd2gltf input.grd
.fi
.RE

Convert a GRD file to GLB(Binary GLTF) with specified output folder and Draco compression at a quantization level of 20:
.RS
.nf
.B mbgrd2gltf input.grd --binary --output /path/to/output --draco -qp 20
.fi
.RE

Converting a large GRD file to GLB(Binary GLTF) with specified output folder and Draco compression at a quantization level of 20 with a vertical exaggeration of 20. [ All options in short-hand notiation. ]
.RS
.nf
.B mbgrd2gltf input.grd -o /path/to/output -d -b -qp 20 -e 20
.fi
.nf
Auto setting stride to 1. [ Program generated output. ]
.RE

.SH "SEE ALSO"
.B mbinfo(1),
.B mbprocess(1),
.B mblist(1)

.SH BUGS
Please report any bugs on the MB-System GitHub Issue Tracker.
