.TH mbimagelist 1 "31 March 2025" "MB-System 5.0" "MB-System 5.0"
.SH NAME
\fBmbimagelist\fP \- parses recursive imagelist structures, performing one or more
tasks on the image files referenced in the imagelist(s). The default action is to
print out out the complete list of image file paths; other
possible tasks include also printing out associated timestamps and camera settings, and
printing out processing parameter values embedded in the imagelist structure.

.SH VERSION
Version 5.0

.SH SYNOPSIS
\fBmbimagelist\fP
.br
[
.br
\fB--absolutepaths\fP   {\fB-A\fP}
.br
\fB--copy\fP=\fIdirectory\fP   {\fB-C\fP\fIdirectory\fP}
.br
\fB--copyhere\fP
.br
\fB--files\fP   {\fB-F\fP}
.br
\fB--help\fP   {\fB-H\fP}
.br
\fB--input\fP=\fIfile\fP   {\fB-I\fP\fIfile\fP}
.br
\fB--left\fP   {\fB-L\fP}
.br
\fB--parameters\fP   {\fB-P\fP}
.br
\fB--right\fP   {\fB-R\fP}
.br
\fB--settings\fP   {\fB-S\fP}
.br
\fB--single\fP
.br
\fB--verbose\fP   {\fB-V\fP}
.br
]

.SH DESCRIPTION
\fBMBimagelist\fP is a utility for parsing imagelist files.
Imagelist files, or lists of seafloor photographic images,
are used by a number of \fBMB-System\fP programs dealing with
seafloor photography. These lists may contain references
to other imagelists, making them recursive. 
By default, the program \fBmbimagelist\fP outputs each
image filename encountered as it parses through the input imagelist tree. The output
paths can be relative to the current working directory or absolute. 

Imagelist files can also contain processing parameters associated with the images, including 
specifying a file containing the calibration parameters for the camera rig, specifying
a file containing the trajectory (navigation and attitude) of the camera rig as images
were collected, specifying a file with an image correction lookup table, and several other
parameters. All of these parameters correspond to command line options for \fBmbphotomosaic\fP 
that can also be specified.

This program
can be used in shellscripts to read imagelists in the same fashion
as \fBMB-System\fP programs like \fBmbphotomosaic\fP and \fBmbphotocorrect\fP.
This program can also be used to check and debug complex recursive
imagelist structures.


.SH MB-SYSTEM AUTHORSHIP
David W. Caress
.br
  Monterey Bay Aquarium Research Institute
.br
Dale N. Chayes
.br
  Center for Coastal and Ocean Mapping
.br
  University of New Hampshire
.br
Christian do Santos Ferreira
.br
  MARUM - Center for Marine Environmental Sciences
.br
  University of Bremen

.SH OPTIONS
.TP
.B \-\-absolutepaths   {\fB\-A\fP}
.br
Causes the image file paths in the output to be converted to absolute
paths (by prepending the current working directory to any relative
path) rather than being output as they appear in the imagelist.
Default: paths are output exactly as they appear in the imagelist.
.TP
.B \-\-copy=\fIdirectory\fP   {\fB\-C\fP\fIdirectory\fP}
.br
Causes each image file listed in the output to also be copied
(using the shell \fBcp\fP command) into \fIdirectory\fP.
.TP
.B \-\-copyhere
.br
Equivalent to \fB\-\-copy\fP, except that the destination directory is
the current working directory rather than one specified by the user.
.TP
.B \-\-files   {\fB\-F\fP}
.br
Requests that the plain image file paths be listed, one per line. This
is the default output mode when neither \fB\-\-parameters\fP nor
\fB\-\-settings\fP is specified.
.TP
.B \-\-help   {\fB\-H\fP}
This "help" flag cause the program to print out a description
of its operation and then exit immediately.
.TP
.B \-\-input=\fIfile\fP   {\fB\-I\fP\fIfile\fP}
.br
Sets the filename of the imagelist to be parsed. Imagelists are
recursive, and may reference other imagelists as well as individual
image files. Default: \fIfile\fP = "imagelist.mb-2".
.TP
.B \-\-left   {\fB\-L\fP}
.br
Sets the image selection to left-camera images. This option is
reserved for future use; the current release of \fBmbimagelist\fP
lists every image referenced in the imagelist regardless of this
setting.
.TP
.B \-\-parameters   {\fB\-P\fP}
.br
Causes a line to be printed for each processing parameter entry
encountered while parsing the imagelist, in addition to (or instead
of, if \fB\-\-files\fP and \fB\-\-settings\fP are not also given) the
image file listing. Default: parameter entries are not reported.
.TP
.B \-\-right   {\fB\-R\fP}
.br
Sets the image selection to right-camera images. This option is
reserved for future use; the current release of \fBmbimagelist\fP
lists every image referenced in the imagelist regardless of this
setting.
.TP
.B \-\-settings   {\fB\-S\fP}
.br
Causes each image line in the output to include the image timestamp,
gain, and exposure values, in addition to the file path. Default:
only the file path is printed.
.TP
.B \-\-single
.br
Sets the image selection to single-camera (non-stereo) images. This
option is reserved for future use; the current release of
\fBmbimagelist\fP lists every image referenced in the imagelist
regardless of this setting. There is no short option equivalent.
.TP
.B \-\-verbose   {\fB\-V\fP}
.br
Increases the verbosity of \fBmbimagelist\fP. Can be used multiple
times. If used at all, a summary of the numbers of left, right,
single, and total images listed is printed at the end of execution.

.SH EXAMPLES
Suppose we have two swath data files from an EM3000 multibeam
and another two from an Hydrosweep MD multibeam. We might
construct two imagelist files. For the EM3000 we might
have a file imagelist_em3000.mb-1 containing:
 	0004_20010705_165004_raw.mb57 57
 	0005_20010705_172010_raw.mb57 57
.br
For the Hydrosweep MD data we might have a file imagelist_hsmd.mb-1
containing:
 	al10107051649.mb102 102
 	al10107051719.mb102 102

Further suppose that we have found it necessary to edit
the bathymetry in 0005_20010705_172010_raw.mb57 and
al10107051719.mb102 using \fBmbedit\fP, and that \fBmbprocess\fP
has been run on both files to generate processed files
called 0005_20010705_172010_rawp.mb57 and
al10107051719p.mb102.

If we run:
 	mbimagelist --input=imagelist_em3000.mb-1
.br
the output is:
 	0004_20010705_165004_raw.mb57 57 1.000000
 	0005_20010705_172010_raw.mb57 57 1.000000
.br
Here the file name is followed by the format and then
by a third column containing the default file weight of 1.0.

Similarly, if we run:
 	mbimagelist --input=imagelist_hsmd.mb-1
.br
the output is:
 	al10107051649.mb102 102 1.000000
 	al10107051719.mb102 102 1.000000

If we insert a line
 	$PROCESSED
.br
at the top of both imagelist_hsmd.mb-1 and imagelist_em3000.mb-1,
then the output of \fBmbimagelist\fP changes so that:
 	mbimagelist --input=imagelist_em3000.mb-1
.br
yields:
 	0004_20010705_165004_raw.mb57 57 1.000000
 	0005_20010705_172010_rawp.mb57 57 1.000000
and:
 	mbimagelist --input=imagelist_hsmd.mb-1
.br
yields:
 	al10107051649.mb102 102 1.000000
 	al10107051719p.mb102 102 1.000000

Now suppose we create a imagelist file called imagelist_all.mb-1
that refers to the two imagelists shown above (without the
$PROCESSED tags). If the contents of imagelist_all.mb-1 are:
 	imagelist_em3000.mb-1 \-1 100.0
 	imagelist_hsmd.mb-1   \-1   1.0
.br
where we have specified different file weights for the
two imagelists, then:
 	mbimagelist --input=imagelist_all.mb-1
.br
yields:
 	0004_20010705_165004_raw.mb57 57 100.000000
 	0005_20010705_172010_raw.mb57 57 100.000000
 	al10107051649.mb102 102 1.000000
 	al10107051719.mb102 102 1.000000


.SH SEE ALSO
\fBmbsystem\fP(1)

.SH BUGS
No true bugs here, only distantly related arthropods... Yum.
Seriously, it would be better if the copy function preserved
the modification times of the copied swath files and ancillary
files. Copying of processed files should also be an option.
