.TH mbpreprocess 1 "6 June 2018" "MB-System 5.0" "MB-System 5.0"
.SH NAME
\fBmbpreprocess\fP \- performs preprocessing of swath sonar data as part of setting
up an MB-System processing structure for a dataset.

.SH VERSION
Version 5.0

.SH SYNOPSIS
\fBmbpreprocess\fP [ 
.br
\fB--verbose\fP
\fB--help\fP
\fB--input\fP=\fIFILE\fP
\fB--format\fP=\fIFORMATID\fP
.br
\fB--platform-file\fP=\fIFILE\fP
\fB--platform-target-sensor\fP=\fIRECORDID\fP
.br
\fB--output-sensor-fnv\fP
.br
\fB--nav-file\fP=\fIFILE\fP
\fB--nav-file-format\fP=\fIFORMATID\fP
\fB--nav-async\fP=\fIRECORDTYPE\fP
\fB--nav-sensor\fP=\fISENSORID\fP
.br
\fB--sensordepth-file\fP=\fIFILE\fP
\fB--sensordepth-file-format\fP=\fIFORMATID\fP
\fB--sensordepth-async\fP=\fIRECORDTYPE\fP
\fB--sensordepth-sensor\fP=\fISENSORID\fP
.br
\fB--heading-file\fP=\fIFILE\fP
\fB--heading-file-format\fP=\fIFORMATID\fP
\fB--heading-async\fP=\fIRECORDTYPE\fP
\fB--heading-sensor\fP=\fISENSORID\fP
.br
\fB--altitude-file\fP=\fIFILE\fP
\fB--altitude-file-format\fP=\fIFORMATID\fP
\fB--altitude-async\fP=\fIRECORDTYPE\fP
\fB--altitude-sensor\fP=\fISENSORID\fP
.br
\fB--attitude-file\fP=\fIFILE\fP
\fB--attitude-file-format\fP=\fIFORMATID\fP
\fB--attitude-async\fP=\fIRECORDTYPE\fP
\fB--attitude-sensor\fP=\fISENSORID\fP
.br
\fB--soundspeed-file\fP=\fIFILE\fP
\fB--soundspeed-file-format\fP=\fIFORMATID\fP
\fB--soundspeed-async\fP=\fIRECORDTYPE\fP
\fB--soundspeed-sensor\fP=\fISENSORID\fP
.br
\fB--time-latency-file\fP=\fIFILE\fP
\fB--time-latency-file-format\fP=\fIFORMATID\fP
\fB--time-latency-constant\fP=\fISECONDS\fP
.br
\fB--time-latency-apply-nav\fP
\fB--time-latency-apply-sensordepth\fP
\fB--time-latency-apply-heading\fP
.br
\fB--time-latency-apply-attitude\fP
\fB--time-latency-apply-altitude\fP
\fB--time-latency-apply-all-ancilliary\fP
.br
\fB--time-latency-apply-survey\fP
\fB--time-latency-apply-all\fP
.br
\fB--filter\fP=\fISECONDS\fP
.br
\fB--filter-apply-nav\fP
\fB--filter-apply-sensordepth\fP
\fB--filter-apply-heading\fP
.br
\fB--filter-apply-attitude\fP
\fB--filter-apply-altitude\fP
\fB--filter-apply-all-ancilliary\fP
.br
\fB--recalculate-bathymetry\fP
\fB--no-change-survey\fP
\fB--multibeam-sidescan-source\fP=\fIRECORDID\fP
\fB--sounding-amplitude-filter\fP=\fITHRESHOLD\fP
.br
\fB--kluge-time-jumps\fP=\fISECONDS\fP
\fB--kluge-ancilliary-time-jumps\fP=\fISECONDS\fP
\fB--kluge-mbaripressure-time-jumps\fP=\fIthreshold
\fB--kluge-beam-tweak\fP=\fIFACTOR\fP
\fB--kluge-soundspeed-tweak\fP=\fIfactor\fP
\fB--kluge-zero-attitude-correction\fP
\fB--kluge-zero-alongtrack-angles\fP
\fB--kluge-fix-wissl-timestamps\fP
.br
]

.SH DESCRIPTION
MBpreprocess handles preprocessing of swath sonar data as part of setting
up an MB-System processing structure for a dataset. This program replaces
the several format-specific preprocessing programs
found in MB-System version 5 releases with a single program for version 6.
In many cases the preprocessing consists only of creating the ancilliary files
parallel to the raw files, but in others the data must be translated to
different formats. The proprocessing step can also be used to merge navigation,
attitude, sound speed, or other ancilliary data with the survey data.

.SH MB-SYSTEM AUTHORSHIP
David W. Caress
.br
  Monterey Bay Aquarium Research Institute
.br
Dale N. Chayes
.br
  Center for Coastal and Ocean Mapping
.br
  University of New Hampshire
.br
Christian do Santos Ferreira
.br
  MARUM - Center for Marine Environmental Sciences
.br
  University of Bremen

.SH OPTIONS
.TP
.B --help
This option causes \fBmbconfig\fP to print out its usage options and exit.
.TP
.B --verbose
By default \fBmbpreprocess\fP outputs minimal information to the shell. This option
causes the program to indicate it's progress as it runs.

.TP
.B --input=\fIFILE\fP
Swath data file from which the input data will be read, or a datalist file
containing a list of input swath data files and/or other datalist files.
If \fIFILE\fP is a datalist file, then mbpreprocess will attempt to preprocess
all data files identified by recursively reading the datalist structure
referenced in \fIFILE\fP.
.TP
.B --format=\fIFORMATID\fP
Sets the \fBMBIO\fP integer format identifier
for the input file \fIFILE\fP specified with the
\fB\--input\fP option. By default, \fBmbpreprocess\fP
infers the format from the "*.mbXX" \fBMB\-System\fP suffix
convention.
.TP
.B --platform-file=\fIFILE\fP
.TP
.B --platform-target-sensor=\fISENSORID\fP
.TP
.B --output-sensor-fnv
Causes \fBmbpreprocess\fP to output "fast navigation" or *.fnv files for each
of the sensors described in the platform file specified with the \fB--platform-file\fP
option. These *.fnv files will be corrected for the lever arms specified by the
positional and angular offsets defined in the platform file.
.TP
.B --skip-existing
.br
.TP
.B \-\-nav-file\fP=\fIfilename\fP
.br
Specifies an external file from which to merge sonar position (navigation),
replacing any navigation data included in the input time series sidescan files.
By default \fBmbsslayout\fP attempts to use navigation values included in the
input data.
.TP
.B \-\-nav-file-format\fP=\fIformat_id\fP
.br
Specifies the format of an external navigation file from which position values
are derived (as defined with \fB\-\-nav-file\fP). Options for the \fIformat_id\fP
value are:
.br
   1: ASCCI text file with lines of the form:
        time_d longitude latitude speed
      where time_d is time in decimal epoch seconds (seconds since 1970), longitude
      and latitude are in decimal degrees, and speed is in km/hour (and is optional).
      South latitudes are negative. Longitude may be defined on either the
      -180.0 to +180.0 or 0.0 to 360.0 domains.
.br
   2: ASCCI text file with lines of the form:
        year month day hour minute second longitude latitude
      where year, month, day, hour, and minute values are integers, the second
      value is decimal, and longitude and latitude are in decimal degrees.
      South latitudes are negative. Longitude may be defined on either the
      -180.0 to +180.0 or 0.0 to 360.0 domains.
.br
   3: ASCCI text file with lines of the form:
        year julian_day hour minute second longitude latitude
      where year, julian_day, hour, and minute values are integers, the second
      value is decimal, and longitude and latitude are in decimal degrees.
      South latitudes are negative. Longitude may be defined on either the
      -180.0 to +180.0 or 0.0 to 360.0 domains.
.br
   4: ASCCI text file with lines of the form:
        year julian_day day_minute second longitude latitude
      where year, julian_day, and day_minute values are integers, the second
      value is decimal, and longitude and latitude are in decimal degrees.
      South latitudes are negative. Longitude may be defined on either the
      -180.0 to +180.0 or 0.0 to 360.0 domains.
.br
   5: ASCCI text file in the 1990's era L-DEO processed nav format with lines
      of the form:
        yy+jjjhhmmssNddmmmmmmEdddmmmmmm
      where yy is the two digit year (after 1999 the "yy+" was replaced by a four
      digit year "yyyy"), jjj is the julian_day, hh is the hour, mm
      is minutes, and ss is seconds. The latitude is given as
      Nddmmmmmmand where N is 'N' for north and 'S' for south, dd are integer
      degrees, and mmmmmm is minutes * 10000. The longitude is given as
      Edddmmmmmmand where E is 'E' for east and 'W' for west, ddd are integer
      degrees, and mmmmmm is minutes * 10000.
.br
   6 or 7: NMEA 0183 position strings
      Several NMEA and NMEA-like strings containing position are recognized,
      and can be parsed with and without line break characters. These strings
      include ZDA, GLL, GGA, DAT, and UNX.
.br
   8: Simrad 90 format navigation files with lines
      of the form:
        ddmmyy hhmmssss ddmmmmmmmN dddmmmmmmmE
      where dd is day of the month, mm is the month, yy is the two digit year,
      hh is the hour, mm is the minute, and ssss is seconds * 100.
      The latitude is given as ddmmmmmmmN where dd are integer degrees, 
      mmmmmmm is minutes * 100000, and N is 'N' for north and 'S' for south latitude.
      The longitude is given as dddmmmmmmmE where ddd are integer degrees, 
      mmmmmmm is minutes * 100000, and E is 'E' for east and 'W' for west longitude.
      
      
      day_minute values are integers,
      the second value is decimal, and longitude and latitude are in decimal
      degrees. The longitude is given as
      Edddmmmmmmand where E is 'E' for east and 'W' for west, ddd are integer
      degrees, and mmmmm is minutes * 10000.
.br
   9: ASCCI text file with white-space delimited lines of the form:
        yr mon day hour min sec time_d lon lat heading speed sensordepth*
      where yr is the four digit year, mon is the month, day is the day of the
      month, min is the minute, second is the decimal seconds, time_d is time in
      decimal epoch seconds (seconds since 1970), lon is the longitude
      in decimal degrees, lat is the latitude in decimal degrees, heading is in
      decimal degrees, speed is in km/hour, and sensordepth is in meters.
      South latitudes are negative. Longitude may be defined on either the
      -180.0 to +180.0 or 0.0 to 360.0 domains.
.br
   10: R2R (Rolling deck to Repository) navigation format with ASCCI text lines
      of the form:
         yyyy-mm-ddThh:mm:ss.sssZ lon lat quality nsat dilution height
      where the lon and lat fields are in decimal degrees with south latitudes
      and west longitudes negative, and the last four quantities relating to
      GPS fix quality.
.TP
.B \-\-nav-async\fP=\fIrecord_kind\fP
.br
Specifies the type of data records from which position values
are derived (as defined with \fB\-\-nav-file-format\fP). Options for the
\fIrecord_kind\fP include:
.br
    MB_DATA_DATA:  1 (survey data)
    MB_DATA_NAV:  12 (navigation data)
    MB_DATA_NAV1: 29 (navigation data from navigation system 1)
    MB_DATA_NAV2: 30 (navigation data from navigation system 2)
    MB_DATA_NAV3: 31 (navigation data from navigation system 3)
.br
What types of data records are present is format-dependent, as is the default
choice of which record type is used as the navigation source by default. The
program \fBmbinfo\fP can be used with the \fB-N\fP option to determine the numbers
of different record types present in a data file.
.TP
.B --nav-sensor=\fISENSORID\fP
.br
.TP
.B --sensordepth-file=\fIFILE\fP
.TP
.B --sensordepth-file-format=\fIFORMATID\fP
.TP
.B --sensordepth-async=\fIRECORDTYPE\fP
.TP
.B --sensordepth-sensor=\fISENSORID\fP
.br
.TP
.B --heading-file=\fIFILE\fP
.TP
.B --heading-file-format=\fIFORMATID\fP
.TP
.B --heading-async=\fIRECORDTYPE\fP
.TP
.B --heading-sensor=\fISENSORID\fP
.br
.TP
.B --altitude-file=\fIFILE\fP
.TP
.B --altitude-file-format=\fIFORMATID\fP
.TP
.B --altitude-async=\fIRECORDTYPE\fP
.TP
.B --altitude-sensor=\fISENSORID\fP
.br
.TP
.B --attitude-file=\fIFILE\fP
.TP
.B --attitude-file-format=\fIFORMATID\fP
.TP
.B --attitude-async=\fIRECORDTYPE\fP
.TP
.B --attitude-sensor=\fISENSORID\fP
.br
.TP
.B --soundspeed-file=\fIFILE\fP
.TP
.B --soundspeed-file-format=\fIFORMATID\fP
.TP
.B --soundspeed-async=\fIRECORDTYPE\fP
.TP
.B --soundspeed-sensor=\fISENSORID\fP
.br
.TP
.B --time-latency-file=\fIFILE\fP
.TP
.B --time-latency-file-format=\fIFORMATID\fP
.TP
.B --time-latency-constant=\fISECONDS\fP
.TP
.B --time-latency-apply-nav
.TP
.B --time-latency-apply-sensordepth
.TP
.B --time-latency-apply-heading
.TP
.B --time-latency-apply-attitude
.TP
.B --time-latency-apply-altitude
.TP
.B --time-latency-apply-all-ancilliary
.TP
.B --time-latency-apply-survey
.TP
.B --time-latency-apply-all
.br
.TP
.B --filter=\fISECONDS\fP
.TP
.B --filter-apply-nav
.TP
.B --filter-apply-sensordepth
.TP
.B --filter-apply-heading
.TP
.B --filter-apply-attitude
.TP
.B --filter-apply-altitude
.TP
.B --filter-apply-all-ancilliary
.br
.TP
.B --recalculate-bathymetry
.TP
.B --no-change-survey
.TP
.B --multibeam-sidescan-source=\fIRECORDID\fP
.TP
.B --sounding-amplitude-filter=\fITHRESHOLD\fP
.TP
.B --sounding-amplitude-filter=\fITHRESHOLD\fP
.TP
.B --kluge-time-jumps=\fISECONDS\fP
.TP
.B --kluge-ancilliary-time-jumps=\fISECONDS\fP
.TP
.B --kluge-mbaripressure-time-jumps=\fISECONDS\fP
.TP
.B --kluge-beam-tweak=\fIFACTOR\fP
.TP
.B --kluge-soundspeed-tweak=\fIFACTOR\fP
.TP
.B --kluge-zero-attitude-correction
.TP
.B --kluge-zero-alongtrack-angles
.TP
.B --kluge-fix-wissl-timestamps
.br

.SH EXAMPLES
To be written.....

.SH SEE ALSO
\fBmbsystem\fP(1), \fBmbdatalist\fP(1), \fBmbprocess\fP(1)

.SH BUGS
Oh yeah.
