.TH mbpreprocess 1 "14 March 2014" "MB-System 5.0" "MB-System 5.0"
.SH NAME
\fBmbpreprocess\fP \- performs preprocessing of swath sonar data as part of setting
up an MB-System processing structure for a dataset.

.SH VERSION
Version 5.0

.SH SYNOPSIS
\fBmbpreprocess\fP [ 
.br
\fB--verbose\fP
.br
\fB--help\fP
.br
\fB--input\fP=\fIFILE\fP
.br
\fB--format\fP=\fIFORMAT\fP
.br
\fB--nav-file\fP=\fIFILE\fP
.br
\fB--nav-file-format\fP=\fIFORMAT\fP
.br
\fB--nav-async\fP=\fIRECORDTYPE\fP
.br
\fB--sensordepth-file\fP=\fIFILE\fP
.br
\fB--sensordepth-file-format\fP=\fIFILE\fP
.br
\fB--sensordepth-async\fP=\fIRECORDTYPE\fP
.br
\fB--heading-file\fP=\fIFILE\fP
.br
\fB--heading-file-format\fP=\fIFORMAT\fP
.br
\fB--heading-async\fP=\fIRECORDTYPE\fP
.br
\fB--attitude-file\fP=\fIFILE\fP
.br
\fB--attitude-file-format\fP=\fIFORMAT\fP
.br
\fB--attitude-async\fP=\fIRECORDTYPE\fP
.br
\fB--timeshift-file\fP=\fIFILE\fP
.br
\fB--timeshift-constant\fP=\fITIME\fP
.br
\fB--timeshift-apply-nav\fP
.br
\fB--timeshift-apply-sensordepth\fP
.br
\fB--timeshift-apply-heading\fP
.br
\fB--timeshift-apply-attitude\fP
.br
\fB--timeshift-apply-all-ancilliary\fP
.br
\fB--timeshift-apply-survey\fP
.br
\fB--timeshift-apply-all\fP
.br
]

.SH DESCRIPTION
MBpreprocess handles preprocessing of swath sonar data as part of setting
up an MB-System processing structure for a dataset. This program replaces
the several format-specific preprocessing programs
found in MB-System version 5 releases with a single program for version 6.
This program is under development, and is not ready for general use at
this time.

.SH AUTHORSHIP
David W. Caress (caress@mbari.org)
.br
  Monterey Bay Aquarium Research Institute
.br
Dale N. Chayes (dale@ldeo.columbia.edu)
.br
  Lamont-Doherty Earth Observatory

.SH OPTIONS
.TP
.B --verbose
By default \fBmbpreprocess\fP outputs minimal information to the shell. This option
causes the program to indicate it's progress as it runs. Goody.

.SH EXAMPLES
To be written.....

.SH SEE ALSO
\fBmbsystem\fP(1), \fBmbdatalist\fP(1), \fBmbprocess\fP(1)

.SH BUGS
Oh yeah.
