.TH mbsslayout 1 "17 September 2017" "MB-System 5.0" "MB-System 5.0"
.SH NAME
\fBmbsslayout\fP \- translates time-based sidescan sonar data into backscatter
layed out onto a topographic model of the seafloor.

.SH VERSION
Version 5.0

.SH SYNOPSIS
\fBmbsslayout\fP [ 
.br
\fB--verbose\fP
.br
\fB--help\fP
.br
 .br
\fB--input\fP=\fIdatalist\fP
.br
\fB--format\fP=\fIformat\fP
.br
 .br
\fB--platform-file\fP=\fIFILE\fP
.br
\fB--platform-target-sensor\fP=\fISENSORID\fP
.br
.br
\fB--output-source\fP=\fIrecord_kind\fP
.br
\fB--output-name1\fP=\fIname\fP
.br
\fB--output-name2\fP=\fIname\fP
.br
 .br
\fB--line-nameroot\fP=\fIname\fP
.br
\fB--line-time-list\fP=\fIfilename\fP
.br
\fB--line-route\fP=\fIfilename\fP
.br
\fB--line-check-bearing\fP
.br
\fB--line-range-threshold\fP=\fIvalue\fP
.br
 .br
\fB--topo-grid-file\fP=\fIfilename\fP
.br
\fB--altitude-altitude\fP
.br
\fB--altitude-bottomppick\fP
.br
\fB--altitude-bottompick-threshold\fP=\fIvalue\fP
.br
\fB--altitude-topo-grid\fP
.br
\fB--channel-swap\fP
.br
\fB--swath-width\fP=\fIvalue\fP
.br
\fB--gain\fP=\fIvalue\fP
.br
\fB--interpolation\fP=\fIvalue\fP
.br
.br
\fB--nav-file\fP=\fIfilename\fP
.br
\fB--nav-file-format\fP=\fIformat_id\fP
.br
\fB--nav-async\fP=\fIrecord_kind\fP
.br
\fB--sensordepth-file\fP=\fIfilename\fP
.br
\fB--sensordepth-file-format\fP=\fIformat_id\fP
.br
\fB--sensordepth-async\fP=\fIrecord_kind\fP
.br
\fB--altitude-file\fP=\fIfilename\fP
.br
\fB--altitude_file-format\fP=\fIformat_id\fP
.br
\fB--altitude-async\fP=\fIrecord_kind\fP
.br
\fB--heading-file\fP=\fIfilename\fP
.br
\fB--heading-file-format\fP=\fIformat_id\fP
.br
\fB--heading-async\fP=\fIrecord_kind\fP
.br
\fB--attitude-file\fP=\fIfilename\fP
.br
\fB--attitude-file-format\fP=\fIformat_id\fP
.br
\fB--attitude-async\fP=\fIrecord_kind\fP
.br
\fB--soundspeed-constant\fP=\fIvalue\fP
.br
\fB--soundspeed-file\fP=\fIfilename\fP
.br
\fB--soundspeed-file-format\fP=\fIformat_id\fP
.br
\fB--soundspeed-async\fP=\fIrecord_kind\fP
.br
\fB--timeshift-file\fP=\fIfilename\fP
.br
\fB--timeshift-constant\fP=\fIvalue\fP
.br
\fB--timeshift-apply-nav\fP
.br
\fB--timeshift-apply-sensordepth\fP
.br
\fB--timeshift-apply-altitude\fP
.br
\fB--timeshift-apply-heading\fP
.br
\fB--timeshift-apply-attitude\fP
.br
\fB--timeshift-apply-all-ancilliary\fP
.br
\fB--timeshift-apply-survey\fP
.br
\fB--timeshift-apply-all\fP
.br
]

.SH DESCRIPTION
MBsslayout translates time-based sidescan sonar data into backscatter
laid out onto a topographic model of the seafloor. The input should be a datalist
referencing data files in a format containing time based sidescan sonar data
(typically both port and starboard time series) without swath
bathymetry data. The output will be sidescan data in the MBF_MBLDEOIH format
(MBIO format id 71). The sidescan can be laid out using a flat bottom assumption,
but is generally laid out onto a gridded topographic model derived from bathymetric
mapping with other sensors. The gridded bathymetry data may be collected
simultaneously with the sidescan from the same platform, or it may derive from
other surveys.

Navigation, attitude, and water sound speed values will by default, if available,
derive from values contained in the time-based sidescan files. If necessary or
desired, the ancilliary values can be merged from separate files. Time latency
corrections can be made to the ancilliary data time series if needed.

Once the sidescan data have been laid out onto the seafloor, they can be further
processed using \fBMB-System\fP tools such as \fBmbbackangle\fP followed by
\fBmbprocess\fP.

.SH MB-SYSTEM AUTHORSHIP
David W. Caress
.br
  Monterey Bay Aquarium Research Institute
.br
Dale N. Chayes
.br
  Center for Coastal and Ocean Mapping
.br
  University of New Hampshire
.br
Christian do Santos Ferreira
.br
  MARUM - Center for Marine Environmental Sciences
.br
  University of Bremen

.SH OPTIONS
.TP
.B --verbose
By default \fBmbsslayout\fP outputs minimal information to the shell. This option
causes the program to indicate it's progress as it runs. Goody.

.SH EXAMPLES
To be written.....

.SH SEE ALSO
\fBmbsystem\fP(1), \fBmbdatalist\fP(1), \fBmbprocess\fP(1)

.SH BUGS
Oh yeah.
