.TH mbmakeplatform 1 "11 June 2016" "MB-System 5.0" "MB-System 5.0"
.SH NAME
\fBmbmakeplatform\fP \- creates or modifies an MB-System platform file.

.SH VERSION
Version 5.0

.SH SYNOPSIS
\fBmbmakeplatform\fP
.br
[
.br
\fB--verbose\fP
.br
\fB--help\fP
.br
\fB--input\fP=\fIplffile\fP
.br
\fB--swath\fP=\fIdatalist\fP
.br
\fB--swath\fP=\fIswathfile\fP
.br
\fB--swath-format\fP=\fIvalue\fP
.br
]
.br
\fB--output\fP=\fIplffile\fP
.br
[
.br
\fB--platform-type-surface-vessel\fP
.br
\fB--platform-type-tow-body\fP
.br
\fB--platform-type-rov\fP
.br
\fB--platform-type-auv\fP
.br
\fB--platform-type-aircraft\fP
.br
\fB--platform-type-satellite\fP
.br
\fB--platform-name\fP=\fIstring\fP
.br
\fB--platform-organization\fP=\fIstring\fP
.br
\fB--platform-documentation-url\fP
.br
\fB--platform-start-time\fP
.br
\fB--platform-end-time\fP
.br
\fB--add-sensor-sonar-echosounder\fP
.br
\fB--add-sensor-sonar-multiechosounder\fP
.br
\fB--add-sensor-sonar-sidescan\fP
.br
\fB--add-sensor-sonar-interferometry\fP
.br
\fB--add-sensor-sonar-multibeam\fP
.br
\fB--add-sensor-sonar-multibeam-twohead\fP
.br
\fB--add-sensor-sonar-subbottom\fP
.br
\fB--add-sensor-camera-mono\fP
.br
\fB--add-sensor-camera-stereo\fP
.br
\fB--add-sensor-camera-video\fP
.br
\fB--add-sensor-lidar-scan\fP
.br
\fB--add-sensor-lidar-swath\fP
.br
\fB--add-sensor-position\fP
.br
\fB--add-sensor-compass\fP
.br
\fB--add-sensor-vru\fP
.br
\fB--add-sensor-imu\fP
.br
\fB--add-sensor-ins\fP
.br
\fB--add-sensor-ins-with-pressure\fP
.br
\fB--add-sensor-ctd\fP
.br
\fB--add-sensor-pressure\fP
.br
\fB--add-sensor-soundspeed\fP
.br
\fB--end-sensor\fP
.br
\fB--sensor-model\fP=\fIstring\fP
.br
\fB--sensor-manufacturer\fP=\fIstring\fP
.br
\fB--sensor-serialnumber\fP=\fIstring\fP
.br
\fB--sensor-capability-position\fP
.br
\fB--sensor-capability-depth\fP
.br
\fB--sensor-capability-altitude\fP
.br
\fB--sensor-capability-velocity\fP
.br
\fB--sensor-capability-acceleration\fP
.br
\fB--sensor-capability-pressure\fP
.br
\fB--sensor-capability-rollpitch\fP
.br
\fB--sensor-capability-heading\fP
.br
\fB--sensor-capability-magneticfield\fP
.br
\fB--sensor-capability-temperature\fP
.br
\fB--sensor-capability-conductivity\fP
.br
\fB--sensor-capability-salinity\fP
.br
\fB--sensor-capability-soundspeed\fP
.br
\fB--sensor-capability-gravity\fP
.br
\fB--sensor-capability-topography-echosounder\fP
.br
\fB--sensor-capability-topography-interferometry\fP
.br
\fB--sensor-capability-topography-sass\fP
.br
\fB--sensor-capability-topography-multibeam\fP
.br
\fB--sensor-capability-topography-photogrammetry\fP
.br
\fB--sensor-capability-topography-structurefrommotion\fP
.br
\fB--sensor-capability-topography-lidar\fP
.br
\fB--sensor-capability-topography-structuredlight\fP
.br
\fB--sensor-capability-topography-laserscanner\fP
.br
\fB--sensor-capability-backscatter-echosounder\fP
.br
\fB--sensor-capability-backscatter-sidescan\fP
.br
\fB--sensor-capability-backscatter-interferometry\fP
.br
\fB--sensor-capability-backscatter-sass\fP
.br
\fB--sensor-capability-backscatter-multibeam\fP
.br
\fB--sensor-capability-backscatter-lidar\fP
.br
\fB--sensor-capability-backscatter-structuredlight\fP
.br
\fB--sensor-capability-backscatter-laserscanner\fP
.br
\fB--sensor-capability-photography\fP
.br
\fB--sensor-capability-stereophotography\fP
.br
\fB--sensor-capability-video\fP
.br
\fB--sensor-capability-stereovideo\fP
.br
\fB--sensor-capability1\fP=\fIvalue\fP
.br
\fB--sensor-capability2\fP=\fIvalue\fP
.br
\fB--sensor-offsets\fP=\fIx/y/z/azimuth/roll/pitch\fP
.br
\fB--sensor-offset-positions\fP=\fIx/y/z\fP
.br
\fB--sensor-offset-angles\fP=\fIazimuth/roll/pitch\fP
.br
\fB--sensor-time-latency\fP=\fIvalue\fP
.br
\fB--sensor-time-latency-model\fP=\fIfile\fP
.br
\fB--sensor-source-bathymetry\fP
.br
\fB--sensor-source-bathymetry1\fP
.br
\fB--sensor-source-bathymetry2\fP
.br
\fB--sensor-source-bathymetry3\fP
.br
\fB--sensor-source-backscatter\fP
.br
\fB--sensor-source-backscatter1\fP
.br
\fB--sensor-source-backscatter2\fP
.br
\fB--sensor-source-backscatter3\fP
.br
\fB--sensor-source-subbottom\fP
.br
\fB--sensor-source-subbottom1\fP
.br
\fB--sensor-source-subbottom2\fP
.br
\fB--sensor-source-subbottom3\fP
.br
\fB--sensor-source-position\fP
.br
\fB--sensor-source-position1\fP
.br
\fB--sensor-source-position2\fP
.br
\fB--sensor-source-position3\fP
.br
\fB--sensor-source-depth\fP
.br
\fB--sensor-source-depth1\fP
.br
\fB--sensor-source-depth2\fP
.br
\fB--sensor-source-depth3\fP
.br
\fB--sensor-source-heading\fP
.br
\fB--sensor-source-heading1\fP
.br
\fB--sensor-source-heading2\fP
.br
\fB--sensor-source-heading3\fP
.br
\fB--sensor-source-rollpitch\fP
.br
\fB--sensor-source-rollpitch1\fP
.br
\fB--sensor-source-rollpitch2\fP
.br
\fB--sensor-source-rollpitch3\fP
.br
\fB--sensor-source-heave\fP
.br
\fB--sensor-source-heave1\fP
.br
\fB--sensor-source-heave2\fP
.br
\fB--sensor-source-heave3\fP
.br
\fB--modify-sensor\fP=\fIsensorid\fP
.br
\fB--modify-sensor-bathymetry\fP
.br
\fB--modify-sensor-bathymetry1\fP
.br
\fB--modify-sensor-bathymetry2\fP
.br
\fB--modify-sensor-bathymetry3\fP
.br
\fB--modify-sensor-backscatter\fP
.br
\fB--modify-sensor-backscatter1\fP
.br
\fB--modify-sensor-backscatter2\fP
.br
\fB--modify-sensor-backscatter3\fP
.br
\fB--modify-sensor-subbottom\fP
.br
\fB--modify-sensor-subbottom1\fP
.br
\fB--modify-sensor-subbottom2\fP
.br
\fB--modify-sensor-subbottom3\fP
.br
\fB--modify-sensor-position\fP
.br
\fB--modify-sensor-position1\fP
.br
\fB--modify-sensor-position2\fP
.br
\fB--modify-sensor-position3\fP
.br
\fB--modify-sensor-depth\fP
.br
\fB--modify-sensor-depth1\fP
.br
\fB--modify-sensor-depth2\fP
.br
\fB--modify-sensor-depth3\fP
.br
\fB--modify-sensor-heading\fP
.br
\fB--modify-sensor-heading1\fP
.br
\fB--modify-sensor-heading2\fP
.br
\fB--modify-sensor-heading3\fP
.br
\fB--modify-sensor-rollpitch\fP
.br
\fB--modify-sensor-rollpitch1\fP
.br
\fB--modify-sensor-rollpitch2\fP
.br
\fB--modify-sensor-rollpitch3\fP
.br
\fB--modify-sensor-heave\fP
.br
\fB--modify-sensor-heave1\fP
.br
\fB--modify-sensor-heave2\fP
.br
\fB--modify-sensor-heave3\fP
.br
\fB--modify-offsets\fP=\fIioff/x/y/z/azimuth/roll/pitch\fP
.br
\fB--modify-offset-positions\fP=\fIioff/x/y/z\fP
.br
\fB--modify-offset-angles\fP=\fIioff/azimuth/roll/pitch\fP
.br
\fB--modify-time-latency\fP=\fIvalue\fP
.br
\fB--modify-time-latency-model\fP=\fIfile
.br
]

.SH DESCRIPTION
Mbmakeplatform handles preprocessing of swath sonar data as part of setting
up an MB-System processing structure for a dataset. This program replaces
the several format-specific preprocessing programs
found in MB-System version 5 releases with a single program for version 6.
This program is under development, and is not ready for general use at
this time.

.SH MB-SYSTEM AUTHORSHIP
David W. Caress
.br
  Monterey Bay Aquarium Research Institute
.br
Dale N. Chayes
.br
  Center for Coastal and Ocean Mapping
.br
  University of New Hampshire
.br
Christian do Santos Ferreira
.br
  MARUM - Center for Marine Environmental Sciences
.br
  University of Bremen

.SH OPTIONS
.TP
.B --verbose
By default \fBmbmakeplatform\fP outputs minimal information to the shell. This option
causes the program to indicate it's progress as it runs. Goody.

.SH EXAMPLES
To be written.....

.SH SEE ALSO
\fBmbsystem\fP(1), \fBmbdatalist\fP(1), \fBmbprocess\fP(1)

.SH BUGS
Oh yeah.
