.TH mbpreprocess 1 "18 March 2017" "MB-System 5.0" "MB-System 5.0"
.SH NAME
\fBmbpreprocess\fP \- performs preprocessing of swath sonar data as part of setting
up an MB-System processing structure for a dataset.

.SH VERSION
Version 5.0

.SH SYNOPSIS
\fBmbpreprocess\fP [ 
.br
\fB--verbose\fP
\fB--help\fP
\fB--input\fP=\fIFILE\fP
\fB--format\fP=\fIFORMATID\fP
\fB--output-sensor-fnv\fP
.br
\fB--nav-file\fP=\fIFILE\fP
\fB--nav-file-format\fP=\fIFORMATID\fP
\fB--nav-async\fP=\fIRECORDTYPE\fP
\fB--nav-sensor\fP=\fISENSORID\fP
.br
\fB--sensordepth-file\fP=\fIFILE\fP
\fB--sensordepth-file-format\fP=\fIFORMATID\fP
\fB--sensordepth-async\fP=\fIRECORDTYPE\fP
\fB--sensordepth-sensor\fP=\fISENSORID\fP
.br
\fB--heading-file\fP=\fIFILE\fP
\fB--heading-file-format\fP=\fIFORMATID\fP
\fB--heading-async\fP=\fIRECORDTYPE\fP
\fB--heading-sensor\fP=\fISENSORID\fP
.br
\fB--altitude-file\fP=\fIFILE\fP
\fB--altitude-file-format\fP=\fIFORMATID\fP
\fB--altitude-async\fP=\fIRECORDTYPE\fP
\fB--altitude-sensor\fP=\fISENSORID\fP
.br
\fB--attitude-file\fP=\fIFILE\fP
\fB--attitude-file-format\fP=\fIFORMATID\fP
\fB--attitude-async\fP=\fIRECORDTYPE\fP
\fB--attitude-sensor\fP=\fISENSORID\fP
.br
\fB--time-latency-file\fP=\fIFILE\fP
\fB--time-latency-file-format\fP=\fIFORMATID\fP
\fB--time-latency-constant\fP=\fISECONDS\fP
\fB--time-latency-apply-nav\fP
\fB--time-latency-apply-sensordepth\fP
\fB--time-latency-apply-heading\fP
\fB--time-latency-apply-attitude\fP
\fB--time-latency-apply-altitude\fP
\fB--time-latency-apply-all-ancilliary\fP
\fB--time-latency-apply-survey\fP
\fB--time-latency-apply-all\fP
.br
\fB--filter\fP=\fISECONDS\fP
\fB--filter-apply-nav\fP
\fB--filter-apply-sensordepth\fP
\fB--filter-apply-heading\fP
\fB--filter-apply-attitude\fP
\fB--filter-apply-altitude\fP
\fB--filter-apply-all-ancilliary\fP
.br
\fB--platform-file\fP=\fIFILE\fP
\fB--platform-target-sensor\fP=\fIRECORDID\fP
\fB--no-change-survey\fP
\fBmultibeam-sidescan-source\fP=\fISECONDS\fP
\fBkluge-time-jumps\fP=\fISECONDS\fP
\fBkluge-beam-tweak\fP=\fIFACTOR\fP
\fBkluge-zero-attitude-correction\fP
\fBkluge-zero-alongtrack-angles\fP

.br
]

.SH DESCRIPTION
MBpreprocess handles preprocessing of swath sonar data as part of setting
up an MB-System processing structure for a dataset. This program replaces
the several format-specific preprocessing programs
found in MB-System version 5 releases with a single program for version 6.

.SH MB-SYSTEM AUTHORSHIP
David W. Caress
.br
  Monterey Bay Aquarium Research Institute
.br
Dale N. Chayes
.br
  Center for Coastal and Ocean Mapping
.br
  University of New Hampshire
.br
Christian do Santos Ferreira
.br
  MARUM - Center for Marine Environmental Sciences
.br
  University of Bremen

.SH OPTIONS
.TP
.B --verbose
By default \fBmbpreprocess\fP outputs minimal information to the shell. This option
causes the program to indicate it's progress as it runs. Goody.

.SH EXAMPLES
To be written.....

.SH SEE ALSO
\fBmbsystem\fP(1), \fBmbdatalist\fP(1), \fBmbprocess\fP(1)

.SH BUGS
Oh yeah.
