
/* Begin user code block <abstract> */
/* End user code block <abstract> */

/**
 * README: Portions of this file are merged at file generation
 * time. Edits can be made *only* in between specified code blocks, look
 * for keywords <Begin user code> and <End user code>.
 */
/*
 * Generated by the ICS Builder Xcessory (BX).
 *
 * BuilderXcessory Version 6.1.3
 * Code Generator Xcessory 6.1.3 (08/19/04) CGX Scripts 6.1 Motif 2.1 
 *
 */


/* Begin user code block <file_comments> */
/* End user code block <file_comments> */

#include <Xm/Xm.h>
#include <Xm/MainW.h>
#include <Xm/DialogS.h>
#include <Xm/MwmUtil.h>
#include <Xm/BulletinB.h>
#include <Xm/RowColumn.h>
#include <Xm/ToggleB.h>
#include <Xm/PushB.h>
#include <Xm/Label.h>
#include <Xm/Scale.h>
#include <Xm/TextF.h>
#include <Xm/FileSB.h>
#include <Xm/Separator.h>
#include <Xm/CascadeB.h>
#include <Xm/DrawingA.h>
#include <Xm/MainW.h>
#include <Xm/DialogS.h>
#include <Xm/MwmUtil.h>
#include <Xm/BulletinB.h>
#include <Xm/RowColumn.h>
#include <Xm/ToggleB.h>
#include <Xm/PushB.h>
#include <Xm/Label.h>
#include <Xm/Scale.h>
#include <Xm/TextF.h>
#include <Xm/FileSB.h>
#include <Xm/Separator.h>
#include <Xm/CascadeB.h>
#include <Xm/DrawingA.h>

/*
 * Global declarations are now stored in the header file.
 *
 * If DECLARE_BX_GLOBALS is defined then this header file
 * declares the globals, otherwise it just externs them.
 */
#define DECLARE_BX_GLOBALS

/**
 * Globally included information.
 */


/**
 * Common constant and pixmap declarations.
 */
#include "mbvelocity_creation.h"

/**
 * Convenience functions from utilities file.
 */
extern void RegisterBxConverters(XtAppContext);
extern XtPointer BX_CONVERT(Widget, char *, char *, int, Boolean *);
extern XtPointer BX_DOUBLE(double);
extern XtPointer BX_SINGLE(float);
extern void BX_MENU_POST(Widget, XtPointer, XEvent *, Boolean *);
extern Pixmap XPM_PIXMAP(Widget, char **);
extern void BX_SET_BACKGROUND_COLOR(Widget, ArgList, Cardinal *, Pixel);

/**
 * Declarations for callbacks and handlers.
 */
extern void do_quit(Widget, XtPointer, XtPointer);
extern void BxUnmanageCB(Widget, XtPointer, XtPointer);
extern void do_anglemode(Widget, XtPointer, XtPointer);
extern void do_velcenter(Widget, XtPointer, XtPointer);
extern void do_residual_range(Widget, XtPointer, XtPointer);
extern void do_velrange(Widget, XtPointer, XtPointer);
extern void do_maxdepth(Widget, XtPointer, XtPointer);
extern void do_open(Widget, XtPointer, XtPointer);
extern void BxManageCB(Widget, XtPointer, XtPointer);
extern void do_process_mb(Widget, XtPointer, XtPointer);
extern void do_canvas_event(Widget, XtPointer, XtPointer);
extern void do_expose(Widget, XtPointer, XtPointer);
extern void do_io_mode_open_svp_display(Widget, XtPointer, XtPointer);
extern void BxSetValuesCB(Widget, XtPointer, XtPointer);
extern void do_io_mode_open_svp_edit(Widget, XtPointer, XtPointer);
extern void do_new_profile(Widget, XtPointer, XtPointer);
extern void do_io_mode_save_svp(Widget, XtPointer, XtPointer);
extern void do_io_mode_mb(Widget, XtPointer, XtPointer);
extern void do_save_swath_svp(Widget, XtPointer, XtPointer);
extern void do_save_residuals(Widget, XtPointer, XtPointer);

/**
 * Create the window_mbvelocity hierarchy of widgets.
 */
Widget
Createwindow_mbvelocity(Widget parent)
{
    Cardinal ac = 0;
    Arg      args[256];
    Cardinal cdc = 0;
    Boolean  argok = False;
    Widget   window_mbvelocity;
    Widget   dialogShell_mode;
    Widget   bulletinBoard_mode;
    Widget   radioBox_mode;
    Widget   pushButton_mode_dismiss;
    Widget   xmDialogShell_scaling;
    Widget   bulletinBoard_scaling;
    Widget   label_velcenter;
    Widget   pushButton_scaling_dismiss;
    Widget   label_residual_range;
    Widget   label_velrange;
    Widget   label_max_depth;
    Widget   xmDialogShell_error;
    Widget   pushButton_error;
    Widget   bulletinBoard_fileselect;
    Widget   xmDialogShell_message;
    Widget   label_pleasewait;
    Widget   xmDialogShell_about;
    Widget   bulletinBoard_about;
    Widget   label_about_create1;
    Widget   separator2;
    Widget   pushButton_about_dismiss;
    Widget   label_about_create;
    Widget   label_about_lamont;
    Widget   label_about_columbia;
    Widget   label_about_mbsystem;
    Widget   label_about_mbpub;
    Widget   label_about_component;
    Widget   label_about_for;
    Widget   separator;
    Widget   label_about_function;
    Widget   label_about_mbedit;
    Widget   input_screen;
    Widget   pushButton_mode;
    Widget   pushButton_plotscaling;
    Widget   rowColumn;
    Widget   menuBar_file;
    Widget   cascadeButton_file;
    Widget   pulldownMenu_file;
    Widget   pushButton_open_svp_display;
    Widget   pushButton_open_svp_edit;
    Widget   pushButton_new_svp_edit;
    Widget   separator1;
    Widget   separator3;
    Widget   pushButton_about;
    Widget   pushButton_quit;
    
    /**
     * Register the converters for the widgets.
     */
    RegisterBxConverters(XtWidgetToApplicationContext(parent));
    XtInitializeWidgetClass((WidgetClass)xmMainWindowWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmDialogShellWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmBulletinBoardWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmRowColumnWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmToggleButtonWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmPushButtonWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmLabelWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmScaleWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmTextFieldWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmFileSelectionBoxWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmSeparatorWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmBulletinBoardWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmRowColumnWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmRowColumnWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmCascadeButtonWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmRowColumnWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmDrawingAreaWidgetClass);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 365); ac++;
    XtSetArg(args[ac], XmNy, 192); ac++;
    XtSetArg(args[ac], XmNwidth, 1016); ac++;
    XtSetArg(args[ac], XmNheight, 668); ac++;
    window_mbvelocity = XmCreateMainWindow(parent,
        (char *)"window_mbvelocity",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNmarginHeight, 0); ac++;
    XtSetArg(args[ac], XmNmarginWidth, 0); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNwidth, 1016); ac++;
    XtSetArg(args[ac], XmNheight, 668); ac++;
    input_screen = XmCreateBulletinBoard(window_mbvelocity,
        (char *)"input_screen",
        args, 
        ac);
    XtManageChild(input_screen);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(input_screen, (char *)"Angle Mode", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 330); ac++;
        XtSetArg(args[ac], XmNy, 0); ac++;
        XtSetArg(args[ac], XmNwidth, 90); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(input_screen, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_mode = XmCreatePushButton(input_screen,
            (char *)"pushButton_mode",
            args, 
            ac);
        XtManageChild(pushButton_mode);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_mode, XmNactivateCallback, BxManageCB, (XtPointer)"bulletinBoard_mode");
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(input_screen, (char *)"Plot Scaling", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 160); ac++;
        XtSetArg(args[ac], XmNy, 0); ac++;
        XtSetArg(args[ac], XmNwidth, 90); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(input_screen, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_plotscaling = XmCreatePushButton(input_screen,
            (char *)"pushButton_plotscaling",
            args, 
            ac);
        XtManageChild(pushButton_plotscaling);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_plotscaling, XmNactivateCallback, BxManageCB, (XtPointer)"bulletinBoard_scaling");
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 83); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    rowColumn = XmCreateRowColumn(input_screen,
        (char *)"rowColumn",
        args, 
        ac);
    XtManageChild(rowColumn);
    
    ac = 0;
    XtSetArg(args[ac], XmNmarginHeight, 0); ac++;
    XtSetArg(args[ac], XmNmarginWidth, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 77); ac++;
    XtSetArg(args[ac], XmNheight, 28); ac++;
    menuBar_file = XmCreateMenuBar(rowColumn,
        (char *)"menuBar_file",
        args, 
        ac);
    XtManageChild(menuBar_file);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(menuBar_file, (char *)"    File    ", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 2); ac++;
        XtSetArg(args[ac], XmNy, 2); ac++;
        XtSetArg(args[ac], XmNwidth, 73); ac++;
        XtSetArg(args[ac], XmNheight, 24); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(menuBar_file, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        cascadeButton_file = XmCreateCascadeButton(menuBar_file,
            (char *)"cascadeButton_file",
            args, 
            ac);
        XtManageChild(cascadeButton_file);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 184); ac++;
    XtSetArg(args[ac], XmNheight, 176); ac++;
    pulldownMenu_file = XmCreatePulldownMenu(XtParent(cascadeButton_file),
        (char *)"pulldownMenu_file",
        args, 
        ac);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(pulldownMenu_file, (char *)"Open display profile", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(pulldownMenu_file, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_open_svp_display = XmCreatePushButton(pulldownMenu_file,
            (char *)"pushButton_open_svp_display",
            args, 
            ac);
        XtManageChild(pushButton_open_svp_display);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_open_svp_display, XmNactivateCallback, BxManageCB, (XtPointer)"bulletinBoard_fileselect");
    XtAddCallback(pushButton_open_svp_display, XmNactivateCallback, do_io_mode_open_svp_display, (XtPointer)0);
    XtAddCallback(pushButton_open_svp_display, XmNactivateCallback, BxUnmanageCB, (XtPointer)"label_mbformat");
    XtAddCallback(pushButton_open_svp_display, XmNactivateCallback, BxUnmanageCB, (XtPointer)"textField_mbformat");
    XtAddCallback(pushButton_open_svp_display, XmNactivateCallback, BxSetValuesCB, (XtPointer)"xmDialogShell_fileselect.title=Open Display Sound Velocity Profile (SVP)");
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(pulldownMenu_file, (char *)"Open editable profile", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(pulldownMenu_file, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_open_svp_edit = XmCreatePushButton(pulldownMenu_file,
            (char *)"pushButton_open_svp_edit",
            args, 
            ac);
        XtManageChild(pushButton_open_svp_edit);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_open_svp_edit, XmNactivateCallback, BxManageCB, (XtPointer)"bulletinBoard_fileselect");
    XtAddCallback(pushButton_open_svp_edit, XmNactivateCallback, do_io_mode_open_svp_edit, (XtPointer)0);
    XtAddCallback(pushButton_open_svp_edit, XmNactivateCallback, BxUnmanageCB, (XtPointer)"label_mbformat");
    XtAddCallback(pushButton_open_svp_edit, XmNactivateCallback, BxUnmanageCB, (XtPointer)"textField_mbformat");
    XtAddCallback(pushButton_open_svp_edit, XmNactivateCallback, BxSetValuesCB, (XtPointer)"xmDialogShell_fileselect.title=Open Editable Sound Velocity Profile (SVP)");
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(pulldownMenu_file, (char *)"New editable profile...", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(pulldownMenu_file, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_new_svp_edit = XmCreatePushButton(pulldownMenu_file,
            (char *)"pushButton_new_svp_edit",
            args, 
            ac);
        XtManageChild(pushButton_new_svp_edit);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_new_svp_edit, XmNactivateCallback, do_new_profile, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(pulldownMenu_file, (char *)"Save editable profile", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(pulldownMenu_file, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_save_svp = XmCreatePushButton(pulldownMenu_file,
            (char *)"pushButton_save_svp",
            args, 
            ac);
        XtManageChild(pushButton_save_svp);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_save_svp, XmNactivateCallback, BxManageCB, (XtPointer)"bulletinBoard_fileselect");
    XtAddCallback(pushButton_save_svp, XmNactivateCallback, do_io_mode_save_svp, (XtPointer)0);
    XtAddCallback(pushButton_save_svp, XmNactivateCallback, BxUnmanageCB, (XtPointer)"label_mbformat");
    XtAddCallback(pushButton_save_svp, XmNactivateCallback, BxUnmanageCB, (XtPointer)"textField_mbformat");
    XtAddCallback(pushButton_save_svp, XmNactivateCallback, BxSetValuesCB, (XtPointer)"xmDialogShell_fileselect.title=Save Editable Sound Velocity Profile (SVP)");
    
    ac = 0;
    separator1 = XmCreateSeparator(pulldownMenu_file,
        (char *)"separator1",
        args, 
        ac);
    XtManageChild(separator1);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(pulldownMenu_file, (char *)"Open swath sonar data", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(pulldownMenu_file, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_open_mb = XmCreatePushButton(pulldownMenu_file,
            (char *)"pushButton_open_mb",
            args, 
            ac);
        XtManageChild(pushButton_open_mb);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_open_mb, XmNactivateCallback, BxManageCB, (XtPointer)"bulletinBoard_fileselect");
    XtAddCallback(pushButton_open_mb, XmNactivateCallback, do_io_mode_mb, (XtPointer)0);
    XtAddCallback(pushButton_open_mb, XmNactivateCallback, BxManageCB, (XtPointer)"label_mbformat");
    XtAddCallback(pushButton_open_mb, XmNactivateCallback, BxManageCB, (XtPointer)"textField_mbformat");
    XtAddCallback(pushButton_open_mb, XmNactivateCallback, BxSetValuesCB, (XtPointer)"xmDialogShell_fileselect.title=Open Swath Sonar Data");
    
    ac = 0;
    separator3 = XmCreateSeparator(pulldownMenu_file,
        (char *)"separator3",
        args, 
        ac);
    XtManageChild(separator3);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(pulldownMenu_file, (char *)"Save swath svp file", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNsensitive, False); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(pulldownMenu_file, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_save_svpfile = XmCreatePushButton(pulldownMenu_file,
            (char *)"pushButton_save_svpfile",
            args, 
            ac);
        XtManageChild(pushButton_save_svpfile);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_save_svpfile, XmNactivateCallback, do_save_swath_svp, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(pulldownMenu_file, (char *)"Save residuals as offsets", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(pulldownMenu_file, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_save_residuals = XmCreatePushButton(pulldownMenu_file,
            (char *)"pushButton_save_residuals",
            args, 
            ac);
        XtManageChild(pushButton_save_residuals);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_save_residuals, XmNactivateCallback, do_save_residuals, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, pulldownMenu_file); ac++;
    XtSetValues(cascadeButton_file, args, ac);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(input_screen, (char *)"About", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 930); ac++;
        XtSetArg(args[ac], XmNy, 0); ac++;
        XtSetArg(args[ac], XmNwidth, 80); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(input_screen, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_about = XmCreatePushButton(input_screen,
            (char *)"pushButton_about",
            args, 
            ac);
        XtManageChild(pushButton_about);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_about, XmNactivateCallback, BxManageCB, (XtPointer)"bulletinBoard_about");
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(input_screen, (char *)"Quit", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 700); ac++;
        XtSetArg(args[ac], XmNy, 0); ac++;
        XtSetArg(args[ac], XmNwidth, 80); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(input_screen, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_quit = XmCreatePushButton(input_screen,
            (char *)"pushButton_quit",
            args, 
            ac);
        XtManageChild(pushButton_quit);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_quit, XmNactivateCallback, do_quit, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(input_screen, (char *)"Reprocess", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 520); ac++;
        XtSetArg(args[ac], XmNy, 0); ac++;
        XtSetArg(args[ac], XmNwidth, 90); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(input_screen, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_process = XmCreatePushButton(input_screen,
            (char *)"pushButton_process",
            args, 
            ac);
        XtManageChild(pushButton_process);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_process, XmNactivateCallback, do_process_mb, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNborderWidth, 1); ac++;
    XtSetArg(args[ac], XmNbackground, 
        BX_CONVERT(input_screen, (char *)"white", 
        XmRPixel, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 100); ac++;
    XtSetArg(args[ac], XmNwidth, 1010); ac++;
    XtSetArg(args[ac], XmNheight, 560); ac++;
    drawingArea = XmCreateDrawingArea(input_screen,
        (char *)"drawingArea",
        args, 
        ac);
    XtManageChild(drawingArea);
    XtAddCallback(drawingArea, XmNinputCallback, do_canvas_event, (XtPointer)0);
    XtAddCallback(drawingArea, XmNexposeCallback, do_expose, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(input_screen, (char *)"No Display Sound Velocity Profiles Loaded", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
        XtSetArg(args[ac], XmNx, 0); ac++;
        XtSetArg(args[ac], XmNy, 40); ac++;
        XtSetArg(args[ac], XmNwidth, 1010); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(input_screen, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_status_display = XmCreateLabel(input_screen,
            (char *)"label_status_display",
            args, 
            ac);
        XtManageChild(label_status_display);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(input_screen, (char *)"No Editable Sound Velocity Profile Loaded", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
        XtSetArg(args[ac], XmNx, 0); ac++;
        XtSetArg(args[ac], XmNy, 60); ac++;
        XtSetArg(args[ac], XmNwidth, 1010); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(input_screen, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_status_edit = XmCreateLabel(input_screen,
            (char *)"label_status_edit",
            args, 
            ac);
        XtManageChild(label_status_edit);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(input_screen, (char *)"No MultiBeam Data Loaded", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
        XtSetArg(args[ac], XmNx, 0); ac++;
        XtSetArg(args[ac], XmNy, 80); ac++;
        XtSetArg(args[ac], XmNwidth, 1010); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(input_screen, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_status_mb = XmCreateLabel(input_screen,
            (char *)"label_status_mb",
            args, 
            ac);
        XtManageChild(label_status_mb);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNtitle, "About MBedit"); ac++;
    XtSetArg(args[ac], XmNdeleteResponse, XmUNMAP); ac++;
    XtSetArg(args[ac], XmNwidth, 481); ac++;
    XtSetArg(args[ac], XmNheight, 456); ac++;
    xmDialogShell_about = XmCreateDialogShell(window_mbvelocity,
        (char *)"xmDialogShell_about",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 542); ac++;
    XtSetArg(args[ac], XmNy, 288); ac++;
    XtSetArg(args[ac], XmNwidth, 481); ac++;
    XtSetArg(args[ac], XmNheight, 456); ac++;
    bulletinBoard_about = XtCreateWidget((char *)"bulletinBoard_about",
        xmBulletinBoardWidgetClass,
        xmDialogShell_about,
        args, 
        ac);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)"David W. Caress    and    Dale N. Chayes", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-140-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 260); ac++;
        XtSetArg(args[ac], XmNwidth, 460); ac++;
        XtSetArg(args[ac], XmNheight, 20); ac++;
        label_about_create1 = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_create1",
            args, 
            ac);
        XtManageChild(label_about_create1);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 220); ac++;
    XtSetArg(args[ac], XmNwidth, 460); ac++;
    XtSetArg(args[ac], XmNheight, 20); ac++;
    separator2 = XmCreateSeparator(bulletinBoard_about,
        (char *)"separator2",
        args, 
        ac);
    XtManageChild(separator2);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)"Dismiss", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-140-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 200); ac++;
        XtSetArg(args[ac], XmNy, 410); ac++;
        XtSetArg(args[ac], XmNwidth, 80); ac++;
        XtSetArg(args[ac], XmNheight, 35); ac++;
        pushButton_about_dismiss = XmCreatePushButton(bulletinBoard_about,
            (char *)"pushButton_about_dismiss",
            args, 
            ac);
        XtManageChild(pushButton_about_dismiss);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_about_dismiss, XmNactivateCallback, BxUnmanageCB, (XtPointer)"bulletinBoard_about");
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)"Created by:", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-140-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 240); ac++;
        XtSetArg(args[ac], XmNwidth, 460); ac++;
        XtSetArg(args[ac], XmNheight, 20); ac++;
        label_about_create = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_create",
            args, 
            ac);
        XtManageChild(label_about_create);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)":::t\"Lamont-Doherty\":t\"Earth Observatory\"\"of Columbia University\"", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-120-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 250); ac++;
        XtSetArg(args[ac], XmNy, 280); ac++;
        XtSetArg(args[ac], XmNwidth, 180); ac++;
        XtSetArg(args[ac], XmNheight, 60); ac++;
        label_about_lamont = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_lamont",
            args, 
            ac);
        XtManageChild(label_about_lamont);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)":::t\"Monterey Bay\":t\"Aquarium\"\"Research Institute\"", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-120-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 70); ac++;
        XtSetArg(args[ac], XmNy, 280); ac++;
        XtSetArg(args[ac], XmNwidth, 140); ac++;
        XtSetArg(args[ac], XmNheight, 60); ac++;
        label_about_columbia = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_columbia",
            args, 
            ac);
        XtManageChild(label_about_columbia);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)"MB-System", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-240-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 120); ac++;
        XtSetArg(args[ac], XmNwidth, 450); ac++;
        XtSetArg(args[ac], XmNheight, 38); ac++;
        label_about_mbsystem = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_mbsystem",
            args, 
            ac);
        XtManageChild(label_about_mbsystem);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)"An Open Source Software Package", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-140-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 160); ac++;
        XtSetArg(args[ac], XmNwidth, 450); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        label_about_mbpub = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_mbpub",
            args, 
            ac);
        XtManageChild(label_about_mbpub);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)"One Component of the", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-140-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 90); ac++;
        XtSetArg(args[ac], XmNwidth, 450); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        label_about_component = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_component",
            args, 
            ac);
        XtManageChild(label_about_component);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)"for Processing and Display of Swath Sonar Data", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-140-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 190); ac++;
        XtSetArg(args[ac], XmNwidth, 460); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        label_about_for = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_for",
            args, 
            ac);
        XtManageChild(label_about_for);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 70); ac++;
    XtSetArg(args[ac], XmNwidth, 460); ac++;
    XtSetArg(args[ac], XmNheight, 20); ac++;
    separator = XmCreateSeparator(bulletinBoard_about,
        (char *)"separator",
        args, 
        ac);
    XtManageChild(separator);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)":::t\"MB-System Release 4.6\"\"April 14, 1999\"", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-medium-r-*-*-*-140-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 350); ac++;
        XtSetArg(args[ac], XmNwidth, 460); ac++;
        XtSetArg(args[ac], XmNheight, 60); ac++;
        label_about_version = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_version",
            args, 
            ac);
        XtManageChild(label_about_version);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)"Interactive SVP Modeler/Editor", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-180-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 40); ac++;
        XtSetArg(args[ac], XmNwidth, 460); ac++;
        XtSetArg(args[ac], XmNheight, 23); ac++;
        label_about_function = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_function",
            args, 
            ac);
        XtManageChild(label_about_function);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_about, (char *)"MBvelocitytool", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_about, (char *)"-*-times-bold-r-*-*-*-240-*-*-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 10); ac++;
        XtSetArg(args[ac], XmNwidth, 460); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        label_about_mbedit = XmCreateLabel(bulletinBoard_about,
            (char *)"label_about_mbedit",
            args, 
            ac);
        XtManageChild(label_about_mbedit);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNtitle, "Please Wait..."); ac++;
    XtSetArg(args[ac], XmNmwmInputMode, MWM_INPUT_MODELESS); ac++;
    XtSetArg(args[ac], XmNdeleteResponse, XmUNMAP); ac++;
    XtSetArg(args[ac], XmNwidth, 379); ac++;
    XtSetArg(args[ac], XmNheight, 88); ac++;
    xmDialogShell_message = XmCreateDialogShell(window_mbvelocity,
        (char *)"xmDialogShell_message",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogStyle, XmDIALOG_FULL_APPLICATION_MODAL); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_NONE); ac++;
    XtSetArg(args[ac], XmNx, 1001); ac++;
    XtSetArg(args[ac], XmNy, 467); ac++;
    XtSetArg(args[ac], XmNwidth, 379); ac++;
    XtSetArg(args[ac], XmNheight, 88); ac++;
    bulletinBoard_message = XtCreateWidget((char *)"bulletinBoard_message",
        xmBulletinBoardWidgetClass,
        xmDialogShell_message,
        args, 
        ac);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_message, (char *)"Thank you for your patience.", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
        XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 40); ac++;
        XtSetArg(args[ac], XmNwidth, 360); ac++;
        XtSetArg(args[ac], XmNheight, 20); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_message, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_pleasewait = XmCreateLabel(bulletinBoard_message,
            (char *)"label_pleasewait",
            args, 
            ac);
        XtManageChild(label_pleasewait);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_message, (char *)"MBvelocitytool is loading data...", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 10); ac++;
        XtSetArg(args[ac], XmNwidth, 360); ac++;
        XtSetArg(args[ac], XmNheight, 20); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_message, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_message = XmCreateLabel(bulletinBoard_message,
            (char *)"label_message",
            args, 
            ac);
        XtManageChild(label_message);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNtitle, "Open Swath Sonar Data"); ac++;
    XtSetArg(args[ac], XmNwidth, 591); ac++;
    XtSetArg(args[ac], XmNheight, 537); ac++;
    xmDialogShell_fileselect = XmCreateDialogShell(window_mbvelocity,
        (char *)"xmDialogShell_fileselect",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNautoUnmanage, False); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 512); ac++;
    XtSetArg(args[ac], XmNy, 316); ac++;
    XtSetArg(args[ac], XmNwidth, 591); ac++;
    XtSetArg(args[ac], XmNheight, 537); ac++;
    bulletinBoard_fileselect = XtCreateWidget((char *)"bulletinBoard_fileselect",
        xmBulletinBoardWidgetClass,
        xmDialogShell_fileselect,
        args, 
        ac);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_fileselect, (char *)"Swath Sonar Format ID:", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 20); ac++;
        XtSetArg(args[ac], XmNy, 490); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_fileselect, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_mbformat = XmCreateLabel(bulletinBoard_fileselect,
            (char *)"label_mbformat",
            args, 
            ac);
        XtManageChild(label_mbformat);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNborderWidth, 1); ac++;
    XtSetArg(args[ac], XmNvalue, "1"); ac++;
    XtSetArg(args[ac], XmNcolumns, 5); ac++;
    XtSetArg(args[ac], XmNmaxLength, 5); ac++;
    XtSetArg(args[ac], XmNresizeWidth, False); ac++;
    XtSetArg(args[ac], XmNcursorPosition, 1); ac++;
    XtSetArg(args[ac], XmNhighlightOnEnter, False); ac++;
    XtSetArg(args[ac], XmNmarginHeight, 2); ac++;
    XtSetArg(args[ac], XmNshadowThickness, 0); ac++;
    XtSetArg(args[ac], XmNhighlightThickness, 0); ac++;
    XtSetArg(args[ac], XmNmarginWidth, 2); ac++;
    XtSetArg(args[ac], XmNx, 210); ac++;
    XtSetArg(args[ac], XmNy, 490); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    XtSetArg(args[ac], XmNfontList, 
        BX_CONVERT(bulletinBoard_fileselect, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    textField_mbformat = XmCreateTextField(bulletinBoard_fileselect,
        (char *)"textField_mbformat",
        args, 
        ac);
    XtManageChild(textField_mbformat);
    
    ac = 0;
    XtSetArg(args[ac], XmNmarginHeight, 2); ac++;
    XtSetArg(args[ac], XmNmarginWidth, 2); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 570); ac++;
    XtSetArg(args[ac], XmNheight, 470); ac++;
    fileSelectionBox = XmCreateFileSelectionBox(bulletinBoard_fileselect,
        (char *)"fileSelectionBox",
        args, 
        ac);
    XtManageChild(fileSelectionBox);
    XtAddCallback(fileSelectionBox, XmNokCallback, do_open, (XtPointer)0);
    XtAddCallback(fileSelectionBox, XmNokCallback, BxUnmanageCB, (XtPointer)"bulletinBoard_fileselect");
    XtAddCallback(fileSelectionBox, XmNcancelCallback, BxUnmanageCB, (XtPointer)"bulletinBoard_fileselect");
    
    ac = 0;
    XtSetArg(args[ac], XmNtitle, "Error"); ac++;
    XtSetArg(args[ac], XmNwidth, 311); ac++;
    XtSetArg(args[ac], XmNheight, 161); ac++;
    xmDialogShell_error = XmCreateDialogShell(window_mbvelocity,
        (char *)"xmDialogShell_error",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogStyle, XmDIALOG_APPLICATION_MODAL); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 888); ac++;
    XtSetArg(args[ac], XmNy, 511); ac++;
    XtSetArg(args[ac], XmNwidth, 311); ac++;
    XtSetArg(args[ac], XmNheight, 161); ac++;
    bulletinBoard_error = XtCreateWidget((char *)"bulletinBoard_error",
        xmBulletinBoardWidgetClass,
        xmDialogShell_error,
        args, 
        ac);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_error, (char *)"You probably do not have write", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 40); ac++;
        XtSetArg(args[ac], XmNwidth, 290); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_error, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_error_two = XmCreateLabel(bulletinBoard_error,
            (char *)"label_error_two",
            args, 
            ac);
        XtManageChild(label_error_two);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_error, (char *)"Unable to open output file.", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 10); ac++;
        XtSetArg(args[ac], XmNwidth, 290); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_error, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_error_one = XmCreateLabel(bulletinBoard_error,
            (char *)"label_error_one",
            args, 
            ac);
        XtManageChild(label_error_one);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_error, (char *)"permission in this directory!", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 70); ac++;
        XtSetArg(args[ac], XmNwidth, 290); ac++;
        XtSetArg(args[ac], XmNheight, 30); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_error, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_error_three = XmCreateLabel(bulletinBoard_error,
            (char *)"label_error_three",
            args, 
            ac);
        XtManageChild(label_error_three);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_error, (char *)"OK", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 110); ac++;
        XtSetArg(args[ac], XmNy, 110); ac++;
        XtSetArg(args[ac], XmNwidth, 90); ac++;
        XtSetArg(args[ac], XmNheight, 40); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_error, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_error = XmCreatePushButton(bulletinBoard_error,
            (char *)"pushButton_error",
            args, 
            ac);
        XtManageChild(pushButton_error);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNtitle, "Plot Scaling"); ac++;
    XtSetArg(args[ac], XmNwidth, 543); ac++;
    XtSetArg(args[ac], XmNheight, 220); ac++;
    xmDialogShell_scaling = XmCreateDialogShell(window_mbvelocity,
        (char *)"xmDialogShell_scaling",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 143); ac++;
    XtSetArg(args[ac], XmNy, 513); ac++;
    XtSetArg(args[ac], XmNwidth, 543); ac++;
    XtSetArg(args[ac], XmNheight, 220); ac++;
    bulletinBoard_scaling = XtCreateWidget((char *)"bulletinBoard_scaling",
        xmBulletinBoardWidgetClass,
        xmDialogShell_scaling,
        args, 
        ac);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"1700", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
        XtSetArg(args[ac], XmNx, 470); ac++;
        XtSetArg(args[ac], XmNy, 90); ac++;
        XtSetArg(args[ac], XmNwidth, 50); ac++;
        XtSetArg(args[ac], XmNheight, 20); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_vel_center_max = XmCreateLabel(bulletinBoard_scaling,
            (char *)"label_vel_center_max",
            args, 
            ac);
        XtManageChild(label_vel_center_max);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"Velocity Center (m/s): 1300", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 90); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_velcenter = XmCreateLabel(bulletinBoard_scaling,
            (char *)"label_velcenter",
            args, 
            ac);
        XtManageChild(label_velcenter);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNminimum, 25); ac++;
    XtSetArg(args[ac], XmNvalue, 500); ac++;
    XtSetArg(args[ac], XmNmaximum, 1000); ac++;
    XtSetArg(args[ac], XmNscaleHeight, 15); ac++;
    XtSetArg(args[ac], XmNshowArrows, TRUE); ac++;
    XtSetArg(args[ac], XmNscaleMultiple, 1); ac++;
    XtSetArg(args[ac], XmNshowValue, TRUE); ac++;
    XtSetArg(args[ac], XmNhighlightThickness, 1); ac++;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNx, 200); ac++;
    XtSetArg(args[ac], XmNy, 80); ac++;
    XtSetArg(args[ac], XmNwidth, 270); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    XtSetArg(args[ac], XmNfontList, 
        BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    slider_velcenter = XmCreateScale(bulletinBoard_scaling,
        (char *)"slider_velcenter",
        args, 
        ac);
    XtManageChild(slider_velcenter);
    XtAddCallback(slider_velcenter, XmNvalueChangedCallback, do_velcenter, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"Dismiss", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 230); ac++;
        XtSetArg(args[ac], XmNy, 170); ac++;
        XtSetArg(args[ac], XmNwidth, 90); ac++;
        XtSetArg(args[ac], XmNheight, 40); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_scaling_dismiss = XmCreatePushButton(bulletinBoard_scaling,
            (char *)"pushButton_scaling_dismiss",
            args, 
            ac);
        XtManageChild(pushButton_scaling_dismiss);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_scaling_dismiss, XmNactivateCallback, BxUnmanageCB, (XtPointer)"bulletinBoard_scaling");
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"200", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
        XtSetArg(args[ac], XmNx, 470); ac++;
        XtSetArg(args[ac], XmNy, 130); ac++;
        XtSetArg(args[ac], XmNwidth, 50); ac++;
        XtSetArg(args[ac], XmNheight, 20); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_res_range_max = XmCreateLabel(bulletinBoard_scaling,
            (char *)"label_res_range_max",
            args, 
            ac);
        XtManageChild(label_res_range_max);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNtitleString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNminimum, 1); ac++;
        XtSetArg(args[ac], XmNdecimalPoints, 1); ac++;
        XtSetArg(args[ac], XmNvalue, 100); ac++;
        XtSetArg(args[ac], XmNmaximum, 2000); ac++;
        XtSetArg(args[ac], XmNscaleHeight, 15); ac++;
        XtSetArg(args[ac], XmNshowArrows, TRUE); ac++;
        XtSetArg(args[ac], XmNscaleMultiple, 1); ac++;
        XtSetArg(args[ac], XmNshowValue, TRUE); ac++;
        XtSetArg(args[ac], XmNhighlightThickness, 1); ac++;
        XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
        XtSetArg(args[ac], XmNx, 200); ac++;
        XtSetArg(args[ac], XmNy, 120); ac++;
        XtSetArg(args[ac], XmNwidth, 270); ac++;
        XtSetArg(args[ac], XmNheight, 39); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        slider_residual_range = XmCreateScale(bulletinBoard_scaling,
            (char *)"slider_residual_range",
            args, 
            ac);
        XtManageChild(slider_residual_range);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(slider_residual_range, XmNvalueChangedCallback, do_residual_range, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"Residual Range (m):    1", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 130); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_residual_range = XmCreateLabel(bulletinBoard_scaling,
            (char *)"label_residual_range",
            args, 
            ac);
        XtManageChild(label_residual_range);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"1000", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
        XtSetArg(args[ac], XmNx, 470); ac++;
        XtSetArg(args[ac], XmNy, 50); ac++;
        XtSetArg(args[ac], XmNwidth, 50); ac++;
        XtSetArg(args[ac], XmNheight, 20); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_vel_range_max = XmCreateLabel(bulletinBoard_scaling,
            (char *)"label_vel_range_max",
            args, 
            ac);
        XtManageChild(label_vel_range_max);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNminimum, 25); ac++;
    XtSetArg(args[ac], XmNvalue, 500); ac++;
    XtSetArg(args[ac], XmNmaximum, 1000); ac++;
    XtSetArg(args[ac], XmNscaleHeight, 15); ac++;
    XtSetArg(args[ac], XmNshowArrows, TRUE); ac++;
    XtSetArg(args[ac], XmNscaleMultiple, 1); ac++;
    XtSetArg(args[ac], XmNshowValue, TRUE); ac++;
    XtSetArg(args[ac], XmNhighlightThickness, 1); ac++;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNx, 200); ac++;
    XtSetArg(args[ac], XmNy, 40); ac++;
    XtSetArg(args[ac], XmNwidth, 270); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    XtSetArg(args[ac], XmNfontList, 
        BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    slider_velrange = XmCreateScale(bulletinBoard_scaling,
        (char *)"slider_velrange",
        args, 
        ac);
    XtManageChild(slider_velrange);
    XtAddCallback(slider_velrange, XmNvalueChangedCallback, do_velrange, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"Velocity Range (m/s): 25", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 50); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_velrange = XmCreateLabel(bulletinBoard_scaling,
            (char *)"label_velrange",
            args, 
            ac);
        XtManageChild(label_velrange);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"13000", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
        XtSetArg(args[ac], XmNx, 470); ac++;
        XtSetArg(args[ac], XmNy, 10); ac++;
        XtSetArg(args[ac], XmNwidth, 50); ac++;
        XtSetArg(args[ac], XmNheight, 20); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_max_depth_max = XmCreateLabel(bulletinBoard_scaling,
            (char *)"label_max_depth_max",
            args, 
            ac);
        XtManageChild(label_max_depth_max);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNminimum, 1); ac++;
    XtSetArg(args[ac], XmNvalue, 3000); ac++;
    XtSetArg(args[ac], XmNmaximum, 13000); ac++;
    XtSetArg(args[ac], XmNscaleHeight, 15); ac++;
    XtSetArg(args[ac], XmNshowArrows, TRUE); ac++;
    XtSetArg(args[ac], XmNscaleMultiple, 1); ac++;
    XtSetArg(args[ac], XmNshowValue, TRUE); ac++;
    XtSetArg(args[ac], XmNhighlightThickness, 1); ac++;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNx, 200); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 270); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    XtSetArg(args[ac], XmNfontList, 
        BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    slider_maxdepth = XmCreateScale(bulletinBoard_scaling,
        (char *)"slider_maxdepth",
        args, 
        ac);
    XtManageChild(slider_maxdepth);
    XtAddCallback(slider_maxdepth, XmNvalueChangedCallback, do_maxdepth, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_scaling, (char *)"Maximum Depth (m):     1", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 10); ac++;
        XtSetArg(args[ac], XmNy, 10); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_scaling, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        label_max_depth = XmCreateLabel(bulletinBoard_scaling,
            (char *)"label_max_depth",
            args, 
            ac);
        XtManageChild(label_max_depth);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNtitle, "Beam Angle Mode"); ac++;
    XtSetArg(args[ac], XmNwidth, 348); ac++;
    XtSetArg(args[ac], XmNheight, 172); ac++;
    dialogShell_mode = XmCreateDialogShell(window_mbvelocity,
        (char *)"dialogShell_mode",
        args, 
        ac);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(dialogShell_mode, (char *)"Beam Angle Mode", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNdialogTitle, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNautoUnmanage, False); ac++;
        XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
        XtSetArg(args[ac], XmNx, 875); ac++;
        XtSetArg(args[ac], XmNy, 481); ac++;
        XtSetArg(args[ac], XmNwidth, 348); ac++;
        XtSetArg(args[ac], XmNheight, 172); ac++;
        bulletinBoard_mode = XtCreateWidget((char *)"bulletinBoard_mode",
            xmBulletinBoardWidgetClass,
            dialogShell_mode,
            args, 
            ac);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 20); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 293); ac++;
    XtSetArg(args[ac], XmNheight, 96); ac++;
    XtSetArg(args[ac], XmNisHomogeneous, False); ac++;
    radioBox_mode = XmCreateRadioBox(bulletinBoard_mode,
        (char *)"radioBox_mode",
        args, 
        ac);
    XtManageChild(radioBox_mode);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(radioBox_mode, (char *)"Do Not Change Beam Angles", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNwidth, 287); ac++;
        XtSetArg(args[ac], XmNheight, 28); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(radioBox_mode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        toggleButton_mode_ok = XmCreateToggleButton(radioBox_mode,
            (char *)"toggleButton_mode_ok",
            args, 
            ac);
        XtManageChild(toggleButton_mode_ok);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(toggleButton_mode_ok, XmNvalueChangedCallback, do_anglemode, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(radioBox_mode, (char *)"Adjust Angles Using Snell\'s Law", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNwidth, 287); ac++;
        XtSetArg(args[ac], XmNheight, 28); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(radioBox_mode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        toggleButton_mode_snell = XmCreateToggleButton(radioBox_mode,
            (char *)"toggleButton_mode_snell",
            args, 
            ac);
        XtManageChild(toggleButton_mode_snell);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(toggleButton_mode_snell, XmNvalueChangedCallback, do_anglemode, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(radioBox_mode, (char *)"Adjust Angles Using Sonar Geometry", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNwidth, 287); ac++;
        XtSetArg(args[ac], XmNheight, 28); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(radioBox_mode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        toggleButton_mode_null = XmCreateToggleButton(radioBox_mode,
            (char *)"toggleButton_mode_null",
            args, 
            ac);
        XtManageChild(toggleButton_mode_null);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(toggleButton_mode_null, XmNvalueChangedCallback, do_anglemode, (XtPointer)0);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(bulletinBoard_mode, (char *)"Dismiss", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 120); ac++;
        XtSetArg(args[ac], XmNy, 120); ac++;
        XtSetArg(args[ac], XmNwidth, 100); ac++;
        XtSetArg(args[ac], XmNheight, 40); ac++;
        XtSetArg(args[ac], XmNfontList, 
            BX_CONVERT(bulletinBoard_mode, (char *)"-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
            XmRFontList, 0, &argok)); if (argok) ac++;
        pushButton_mode_dismiss = XmCreatePushButton(bulletinBoard_mode,
            (char *)"pushButton_mode_dismiss",
            args, 
            ac);
        XtManageChild(pushButton_mode_dismiss);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    XtAddCallback(pushButton_mode_dismiss, XmNactivateCallback, BxUnmanageCB, (XtPointer)"bulletinBoard_mode");
    
    
    /* Begin user code block <end_Createwindow_mbvelocity> */
    /* End user code block <end_Createwindow_mbvelocity> */
    return( window_mbvelocity );
}
